In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv("movies.csv")

In [3]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
movies.shape

(62423, 3)

In [5]:
movies.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [6]:
movies["genres"] = movies["genres"].apply(lambda x:x.replace("|", " "))

In [7]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy
1,2,Jumanji (1995),Adventure Children Fantasy
2,3,Grumpier Old Men (1995),Comedy Romance
3,4,Waiting to Exhale (1995),Comedy Drama Romance
4,5,Father of the Bride Part II (1995),Comedy

In [8]:
movies["genres"] = movies["genres"].str.lower()
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),adventure animation children comedy fantasy
1,2,Jumanji (1995),adventure children fantasy
2,3,Grumpier Old Men (1995),comedy romance
3,4,Waiting to Exhale (1995),comedy drama romance
4,5,Father of the Bride Part II (1995),comedy

In [9]:
tags = pd.read_csv("tags.csv")

In [10]:
tags.head()

   userId  movieId               tag   timestamp
0       3      260           classic  1439472355
1       3      260            sci-fi  1439472256
2       4     1732       dark comedy  1573943598
3       4     1732    great dialogue  1573943604
4       4     7569  so bad it's good  1573943455

In [11]:
tags.shape

(1093360, 4)

In [12]:
tags.isnull().sum()

userId        0
movieId       0
tag          16
timestamp     0
dtype: int64

In [13]:
tags.dropna(subset=["tag"], inplace = True)

In [14]:
tags.shape

(1093344, 4)

In [15]:
tags.isnull().sum()

userId       0
movieId      0
tag          0
timestamp    0
dtype: int64

In [16]:
tags

         userId  movieId                  tag   timestamp
0             3      260              classic  1439472355
1             3      260               sci-fi  1439472256
2             4     1732          dark comedy  1573943598
3             4     1732       great dialogue  1573943604
4             4     7569     so bad it's good  1573943455
...         ...      ...                  ...         ...
1093355  162521    66934  Neil Patrick Harris  1427311611
1093356  162521   103341     cornetto trilogy  1427311259
1093357  162534   189169               comedy  1527518175
1093358  162534   189169             disabled  1527518181
1093359  162534   189169              robbery  1527518193

[1093344 rows x 4 columns]

In [17]:
tags_grouped = tags.groupby("movieId")["tag"].apply(lambda x:" ".join(x)).reset_index()

In [18]:
tags_grouped

       movieId                                                tag
0            1  Owned imdb top 250 Pixar Pixar time travel chi...
1            2  Robin Williams time travel fantasy based on ch...
2            3  funny best friend duringcreditsstinger fishing...
3            4  based on novel or book chick flick divorce int...
4            5  aging baby confidence contraception daughter g...
...        ...                                                ...
45246   208813                                         might like
45247   208933                black and white deal with the devil
45248   209035  computer animation Japan mass behavior mass sc...
45249   209037  chameleon computer animation gluttony humorous...
45250   209063  black education friends schools independent sc...

[45251 rows x 2 columns]

In [19]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),adventure animation children comedy fantasy
1,2,Jumanji (1995),adventure children fantasy
2,3,Grumpier Old Men (1995),comedy romance
3,4,Waiting to Exhale (1995),comedy drama romance
4,5,Father of the Bride Part II (1995),comedy

In [20]:
tags_grouped.head()

   movieId                                                tag
0        1  Owned imdb top 250 Pixar Pixar time travel chi...
1        2  Robin Williams time travel fantasy based on ch...
2        3  funny best friend duringcreditsstinger fishing...
3        4  based on novel or book chick flick divorce int...
4        5  aging baby confidence contraception daughter g...

In [21]:
movies = movies.merge(tags_grouped, on="movieId", how="left")

In [22]:
movies

,movieId,title,genres,tag
0,1,Toy Story (1995),adventure animation children comedy fantasy,Owned imdb top 250 Pixar Pixar time travel chi...
1,2,Jumanji (1995),adventure children fantasy,Robin Williams time travel fantasy based on ch...
2,3,Grumpier Old Men (1995),comedy romance,funny best friend duringcreditsstinger fishing...
3,4,Waiting to Exhale (1995),comedy drama romance,based on novel or book chick flick divorce int...
4,5,Father of the Bride Part II (1995),comedy,aging baby confidence contraception daughter g...
...,...,...,...,...
62418,209157,We (2018),drama,NaN
62419,209159,Window of the Soul (2001),documentary,NaN
62420,209163,Bad Poems (2018),comedy drama,NaN
62421,209169,A Girl Thing (2001),(no genres listed),NaN
62422,209171,Women of Devil's Island (1962),action adventure drama,NaN

In [23]:
movies["tag"] = movies["tag"].fillna("")

In [24]:
movies

,movieId,title,genres,tag
0,1,Toy Story (1995),adventure animation children comedy fantasy,Owned imdb top 250 Pixar Pixar time travel chi...
1,2,Jumanji (1995),adventure children fantasy,Robin Williams time travel fantasy based on ch...
2,3,Grumpier Old Men (1995),comedy romance,funny best friend duringcreditsstinger fishing...
3,4,Waiting to Exhale (1995),comedy drama romance,based on novel or book chick flick divorce int...
4,5,Father of the Bride Part II (1995),comedy,aging baby confidence contraception daughter g...
...,...,...,...,...
62418,209157,We (2018),drama,
62419,209159,Window of the Soul (2001),documentary,
62420,209163,Bad Poems (2018),comedy drama,
62421,209169,A Girl Thing (2001),(no genres listed),
62422,209171,Women of Devil's Island (1962),action adventure drama,

In [25]:
movies["bag"] = movies["genres"] + " " + movies["tag"]

In [26]:
movies

,movieId,title,genres,tag,bag
0,1,Toy Story (1995),adventure animation children comedy fantasy,Owned imdb top 250 Pixar Pixar time travel chi...,adventure animation children comedy fantasy Ow...
1,2,Jumanji (1995),adventure children fantasy,Robin Williams time travel fantasy based on ch...,adventure children fantasy Robin Williams time...
2,3,Grumpier Old Men (1995),comedy romance,funny best friend duringcreditsstinger fishing...,comedy romance funny best friend duringcredits...
3,4,Waiting to Exhale (1995),comedy drama romance,based on novel or book chick flick divorce int...,comedy drama romance based on novel or book ch...
4,5,Father of the Bride Part II (1995),comedy,aging baby confidence contraception daughter g...,comedy aging baby confidence contraception dau...
...,...,...,...,...,...
62418,209157,We (2018),drama,,drama
62419,209159,Window of the Soul (2001),documentary,,documentary
62420,209163,Bad Poems (2018),comedy drama,,comedy drama
62421,209169,A Girl Thing (2001),(no genres listed),,(no genres listed)
62422,209171,Women of Devil's Island (1962),action adventure drama,,action adventure drama

In [27]:
movies["bag"] = movies["bag"].str.lower()

In [28]:
movies

,movieId,title,genres,tag,bag
0,1,Toy Story (1995),adventure animation children comedy fantasy,Owned imdb top 250 Pixar Pixar time travel chi...,adventure animation children comedy fantasy ow...
1,2,Jumanji (1995),adventure children fantasy,Robin Williams time travel fantasy based on ch...,adventure children fantasy robin williams time...
2,3,Grumpier Old Men (1995),comedy romance,funny best friend duringcreditsstinger fishing...,comedy romance funny best friend duringcredits...
3,4,Waiting to Exhale (1995),comedy drama romance,based on novel or book chick flick divorce int...,comedy drama romance based on novel or book ch...
4,5,Father of the Bride Part II (1995),comedy,aging baby confidence contraception daughter g...,comedy aging baby confidence contraception dau...
...,...,...,...,...,...
62418,209157,We (2018),drama,,drama
62419,209159,Window of the Soul (2001),documentary,,documentary
62420,209163,Bad Poems (2018),comedy drama,,comedy drama
62421,209169,A Girl Thing (2001),(no genres listed),,(no genres listed)
62422,209171,Women of Devil's Island (1962),action adventure drama,,action adventure drama

In [29]:
movies.drop(columns=["genres", "tag"], inplace = True)

In [30]:
movies

,movieId,title,bag
0,1,Toy Story (1995),adventure animation children comedy fantasy ow...
1,2,Jumanji (1995),adventure children fantasy robin williams time...
2,3,Grumpier Old Men (1995),comedy romance funny best friend duringcredits...
3,4,Waiting to Exhale (1995),comedy drama romance based on novel or book ch...
4,5,Father of the Bride Part II (1995),comedy aging baby confidence contraception dau...
...,...,...,...
62418,209157,We (2018),drama
62419,209159,Window of the Soul (2001),documentary
62420,209163,Bad Poems (2018),comedy drama
62421,209169,A Girl Thing (2001),(no genres listed)
62422,209171,Women of Devil's Island (1962),action adventure drama

In [31]:
movies.isnull().sum()

movieId    0
title      0
bag        0
dtype: int64

In [32]:
movies.shape

(62423, 3)

In [33]:
movies.reset_index(drop=True, inplace=True)

In [34]:
movies

,movieId,title,bag
0,1,Toy Story (1995),adventure animation children comedy fantasy ow...
1,2,Jumanji (1995),adventure children fantasy robin williams time...
2,3,Grumpier Old Men (1995),comedy romance funny best friend duringcredits...
3,4,Waiting to Exhale (1995),comedy drama romance based on novel or book ch...
4,5,Father of the Bride Part II (1995),comedy aging baby confidence contraception dau...
...,...,...,...
62418,209157,We (2018),drama
62419,209159,Window of the Soul (2001),documentary
62420,209163,Bad Poems (2018),comedy drama
62421,209169,A Girl Thing (2001),(no genres listed)
62422,209171,Women of Devil's Island (1962),action adventure drama

In [35]:
import nltk
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [36]:
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to C:\Users\Varun
[nltk_data]     Bahuguna\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\Varun
[nltk_data]     Bahuguna\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [37]:
from nltk.corpus import wordnet
from nltk import pos_tag

def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [38]:
def lemmatize_text(text):
    words = text.split()
    tagged_words = pos_tag(words)
    
    # lemmatized = [
    #     lemmatizer.lemmatize(word, get_wordnet_pos(tag))
    #     for word, tag in tagged_words
    # ]

    lemmatized = []

    for word, tag in tagged_words:
        lemmatized.append(lemmatizer.lemmatize(word, get_wordnet_pos(tag)))
    
    return " ".join(lemmatized)

In [39]:
movies["bag"] = movies["bag"].apply(lemmatize_text)

In [40]:
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
cv = CountVectorizer(max_features=5000, stop_words="english")

In [42]:
vectors = cv.fit_transform(movies["bag"])

In [43]:
vectors.shape

(62423, 5000)

In [44]:
cv.get_feature_names_out()[:1000]

array(['007', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10',
       '100', '11', '12', '13', '16th', '17', '17th', '18th', '1900s',
       '1910s', '1920', '1920s', '1930s', '1940s', '1950s', '1960',
       '1960s', '1970', '1970s', '1980', '1980s', '1990s', '1999', '19th',
       '20', '2000s', '2001', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017',
       '2018', '2019', '2020', '20th', '21st', '250', '2d', '30', '300',
       '35', '3d', '4th', '50', '51', '55', '60', '70', '70mm', '80',
       '90', '_moodwishlist', 'a24', 'aardman', 'aaron', 'abandon',
       'abandonment', 'abba', 'abduction', 'abigail', 'ability',
       'aborigine', 'abortion', 'abraham', 'abrams', 'abroad', 'abrupt',
       'absent', 'absorb', 'abstract', 'absurd', 'absurdism', 'absurdist',
       'abuse', 'abusive', 'academia', 'academy', 'accent', 'acceptance',
       'accident', 'accusation', 'accuse', 'act', 'acted', 'acting',
       'action', 'activism', 'activist', 'actor', 'actress', 'actual',
       'actually', 'adam', 'adams', 'adapt', 'adaptation', 'adapted',
       'adaption', 'add', 'addict', 'addiction', 'addition',
       'adolescence', 'adolf', 'adopt', 'adoption', 'adrenaline',
       'adrien', 'adult', 'adultery', 'adventure', 'adventurous',
       'adversity', 'advertising', 'aerial', 'aesthetic', 'affair',
       'affectionate', 'affleck', 'afghanistan', 'afi', 'africa',
       'african', 'aftercreditsstinger', 'afterlife', 'agatha', 'age',
       'agency', 'agent', 'ai', 'aid', 'air', 'aircraft', 'airplane',
       'airport', 'aki', 'akira', 'al', 'alabama', 'alain', 'alan',
       'alaska', 'alba', 'albert', 'alcatraz', 'alcohol', 'alcoholic',
       'alcoholism', 'alec', 'alejandro', 'alex', 'alexander',
       'alexandre', 'alfonso', 'alfred', 'ali', 'alice', 'alicia',
       'alien', 'alienation', 'aliens', 'alison', 'alive', 'allan',
       'allegorical', 'allegory', 'allen', 'alligator', 'allison',
       'almodovar', 'alps', 'alter', 'alternate', 'alternative', 'altman',
       'alzheimer', 'amanda', 'amateur', 'amaze', 'amazing', 'amazon',
       'ambient', 'ambiguity', 'ambiguous', 'ambition', 'ambitious',
       'ambulance', 'ambush', 'america', 'american', 'americana', 'amish',
       'amnesia', 'amoral', 'amsterdam', 'amusement', 'amy', 'anamorphic',
       'anarchic', 'anarchism', 'anarchy', 'ancient', 'anders',
       'anderson', 'andrei', 'andrew', 'andrews', 'android', 'andrzej',
       'andy', 'ang', 'angel', 'angela', 'angeles', 'angelina', 'anger',
       'angry', 'angst', 'animal', 'animate', 'animated', 'animation',
       'anime', 'aniston', 'anjelica', 'ann', 'anna', 'anne', 'annemari',
       'annette', 'annoy', 'ant', 'antagonist', 'antarctica', 'anthology',
       'anthony', 'anthropomorphic', 'anthropomorphism', 'anti',
       'antichrist', 'antihero', 'anton', 'antonio', 'anxiety', 'apache',
       'apartheid', 'apartment', 'apatow', 'ape', 'apocalypse',
       'apocalyptic', 'appeal', 'appealing', 'apple', 'apprentice',
       'arab', 'arabian', 'arcade', 'archaeologist', 'archaeology',
       'archeology', 'archery', 'architect', 'architecture', 'archive',
       'arctic', 'area', 'argentina', 'argento', 'aristocracy',
       'aristocrat', 'arizona', 'arkin', 'arm', 'armie', 'armor',
       'armstrong', 'army', 'arnold', 'aronofsky', 'arquette', 'arrange',
       'arrest', 'arrow', 'arson', 'art', 'arterton', 'arthouse',
       'arthur', 'arthurian', 'artificial', 'artist', 'artistic',
       'artists', 'artsy', 'artwork', 'asghar', 'ashley', 'ashton',
       'asia', 'asian', 'asimov', 'askew', 'asperger', 'aspire',
       'assassin', 'assassination', 'assassins', 'assault', 'assistant',
       'astaire', 'asteroid', 'astronaut', 'astronomy', 'asylum',
       'atheism', 'athlete', 'atkinson', 'atlanta', 'atlantis',
       'atmosphere', 'atmospheric', 'atomic', 'attachment', 'attack',
       'attempt', 'attenborough', 'attention', 'attorney', 'attract',
       'attraction', 'aubrey', 'audience', 'audition', 'audrey', 'aunt',
       'austen', 'austere', 'austin', 'australia', 'australian',
       'austria', 'authentic', 'authenticity', 'author', 'authoritarian',
       'autism', 'autobiographical', 'autobiography', 'automobile',
       'autopsy', 'available', 'avant', 'avenger', 'average', 'avi',
       'aviation', 'avorrida', 'awaken', 'award', 'aware', 'away', 'awe',
       'awesome', 'awful', 'awkward', 'awry', 'ax', 'aykroyd', 'baby',
       'babysitter', 'bacall', 'bachelor', 'background', 'bacon', 'bad',
       'badass', 'bag', 'bait', 'baker', 'baldwin', 'bale', 'ball',
       'ballet', 'balloon', 'ballroom', 'baltimore', 'ban', 'bana',
       'band', 'banderas', 'bandit', 'bangkok', 'bank', 'banking', 'bar',
       'barbara', 'barber', 'barbie', 'barcelona', 'bardem', 'bare',
       'barker', 'baron', 'barrier', 'barry', 'barrymore', 'bartender',
       'baruchel', 'base', 'baseball', 'basement', 'basil', 'basinger',
       'basketball', 'basque', 'bassett', 'bat', 'bateman', 'bates',
       'bath', 'bathtub', 'batman', 'battle', 'battlefield', 'baumbach',
       'bay', 'baz', 'bb', 'bbc', 'bd', 'bdsm', 'beach', 'bean', 'bear',
       'beast', 'beat', 'beatles', 'beautiful', 'beautifully', 'beauty',
       'bechdel', 'beckinsale', 'bed', 'bee', 'beer', 'begin', 'behavior',
       'bela', 'belgium', 'believable', 'bell', 'bellucci', 'belt',
       'belushi', 'ben', 'bend', 'bending', 'benedict', 'benicio',
       'benigni', 'bening', 'bergman', 'berlin', 'bernal', 'bernard',
       'berry', 'bertolucci', 'besson', 'best', 'bet', 'betamax',
       'betrayal', 'bettany', 'bette', 'betty', 'beverly', 'bfi', 'bgab',
       'bias', 'bible', 'biblical', 'bibliothek', 'bicycle', 'biel',
       'big', 'bigfoot', 'bike', 'biker', 'bikini', 'billionaire',
       'billy', 'binks', 'binoche', 'biographical', 'biography',
       'biological', 'biologist', 'biology', 'biopic', 'birch', 'bird',
       'birth', 'birthday', 'bisexual', 'bisexuality', 'bit', 'bite',
       'bitter', 'bittersweet', 'bizarre', 'bizzare', 'black',
       'blackmail', 'blade', 'blair', 'blake', 'blanchett', 'bland',
       'blasphemous', 'blaxploitation', 'bleak', 'blind', 'blindfold',
       'blindness', 'block', 'blogger', 'blomkamp', 'blonde', 'blood',
       'bloody', 'bloom', 'blow', 'blu', 'blue', 'blunt', 'board', 'boat',
       'bob', 'body', 'bodyguard', 'bogart', 'bollywood', 'bomb',
       'bomber', 'bond', 'bondage', 'bong', 'bonham', 'boob', 'booby',
       'book', 'bookshop', 'boot', 'booth', 'border', 'borderline',
       'bore', 'boring', 'boris', 'bos', 'boston', 'bounty', 'bow',
       'bowery', 'bowie', 'bowl', 'bowling', 'box', 'boxer', 'boxing',
       'boy', 'boyega', 'boyfriend', 'boyle', 'boys', 'br', 'brad',
       'bradley', 'braff', 'brain', 'brainwash', 'branagh', 'brand',
       'brando', 'brat', 'bravery', 'brawl', 'brazil', 'brazilian',
       'break', 'breakdown', 'breakthrough', 'breakup', 'breast',
       'breathtaking', 'brendan', 'breslin', 'brett', 'brian', 'bride',
       'bridge', 'brie', 'brief', 'bright', 'brilliant', 'brit',
       'britain', 'british', 'brittany', 'broadway', 'broderick', 'brody',
       'broken', 'brolin', 'bromance', 'bromantic', 'bronson', 'brook',
       'brooklyn', 'bros', 'brosnan', 'brothel', 'brother', 'brotherhood',
       'brown', 'bruce', 'bruno', 'brutal', 'brutality', 'bryan', 'bryce',
       'btaege', 'budapest', 'buddhism', 'buddhist', 'buddy', 'budget',
       'buenos', 'bug', 'build', 'building', 'bull', 'bullet', 'bullock',
       'bullshit', 'bully', 'bullying', 'bunker', 'bunny', 'bureaucracy',
       'burgess', 'burglar', 'burglary', 'burn', 'burroughs', 'burt',
       'burton', 'bury', 'bus', 'buscemi', 'bush', 'business', 'buster',
       'butcher', 'butler', 'butt', 'butterfly', 'buy', 'byrne', 'caan',
       'cabin', 'cable', 'cage', 'cagney', 'caine', 'california', 'calm',
       'cam', 'cambodia', 'cameo', 'camera', 'camerawork', 'cameron',
       'camp', 'campaign', 'campbell', 'campy', 'canada', 'canadian',
       'cancer', 'candy', 'cannabis', 'cannes', 'cannibal', 'cannibalism',
       'canuxploitation', 'caper', 'capitalism', 'capote', 'capra',
       'captain', 'captivate', 'captive', 'capture', 'car', 'card',
       'care', 'career', 'carell', 'carey', 'caribbean', 'carl', 'carlos',
       'carnival', 'carol', 'carolina', 'carpenter', 'carrey', 'carrie',
       'carroll', 'carry', 'cartel', 'carter', 'cartoon', 'cartoonish',
       'cary', 'case', 'casey', 'cash', 'casino', 'cassel', 'cast',
       'casting', 'castle', 'castration', 'cat', 'catastrophe', 'catchy',
       'cate', 'cathartic', 'catherine', 'catholic', 'catholicism',
       'cattle', 'cav', 'cavalry', 'cave', 'caveman', 'cavill',
       'celebration', 'celebrity', 'cell', 'cello', 'celtic', 'cemetery',
       'censorship', 'center', 'central', 'century', 'cera', 'cerebral',
       'cg', 'cgi', 'chain', 'chainsaw', 'chair', 'chalamet', 'challenge',
       'chamber', 'champion', 'chan', 'chance', 'change', 'channel',
       'channing', 'chaos', 'chaplin', 'character', 'characterization',
       'charles', 'charlie', 'charlize', 'charlotte', 'charlton', 'charm',
       'chase', 'chastain', 'chazelle', 'che', 'cheadle', 'cheap',
       'cheat', 'cheek', 'cheerlead', 'cheerleader', 'cheers', 'cheese',
       'cheesy', 'chef', 'chemistry', 'chess', 'chevy', 'chicago',
       'chick', 'chicken', 'chief', 'child', 'childbirth', 'childhood',
       'childish', 'children', 'chile', 'chimpanzee', 'china', 'chinese',
       'chloe', 'chloë', 'cho', 'chocolate', 'choice', 'choir',
       'choreographic', 'choreography', 'chosen', 'chow', 'chris',
       'christ', 'christensen', 'christian', 'christianity', 'christie',
       'christina', 'christmas', 'christoph', 'christopher', 'chuck',
       'chun', 'church', 'cia', 'cigarette', 'cillian', 'cinderella',
       'cinema', 'cinematic', 'cinematographer', 'cinematography',
       'cinéma', 'circus', 'citizen', 'city', 'civil', 'civilization',
       'claire', 'clancy', 'clark', 'clarke', 'clash', 'class', 'classic',
       'classical', 'classroom', 'claude', 'claus', 'claustrophobic',
       'claymation', 'clea', 'clean', 'cleese', 'clement', 'clerk',
       'clever', 'cliche', 'cliched', 'cliché', 'cliff', 'cliffhanger',
       'climate', 'climb', 'clint', 'clique', 'clive', 'clock', 'clone',
       'clooney', 'close', 'closet', 'clown', 'club', 'clv', 'coach',
       'coal', 'coast', 'cocaine', 'code', 'coen', 'coffee', 'coffin',
       'cohen', 'coincidence', 'cold', 'cole', 'colin', 'collar',
       'collection', 'collector', 'college', 'collette', 'collins',
       'colombia', 'colonial', 'colonialism', 'colony', 'color',
       'colorado', 'colorful', 'colour', 'colourful', 'columbus', 'com',
       'coma', 'combat', 'come', 'comeback', 'comedian', 'comedic',
       'comedy', 'comet', 'comic', 'comical', 'coming', 'commando',
       'commentary', 'commercial', 'common', 'commune', 'communication',
       'communism', 'communist', 'community', 'company', 'compare',
       'compassion', 'compassionate', 'compel', 'competition', 'complex',
       'complicate', 'complicated', 'composer', 'compulsive', 'computer',
       'conan', 'concentration', 'concept', 'concert', 'condition',
       'confession', 'confidence', 'confine', 'conflict', 'conformity',
       'confrontational', 'confuse', 'confusion', 'congress',
       'connecticut', 'connection', 'connelly', 'connery', 'connolly',
       'conrad', 'conscience', 'consciousness', 'conspiracy', 'construct',
       'construction', 'consumerism', 'contact', 'contemplative'],
      dtype=object)

In [45]:
from sklearn.metrics.pairwise import cosine_similarity

In [46]:
def recommend(movie_name):
    movie_name = movie_name.lower()
    
    matches = movies[movies["title"].str.lower().str.contains(movie_name)]
    
    if matches.empty:
        print("Movie not found 😅")
        return
    
    idx = matches.index[0]
    
    # 🔥 KEY LINE (on-the-fly similarity)
    dist = cosine_similarity(vectors[idx], vectors).flatten()
    
    scores = sorted(list(enumerate(dist)), reverse = True, key = lambda x : x[1])[1:6]

    rec = []
    # top 5
    for i in scores:
        rec.append(movies.iloc[i[0]].title)

    return rec

In [47]:
recommend("shawshank")

['Seven (a.k.a. Se7en) (1995)',
 'Year of the Tiger, The (Año del tigre, El) (2011)',
 'Lucky Number Slevin (2006)',
 'Escapist, The (2008)',
 'Sixth Sense, The (1999)']

In [48]:
recommend("fight club")

['Primal Fear (1996)',
 'Seven (a.k.a. Se7en) (1995)',
 'The Machinist (2004)',
 'Shutter Island (2010)',
 'Sixth Sense, The (1999)']

In [49]:
recommend("toy story")

['Toy Story 2 (1999)',
 "Bug's Life, A (1998)",
 'Monsters, Inc. (2001)',
 'The Adventures of André and Wally B. (1984)',
 'Toy Story 3 (2010)']