In [1]:
import numpy as np
import pandas as pd

In [7]:
movies = pd.read_csv(
    r"C:\Users\Varun Bahuguna\OneDrive\Desktop\content-based-recommendation-system\data\movies.dat",
    sep="::",
    engine="python",
    names=["id", "title", "genres"]
)

In [8]:
movies.head()

,id,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [9]:
movies.shape

(10681, 3)

In [10]:
movies.isnull().sum()

id        0
title     0
genres    0
dtype: int64

In [11]:
movies["genres"] = movies["genres"].str.lower()

In [12]:
movies.head()

,id,title,genres
0,1,Toy Story (1995),adventure|animation|children|comedy|fantasy
1,2,Jumanji (1995),adventure|children|fantasy
2,3,Grumpier Old Men (1995),comedy|romance
3,4,Waiting to Exhale (1995),comedy|drama|romance
4,5,Father of the Bride Part II (1995),comedy

In [13]:
movies["genres"] = movies["genres"].apply(lambda x:x.split('|'))

In [14]:
movies

,id,title,genres
0,1,Toy Story (1995),"[adventure, animation, children, comedy, fantasy]"
1,2,Jumanji (1995),"[adventure, children, fantasy]"
2,3,Grumpier Old Men (1995),"[comedy, romance]"
3,4,Waiting to Exhale (1995),"[comedy, drama, romance]"
4,5,Father of the Bride Part II (1995),[comedy]
...,...,...,...
10676,65088,Bedtime Stories (2008),"[adventure, children, comedy]"
10677,65091,Manhattan Melodrama (1934),"[crime, drama, romance]"
10678,65126,Choke (2008),"[comedy, drama]"
10679,65130,Revolutionary Road (2008),"[drama, romance]"
10680,65133,Blackadder Back & Forth (1999),[comedy]

In [15]:
from sklearn.preprocessing import MultiLabelBinarizer

In [16]:
mlb = MultiLabelBinarizer()

genre_matrix = mlb.fit_transform(movies["genres"])

In [17]:
genre_matrix[0]

array([0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
print(mlb.classes_)

['(no genres listed)' 'action' 'adventure' 'animation' 'children' 'comedy'
 'crime' 'documentary' 'drama' 'fantasy' 'film-noir' 'horror' 'imax'
 'musical' 'mystery' 'romance' 'sci-fi' 'thriller' 'war' 'western']

In [19]:
genre_df = pd.DataFrame(genre_matrix, columns=mlb.classes_) # convert to DataFrame

In [20]:
genre_df

,(no genres listed),action,adventure,animation,children,comedy,crime,documentary,drama,fantasy,film-noir,horror,imax,musical,mystery,romance,sci-fi,thriller,war,western
0,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10676,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10677,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0
10678,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
10679,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
10680,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [21]:
genre_df.drop(columns=["(no genres listed)"], inplace=True)

In [22]:
genre_df

,action,adventure,animation,children,comedy,crime,documentary,drama,fantasy,film-noir,horror,imax,musical,mystery,romance,sci-fi,thriller,war,western
0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10676,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10677,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0
10678,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
10679,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0
10680,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [23]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity = cosine_similarity(genre_df)

In [ ]:
similarity

In [ ]:
similarity[0]

In [ ]:
def recommend(movie_title):
    # get index
    idx = movies[movies["title"] == movie_title].index[0]
    
    dist = similarity[idx]

    scores = sorted(list(enumerate(dist)), reverse = True, key = lambda x : x[1])[1:6]

    rec = []
    
    for i in scores:
        rec.append(movies.iloc[i[0]].title)

    return rec

In [ ]:
recommend("Shawshank Redemption, The (1994)")

In [ ]:
recommend("Fight Club (1999)")

In [ ]:
recommend("Iron Man (2008)")