In [1]:
import pandas as pd
import numpy as np

In [2]:
credits = pd.read_csv(r"C:\Users\Varun Bahuguna\OneDrive\Desktop\content-based-recommendation-system\data\credits.csv")
keywords = pd.read_csv(r"C:\Users\Varun Bahuguna\OneDrive\Desktop\content-based-recommendation-system\data\keywords.csv")
meta = pd.read_csv(r"C:\Users\Varun Bahuguna\OneDrive\Desktop\content-based-recommendation-system\data\movies_metadata.csv")

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_16464\3024848566.py:3: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  meta = pd.read_csv(r"C:\Users\Varun Bahuguna\OneDrive\Desktop\content-based-recommendation-system\data\movies_metadata.csv")

In [3]:
credits

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862
...,...,...,...
45471,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de...",439050
45472,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",111109
45473,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",67758
45474,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",227506
45475,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",461257

In [4]:
credits.shape

(45476, 3)

In [5]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB

In [6]:
keywords

           id                                           keywords
0         862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1        8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2       15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3       31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4       11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...
...       ...                                                ...
46414  439050             [{'id': 10703, 'name': 'tragic love'}]
46415  111109  [{'id': 2679, 'name': 'artist'}, {'id': 14531,...
46416   67758                                                 []
46417  227506                                                 []
46418  461257                                                 []

[46419 rows x 2 columns]

In [7]:
keywords.shape

(46419, 2)

In [8]:
keywords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46419 entries, 0 to 46418
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46419 non-null  int64
 1   keywords  46419 non-null  object
dtypes: int64(1), object(1)
memory usage: 725.4+ KB

In [9]:
meta

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [10]:
meta.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [11]:
meta.shape

(45466, 24)

In [12]:
meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [13]:
# id is the common column in all, and its int in credits and keywords, but is string in meta
# convert string id in meta to int id !

meta['id'] = pd.to_numeric(meta['id'], errors='coerce')

In [14]:
meta['id'].isnull().sum()

np.int64(3)

In [15]:
meta[meta['id'].isnull()]

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
19730,- Written by Ørnås,0.065736,/ff9qCepilowshEtG2GYWwzt2bs4.jpg,"[{'name': 'Carousel Productions', 'id': 11176}...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",NaN,0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29503,Rune Balot goes to a casino connected to the ...,1.931659,/zV8bHuSL6WXoD6FWogP9j4x80bL.jpg,"[{'name': 'Aniplex', 'id': 2883}, {'name': 'Go...","[{'iso_3166_1': 'US', 'name': 'United States o...",NaN,0,68.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,...,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35587,Avalanche Sharks tells the story of a bikini ...,2.185485,/zaSf5OG7V8X8gqFvly88zDdRm46.jpg,"[{'name': 'Odyssey Media', 'id': 17161}, {'nam...","[{'iso_3166_1': 'CA', 'name': 'Canada'}]",NaN,0,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,...,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
meta = meta.dropna(subset=["id"])

In [17]:
meta.shape

(45463, 24)

In [18]:
meta.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45463 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45463 non-null  object
 1   belongs_to_collection  4491 non-null   object
 2   budget                 45463 non-null  object
 3   genres                 45463 non-null  object
 4   homepage               7779 non-null   object
 5   id                     45463 non-null  float64
 6   imdb_id                45446 non-null  object
 7   original_language      45452 non-null  object
 8   original_title         45463 non-null  object
 9   overview               44509 non-null  object
 10  popularity             45460 non-null  object
 11  poster_path            45077 non-null  object
 12  production_companies   45460 non-null  object
 13  production_countries   45460 non-null  object
 14  release_date           45376 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(5), object(19)
memory usage: 8.7+ MB

In [19]:
meta["release_date"]

0        1995-10-30
1        1995-12-15
2        1995-12-22
3        1995-12-22
4        1995-02-10
            ...
45461           NaN
45462    2011-11-17
45463    2003-08-01
45464    1917-10-21
45465    2017-06-09
Name: release_date, Length: 45463, dtype: object

In [20]:
# Convert release_date to datetime and extract year
meta['year'] = pd.to_datetime(meta['release_date'], errors='coerce').dt.year.fillna(0).astype(int)

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_16464\3858204944.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta['year'] = pd.to_datetime(meta['release_date'], errors='coerce').dt.year.fillna(0).astype(int)

In [21]:
meta

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,year
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862.0,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,1995
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844.0,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,1995
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602.0,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,1995
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357.0,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,1995
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862.0,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050.0,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0,0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109.0,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0,2011
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758.0,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0,2003
45464,False,NaN,0,[],NaN,227506.0,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0,1917
45465,False,NaN,0,[],NaN,461257.0,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0,2017

In [22]:
# Create a unique display title: "Toy Story (1995)"
# We do this BEFORE the merge to ensure we have the year ready
meta['title'] = meta['title'] + " (" + meta['year'].astype(str) + ")"

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_16464\2973620798.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta['title'] = meta['title'] + " (" + meta['year'].astype(str) + ")"

In [23]:
meta['title']

0                          Toy Story (1995)
1                            Jumanji (1995)
2                   Grumpier Old Men (1995)
3                  Waiting to Exhale (1995)
4        Father of the Bride Part II (1995)
                        ...
45461                            Subdue (0)
45462            Century of Birthing (2011)
45463                       Betrayal (2003)
45464               Satan Triumphant (1917)
45465                       Queerama (2017)
Name: title, Length: 45463, dtype: object

In [24]:
meta.duplicated(subset = ["title"]).sum()

np.int64(83)

In [25]:
meta[meta.duplicated(subset = ["title"], keep = False)].sort_values("title")

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,year
24109,False,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",NaN,2965.0,tt0118247,en,"20,000 Leagues Under the Sea","In the 19th century, an expert marine biologis...",...,0.0,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Darkness is to be feared... above and below.,"20,000 Leagues Under the Sea (1997)",False,6.3,3.0,1997
20848,False,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,2966.0,tt0118248,en,"20,000 Leagues Under the Sea","The year is 1886, when New England's fishing h...",...,0.0,158.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Welcome to the last place on earth.,"20,000 Leagues Under the Sea (1997)",False,4.6,13.0,1997
949,False,NaN,4,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,22649.0,tt0022879,en,A Farewell to Arms,British nurse Catherine Barkley (Helen Hayes) ...,...,25.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Every woman who has loved will understand,A Farewell to Arms (1932),False,6.2,29.0,1932
15074,False,NaN,4,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,22649.0,tt0022879,en,A Farewell to Arms,British nurse Catherine Barkley (Helen Hayes) ...,...,25.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Every woman who has loved will understand,A Farewell to Arms (1932),False,6.2,29.0,1932
2564,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,84198.0,tt1736049,en,A Place at the Table,"Using personal stories, this powerful document...",...,0.0,84.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,One Nation. Underfed.,A Place at the Table (2012),False,6.9,7.0,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
838,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,132641.0,tt0046468,ja,Tsuma,"Ten years into a marriage, the wife is disappo...",...,0.0,89.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Wife (1953),False,0.0,0.0,1953
30001,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,132641.0,tt0046468,ja,Tsuma,"Ten years into a marriage, the wife is disappo...",...,0.0,89.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Wife (1953),False,0.0,0.0,1953
19729,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,82663.0,tt0113002,en,Midnight Man,British soldiers force a recently captured IRA...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
29502,False,"{'id': 122661, 'name': 'Mardock Scramble Colle...",0,"[{'id': 16, 'name': 'Animation'}, {'id': 878, ...",http://m-scramble.jp/exhaust/,122662.0,tt2423504,ja,マルドゥック・スクランブル 排気,Third film of the Mardock Scramble series.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
35586,False,NaN,0,"[{'id': 10770, 'name': 'TV Movie'}, {'id': 28,...",NaN,249260.0,tt2622826,en,Avalanche Sharks,A group of skiers are terrorized during spring...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [26]:
meta.drop_duplicates(subset=["title"], keep="first", inplace=True)

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_16464\3109040338.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta.drop_duplicates(subset=["title"], keep="first", inplace=True)

In [27]:
meta.shape

(45380, 25)

In [28]:
credits.shape

(45476, 3)

In [29]:
credits.duplicated(subset=['id']).sum()

np.int64(44)

In [30]:
credits[credits.duplicated(subset = ["id"], keep = False)].sort_values("id")

,cast,crew,id
25950,"[{'cast_id': 12, 'character': 'The Creature', ...","[{'credit_id': '52fe4380c3a36847f80590dd', 'de...",3057
25885,"[{'cast_id': 12, 'character': 'The Creature', ...","[{'credit_id': '52fe4380c3a36847f80590dd', 'de...",3057
5865,"[{'cast_id': 15, 'character': 'Chuck Barris', ...","[{'credit_id': '52fe43e2c3a36847f80760b5', 'de...",4912
33838,"[{'cast_id': 15, 'character': 'Chuck Barris', ...","[{'credit_id': '52fe43e2c3a36847f80760a9', 'de...",4912
9165,"[{'cast_id': 11, 'character': 'Jef Costello', ...","[{'credit_id': '52fe440ac3a36847f807ee01', 'de...",5511
...,...,...,...
25954,"[{'cast_id': 7, 'character': 'Hollander', 'cre...","[{'credit_id': '52fe4da29251416c9111ce5d', 'de...",199591
24163,"[{'cast_id': 2, 'character': 'Ebba', 'credit_i...","[{'credit_id': '534fd1a80e0a267eb6000e32', 'de...",265189
45275,"[{'cast_id': 2, 'character': 'Ebba', 'credit_i...","[{'credit_id': '534fd1a80e0a267eb6000e32', 'de...",265189
33196,"[{'cast_id': 1, 'character': 'Jenjira', 'credi...","[{'credit_id': '5448c8efc3a3680fb4001582', 'de...",298721
40051,"[{'cast_id': 1, 'character': 'Jenjira', 'credi...","[{'credit_id': '5739ceeac3a3683c9d000c12', 'de...",298721

In [31]:
credits = credits.drop_duplicates(subset=['id'])

In [32]:
credits.duplicated(subset=['id']).sum()

np.int64(0)

In [33]:
credits.shape

(45432, 3)

In [34]:
keywords.shape

(46419, 2)

In [35]:
keywords.duplicated(subset=['id']).sum()

np.int64(987)

In [36]:
keywords[keywords.duplicated(subset = ["id"], keep = False)].sort_values("id")

           id                                           keywords
37095    1998  [{'id': 417, 'name': 'corruption'}, {'id': 612...
36138    1998  [{'id': 417, 'name': 'corruption'}, {'id': 612...
36822    3025  [{'id': 212, 'name': 'london england'}, {'id':...
35865    3025  [{'id': 212, 'name': 'london england'}, {'id':...
35999    3692  [{'id': 470, 'name': 'spy'}, {'id': 591, 'name...
...       ...                                                ...
36190  380841                                                 []
36193  380864                                                 []
37150  380864                                                 []
37280  381353                                                 []
36323  381353                                                 []

[1972 rows x 2 columns]

In [37]:
keywords = keywords.drop_duplicates(subset=['id'])

In [38]:
keywords.duplicated(subset=['id']).sum()

np.int64(0)

In [39]:
keywords.shape

(45432, 2)

In [40]:
meta.shape

(45380, 25)

In [41]:
meta.duplicated(subset=['id']).sum()

np.int64(0)

In [42]:
movies = meta.merge(credits, on='id').merge(keywords, on='id')

In [43]:
movies

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,status,tagline,title,video,vote_average,vote_count,year,cast,crew,keywords
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862.0,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,Released,NaN,Toy Story (1995),False,7.7,5415.0,1995,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844.0,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,Released,Roll the dice and unleash the excitement!,Jumanji (1995),False,6.9,2413.0,1995,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602.0,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men (1995),False,6.5,92.0,1995,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357.0,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,Released,Friends are the people who let you be yourself...,Waiting to Exhale (1995),False,6.1,34.0,1995,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862.0,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II (1995),False,5.7,173.0,1995,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45374,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050.0,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,Released,Rising and falling between a man and woman,Subdue (0),False,4.0,1.0,0,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de...","[{'id': 10703, 'name': 'tragic love'}]"
45375,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109.0,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,Released,NaN,Century of Birthing (2011),False,9.0,3.0,2011,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...","[{'id': 2679, 'name': 'artist'}, {'id': 14531,..."
45376,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758.0,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,Released,A deadly game of wits.,Betrayal (2003),False,3.8,6.0,2003,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",[]
45377,False,NaN,0,[],NaN,227506.0,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,Released,NaN,Satan Triumphant (1917),False,0.0,0.0,1917,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",[]
45378,False,NaN,0,[],NaN,461257.0,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,Released,NaN,Queerama (2017),False,0.0,0.0,2017,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",[]

In [44]:
movies.shape

(45379, 28)

In [45]:
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'year', 'cast', 'crew', 'keywords'],
      dtype='object')

In [46]:
movies["status"]

0        Released
1        Released
2        Released
3        Released
4        Released
           ...
45374    Released
45375    Released
45376    Released
45377    Released
45378    Released
Name: status, Length: 45379, dtype: object

In [47]:
movies["status"].value_counts()

status
Released           44933
Rumored              229
Post Production       98
In Production         20
Planned               15
Canceled               2
Name: count, dtype: int64

In [48]:
movies = movies[movies['status'] == 'Released']

In [49]:
movies.shape

(44933, 28)

In [50]:
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'year', 'cast', 'crew', 'keywords'],
      dtype='object')

In [51]:
movies["vote_count"].describe()

count    44933.000000
mean       111.042107
std        494.055996
min          0.000000
25%          3.000000
50%         10.000000
75%         35.000000
max      14075.000000
Name: vote_count, dtype: float64

In [52]:
movies = movies[movies['vote_count'] >= 34]

In [53]:
movies.shape

(11486, 28)

In [54]:
# Constants based on your descriptive stats
m = 34
C = movies['vote_average'].mean()

def weighted_rating(x, m=m, C=C):
    v = x['vote_count']
    R = x['vote_average']
    # Calculation based on the IMDB formula
    return (v/(v+m) * R) + (m/(v+m) * C)

In [55]:
# Create the score column
movies['new_vote_avg'] = movies.apply(weighted_rating, axis=1)

In [56]:
movies["new_vote_avg"].describe()

count    11486.000000
mean         6.341170
std          0.687176
min          3.128337
25%          5.887334
50%          6.366945
75%          6.803588
max          8.963919
Name: new_vote_avg, dtype: float64

In [57]:
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'year', 'cast', 'crew', 'keywords',
       'new_vote_avg'],
      dtype='object')

In [58]:
movies["runtime"]

0         81.0
1        104.0
2        101.0
3        127.0
4        106.0
         ...
45261     90.0
45286     83.0
45293     83.0
45350      4.0
45354    101.0
Name: runtime, Length: 11486, dtype: float64

In [59]:
movies = movies[movies["runtime"]>50]

In [60]:
movies.shape

(11226, 29)

In [61]:
movies["runtime"].describe()

count    11226.000000
mean       106.165865
std         27.300657
min         51.000000
25%         92.000000
50%        101.000000
75%        115.000000
max        877.000000
Name: runtime, dtype: float64

In [62]:
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'year', 'cast', 'crew', 'keywords',
       'new_vote_avg'],
      dtype='object')

In [63]:
movies = movies[['genres', 'id', 'overview', 'title', 'cast', 'crew', 'keywords', 'vote_count', 'new_vote_avg']]

In [64]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",5415.0,7.691379
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",2413.0,6.891918
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",92.0,6.450979
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",34.0,6.209168
4,"[{'id': 35, 'name': 'Comedy'}]",11862.0,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995),"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",173.0,5.801562
...,...,...,...,...,...,...,...,...,...
45256,"[{'id': 35, 'name': 'Comedy'}]",248705.0,"Stuck in the corridors of time, Godefroy de Mo...",The Visitors: Bastille Day (2016),"[{'cast_id': 2, 'character': 'Le comte Godefro...","[{'credit_id': '52fe4f37c3a36847f82c5efb', 'de...","[{'id': 2652, 'name': 'nazis'}, {'id': 3098, '...",167.0,4.392156
45261,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",44918.0,On the 100th anniversary of the original voyag...,Titanic 2 (2010),"[{'cast_id': 1, 'character': 'Hayden Walsh', '...","[{'credit_id': '52fe46a3c3a36847f810a04b', 'de...","[{'id': 9937, 'name': 'suspense'}]",55.0,4.514870
45286,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",426272.0,Ray is a fledgling entrepreneur who specialize...,Take Me (2017),"[{'cast_id': 1, 'character': 'Anna St. Blair',...","[{'credit_id': '582c3222c3a36872c0006604', 'de...",[],38.0,6.150325
45293,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",432789.0,"Burned by a bad breakup, a struggling New York...",The Incredible Jessica James (2017),"[{'cast_id': 6, 'character': 'Jessica James', ...","[{'credit_id': '586a688dc3a3680f4e017d65', 'de...",[],37.0,6.256668
45354,"[{'id': 35, 'name': 'Comedy'}]",14008.0,Hyperactive teenager Kelly is enrolled into a ...,Cadet Kelly (2002),"[{'cast_id': 1, 'character': 'Kelly Collins', ...","[{'credit_id': '52fe45c29251416c75061803', 'de...","[{'id': 171803, 'name': 'military school'}]",145.0,5.412421

In [65]:
movies.shape

(11226, 9)

In [66]:
movies.isnull().sum()

genres           0
id               0
overview        18
title            0
cast             0
crew             0
keywords         0
vote_count       0
new_vote_avg     0
dtype: int64

In [67]:
movies['overview'] = movies['overview'].fillna('')

In [68]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",5415.0,7.691379
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",2413.0,6.891918
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",92.0,6.450979
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",34.0,6.209168
4,"[{'id': 35, 'name': 'Comedy'}]",11862.0,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995),"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",173.0,5.801562
...,...,...,...,...,...,...,...,...,...
45256,"[{'id': 35, 'name': 'Comedy'}]",248705.0,"Stuck in the corridors of time, Godefroy de Mo...",The Visitors: Bastille Day (2016),"[{'cast_id': 2, 'character': 'Le comte Godefro...","[{'credit_id': '52fe4f37c3a36847f82c5efb', 'de...","[{'id': 2652, 'name': 'nazis'}, {'id': 3098, '...",167.0,4.392156
45261,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",44918.0,On the 100th anniversary of the original voyag...,Titanic 2 (2010),"[{'cast_id': 1, 'character': 'Hayden Walsh', '...","[{'credit_id': '52fe46a3c3a36847f810a04b', 'de...","[{'id': 9937, 'name': 'suspense'}]",55.0,4.514870
45286,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",426272.0,Ray is a fledgling entrepreneur who specialize...,Take Me (2017),"[{'cast_id': 1, 'character': 'Anna St. Blair',...","[{'credit_id': '582c3222c3a36872c0006604', 'de...",[],38.0,6.150325
45293,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",432789.0,"Burned by a bad breakup, a struggling New York...",The Incredible Jessica James (2017),"[{'cast_id': 6, 'character': 'Jessica James', ...","[{'credit_id': '586a688dc3a3680f4e017d65', 'de...",[],37.0,6.256668
45354,"[{'id': 35, 'name': 'Comedy'}]",14008.0,Hyperactive teenager Kelly is enrolled into a ...,Cadet Kelly (2002),"[{'cast_id': 1, 'character': 'Kelly Collins', ...","[{'credit_id': '52fe45c29251416c75061803', 'de...","[{'id': 171803, 'name': 'military school'}]",145.0,5.412421

In [69]:
# Check for empty lists in JSON columns
for col in ['genres', 'cast', 'crew', 'keywords']:
    empty_count = movies[col].apply(lambda x: x == [] or x == "[]").sum()
    print(f"Movies with empty {col}: {empty_count}")

Movies with empty genres: 8
Movies with empty cast: 17
Movies with empty crew: 9
Movies with empty keywords: 1041

In [70]:
movies = movies[movies['cast'].apply(lambda x: len(x) > 0 and x != '[]')]
movies = movies[movies['crew'].apply(lambda x: len(x) > 0 and x != '[]')]
movies = movies[movies['genres'].apply(lambda x: len(x) > 0 and x != '[]')]

In [71]:
# Check for empty lists in JSON columns
for col in ['genres', 'cast', 'crew', 'keywords']:
    empty_count = movies[movies[col].apply(lambda x: x == [] or x == "[]")].shape[0]
    print(f"Movies with empty {col}: {empty_count}")

Movies with empty genres: 0
Movies with empty cast: 0
Movies with empty crew: 0
Movies with empty keywords: 1029

In [72]:
movies.shape

(11195, 9)

In [73]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",5415.0,7.691379
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",2413.0,6.891918
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",92.0,6.450979
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",34.0,6.209168
4,"[{'id': 35, 'name': 'Comedy'}]",11862.0,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995),"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",173.0,5.801562
...,...,...,...,...,...,...,...,...,...
45256,"[{'id': 35, 'name': 'Comedy'}]",248705.0,"Stuck in the corridors of time, Godefroy de Mo...",The Visitors: Bastille Day (2016),"[{'cast_id': 2, 'character': 'Le comte Godefro...","[{'credit_id': '52fe4f37c3a36847f82c5efb', 'de...","[{'id': 2652, 'name': 'nazis'}, {'id': 3098, '...",167.0,4.392156
45261,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",44918.0,On the 100th anniversary of the original voyag...,Titanic 2 (2010),"[{'cast_id': 1, 'character': 'Hayden Walsh', '...","[{'credit_id': '52fe46a3c3a36847f810a04b', 'de...","[{'id': 9937, 'name': 'suspense'}]",55.0,4.514870
45286,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",426272.0,Ray is a fledgling entrepreneur who specialize...,Take Me (2017),"[{'cast_id': 1, 'character': 'Anna St. Blair',...","[{'credit_id': '582c3222c3a36872c0006604', 'de...",[],38.0,6.150325
45293,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",432789.0,"Burned by a bad breakup, a struggling New York...",The Incredible Jessica James (2017),"[{'cast_id': 6, 'character': 'Jessica James', ...","[{'credit_id': '586a688dc3a3680f4e017d65', 'de...",[],37.0,6.256668
45354,"[{'id': 35, 'name': 'Comedy'}]",14008.0,Hyperactive teenager Kelly is enrolled into a ...,Cadet Kelly (2002),"[{'cast_id': 1, 'character': 'Kelly Collins', ...","[{'credit_id': '52fe45c29251416c75061803', 'de...","[{'id': 171803, 'name': 'military school'}]",145.0,5.412421

In [74]:
movies.iloc[0].genres

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [75]:
import ast

def convert(obj):
    L = []

    for i in ast.literal_eval(obj):
        L.append(i['name'])

    return L

In [76]:
movies["genres"] = movies["genres"].apply(convert)

In [77]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[Animation, Comedy, Family]",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",5415.0,7.691379
1,"[Adventure, Fantasy, Family]",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",2413.0,6.891918
2,"[Romance, Comedy]",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",92.0,6.450979
3,"[Comedy, Drama, Romance]",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",34.0,6.209168
4,[Comedy],11862.0,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995),"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",173.0,5.801562
...,...,...,...,...,...,...,...,...,...
45256,[Comedy],248705.0,"Stuck in the corridors of time, Godefroy de Mo...",The Visitors: Bastille Day (2016),"[{'cast_id': 2, 'character': 'Le comte Godefro...","[{'credit_id': '52fe4f37c3a36847f82c5efb', 'de...","[{'id': 2652, 'name': 'nazis'}, {'id': 3098, '...",167.0,4.392156
45261,"[Action, Adventure, Thriller]",44918.0,On the 100th anniversary of the original voyag...,Titanic 2 (2010),"[{'cast_id': 1, 'character': 'Hayden Walsh', '...","[{'credit_id': '52fe46a3c3a36847f810a04b', 'de...","[{'id': 9937, 'name': 'suspense'}]",55.0,4.514870
45286,"[Comedy, Crime]",426272.0,Ray is a fledgling entrepreneur who specialize...,Take Me (2017),"[{'cast_id': 1, 'character': 'Anna St. Blair',...","[{'credit_id': '582c3222c3a36872c0006604', 'de...",[],38.0,6.150325
45293,"[Romance, Comedy]",432789.0,"Burned by a bad breakup, a struggling New York...",The Incredible Jessica James (2017),"[{'cast_id': 6, 'character': 'Jessica James', ...","[{'credit_id': '586a688dc3a3680f4e017d65', 'de...",[],37.0,6.256668
45354,[Comedy],14008.0,Hyperactive teenager Kelly is enrolled into a ...,Cadet Kelly (2002),"[{'cast_id': 1, 'character': 'Kelly Collins', ...","[{'credit_id': '52fe45c29251416c75061803', 'de...","[{'id': 171803, 'name': 'military school'}]",145.0,5.412421

In [78]:
movies.iloc[0].keywords

"[{'id': 931, 'name': 'jealousy'}, {'id': 4290, 'name': 'toy'}, {'id': 5202, 'name': 'boy'}, {'id': 6054, 'name': 'friendship'}, {'id': 9713, 'name': 'friends'}, {'id': 9823, 'name': 'rivalry'}, {'id': 165503, 'name': 'boy next door'}, {'id': 170722, 'name': 'new toy'}, {'id': 187065, 'name': 'toy comes to life'}]"

In [79]:
movies["keywords"] = movies["keywords"].apply(convert)

In [80]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[Animation, Comedy, Family]",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[jealousy, toy, boy, friendship, friends, riva...",5415.0,7.691379
1,"[Adventure, Fantasy, Family]",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[board game, disappearance, based on children'...",2413.0,6.891918
2,"[Romance, Comedy]",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[fishing, best friend, duringcreditsstinger, o...",92.0,6.450979
3,"[Comedy, Drama, Romance]",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[based on novel, interracial relationship, sin...",34.0,6.209168
4,[Comedy],11862.0,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995),"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[baby, midlife crisis, confidence, aging, daug...",173.0,5.801562
...,...,...,...,...,...,...,...,...,...
45256,[Comedy],248705.0,"Stuck in the corridors of time, Godefroy de Mo...",The Visitors: Bastille Day (2016),"[{'cast_id': 2, 'character': 'Le comte Godefro...","[{'credit_id': '52fe4f37c3a36847f82c5efb', 'de...","[nazis, castle, time travel, robespierre]",167.0,4.392156
45261,"[Action, Adventure, Thriller]",44918.0,On the 100th anniversary of the original voyag...,Titanic 2 (2010),"[{'cast_id': 1, 'character': 'Hayden Walsh', '...","[{'credit_id': '52fe46a3c3a36847f810a04b', 'de...",[suspense],55.0,4.514870
45286,"[Comedy, Crime]",426272.0,Ray is a fledgling entrepreneur who specialize...,Take Me (2017),"[{'cast_id': 1, 'character': 'Anna St. Blair',...","[{'credit_id': '582c3222c3a36872c0006604', 'de...",[],38.0,6.150325
45293,"[Romance, Comedy]",432789.0,"Burned by a bad breakup, a struggling New York...",The Incredible Jessica James (2017),"[{'cast_id': 6, 'character': 'Jessica James', ...","[{'credit_id': '586a688dc3a3680f4e017d65', 'de...",[],37.0,6.256668
45354,[Comedy],14008.0,Hyperactive teenager Kelly is enrolled into a ...,Cadet Kelly (2002),"[{'cast_id': 1, 'character': 'Kelly Collins', ...","[{'credit_id': '52fe45c29251416c75061803', 'de...",[military school],145.0,5.412421

In [81]:
movies.iloc[0].cast

"[{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}, {'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}, {'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}, {'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'}, {'cast_id': 19, 'character': 'Hamm (voice)', 'credit_id': '52fe4284c3a36847f8024fa9', 'gender': 2, 'id': 7907, 'name': 'John Ratzenberger', 'order': 5, 'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'}, {'cast_id': 20, 'character': 'Bo Peep (voice)', 'credit_id': '52fe4284c3a36847f8024fad', 'gender': 1, 'id': 8873, 'name': 'Annie Potts', 'order': 6, 'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'}, {'cast_id': 26, 'character': 'Andy (voice)', 'credit_id': '52fe4284c3a36847f8024fc1', 'gender': 0, 'id': 1116442, 'name': 'John Morris', 'order': 7, 'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'}, {'cast_id': 22, 'character': 'Sid (voice)', 'credit_id': '52fe4284c3a36847f8024fb1', 'gender': 2, 'id': 12901, 'name': 'Erik von Detten', 'order': 8, 'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'}, {'cast_id': 23, 'character': 'Mrs. Davis (voice)', 'credit_id': '52fe4284c3a36847f8024fb5', 'gender': 1, 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9, 'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'}, {'cast_id': 24, 'character': 'Sergeant (voice)', 'credit_id': '52fe4284c3a36847f8024fb9', 'gender': 2, 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10, 'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'}, {'cast_id': 25, 'character': 'Hannah (voice)', 'credit_id': '52fe4284c3a36847f8024fbd', 'gender': 1, 'id': 12903, 'name': 'Sarah Freeman', 'order': 11, 'profile_path': None}, {'cast_id': 27, 'character': 'TV Announcer (voice)', 'credit_id': '52fe4284c3a36847f8024fc5', 'gender': 2, 'id': 37221, 'name': 'Penn Jillette', 'order': 12, 'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}]"

In [82]:
def convert3(obj):
    cnt = 0
    L = []

    for i in ast.literal_eval(obj):
        if cnt!=3:
            L.append(i['name'])
            cnt+=1
        else:
            break

    return L

In [83]:
movies["cast"] = movies["cast"].apply(convert3)

In [84]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[Animation, Comedy, Family]",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[Tom Hanks, Tim Allen, Don Rickles]","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[jealousy, toy, boy, friendship, friends, riva...",5415.0,7.691379
1,"[Adventure, Fantasy, Family]",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[Robin Williams, Jonathan Hyde, Kirsten Dunst]","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[board game, disappearance, based on children'...",2413.0,6.891918
2,"[Romance, Comedy]",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[Walter Matthau, Jack Lemmon, Ann-Margret]","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[fishing, best friend, duringcreditsstinger, o...",92.0,6.450979
3,"[Comedy, Drama, Romance]",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[Whitney Houston, Angela Bassett, Loretta Devine]","[{'credit_id': '52fe44779251416c91011acb', 'de...","[based on novel, interracial relationship, sin...",34.0,6.209168
4,[Comedy],11862.0,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995),"[Steve Martin, Diane Keaton, Martin Short]","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[baby, midlife crisis, confidence, aging, daug...",173.0,5.801562
...,...,...,...,...,...,...,...,...,...
45256,[Comedy],248705.0,"Stuck in the corridors of time, Godefroy de Mo...",The Visitors: Bastille Day (2016),"[Jean Reno, Christian Clavier, Franck Dubosc]","[{'credit_id': '52fe4f37c3a36847f82c5efb', 'de...","[nazis, castle, time travel, robespierre]",167.0,4.392156
45261,"[Action, Adventure, Thriller]",44918.0,On the 100th anniversary of the original voyag...,Titanic 2 (2010),"[Shane Van Dyke, Marie Westbrook, Bruce Davison]","[{'credit_id': '52fe46a3c3a36847f810a04b', 'de...",[suspense],55.0,4.514870
45286,"[Comedy, Crime]",426272.0,Ray is a fledgling entrepreneur who specialize...,Take Me (2017),"[Taylor Schilling, Pat Healy, Alycia Delmore]","[{'credit_id': '582c3222c3a36872c0006604', 'de...",[],38.0,6.150325
45293,"[Romance, Comedy]",432789.0,"Burned by a bad breakup, a struggling New York...",The Incredible Jessica James (2017),"[Jessica Williams, Chris O'Dowd, Keith Stanfield]","[{'credit_id': '586a688dc3a3680f4e017d65', 'de...",[],37.0,6.256668
45354,[Comedy],14008.0,Hyperactive teenager Kelly is enrolled into a ...,Cadet Kelly (2002),"[Hilary Duff, Christy Carlson Romano, Gary Cole]","[{'credit_id': '52fe45c29251416c75061803', 'de...",[military school],145.0,5.412421

In [85]:
movies.iloc[2].crew

"[{'credit_id': '52fe466a9251416c75077a89', 'department': 'Directing', 'gender': 2, 'id': 26502, 'job': 'Director', 'name': 'Howard Deutch', 'profile_path': '/68Vae1HkU1NxQZ6KEmuxIpno7c9.jpg'}, {'credit_id': '52fe466b9251416c75077aa3', 'department': 'Writing', 'gender': 2, 'id': 16837, 'job': 'Characters', 'name': 'Mark Steven Johnson', 'profile_path': '/6trChNn3o2bi4i2ipgMEAytwmZp.jpg'}, {'credit_id': '52fe466b9251416c75077aa9', 'department': 'Writing', 'gender': 2, 'id': 16837, 'job': 'Writer', 'name': 'Mark Steven Johnson', 'profile_path': '/6trChNn3o2bi4i2ipgMEAytwmZp.jpg'}, {'credit_id': '5675eb4b92514179dd003933', 'department': 'Crew', 'gender': 2, 'id': 1551320, 'job': 'Sound Recordist', 'name': 'Jack Keller', 'profile_path': None}]"

In [86]:
def fetch_director(obj):
    L = []

    for i in ast.literal_eval(obj):
        if(i["job"]=="Director"):
            L.append(i["name"])

    return L

In [87]:
movies["crew"] = movies["crew"].apply(fetch_director)

In [88]:
movies.head(4)

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[Animation, Comedy, Family]",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter],"[jealousy, toy, boy, friendship, friends, riva...",5415.0,7.691379
1,"[Adventure, Fantasy, Family]",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston],"[board game, disappearance, based on children'...",2413.0,6.891918
2,"[Romance, Comedy]",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[Walter Matthau, Jack Lemmon, Ann-Margret]",[Howard Deutch],"[fishing, best friend, duringcreditsstinger, o...",92.0,6.450979
3,"[Comedy, Drama, Romance]",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[Whitney Houston, Angela Bassett, Loretta Devine]",[Forest Whitaker],"[based on novel, interracial relationship, sin...",34.0,6.209168

In [89]:
movies.iloc[0].overview

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences."

In [90]:
movies["overview"] = movies["overview"].apply(lambda x:x.split())

In [91]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[Animation, Comedy, Family]",862.0,"[Led, by, Woody,, Andy's, toys, live, happily,...",Toy Story (1995),"[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter],"[jealousy, toy, boy, friendship, friends, riva...",5415.0,7.691379
1,"[Adventure, Fantasy, Family]",8844.0,"[When, siblings, Judy, and, Peter, discover, a...",Jumanji (1995),"[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston],"[board game, disappearance, based on children'...",2413.0,6.891918
2,"[Romance, Comedy]",15602.0,"[A, family, wedding, reignites, the, ancient, ...",Grumpier Old Men (1995),"[Walter Matthau, Jack Lemmon, Ann-Margret]",[Howard Deutch],"[fishing, best friend, duringcreditsstinger, o...",92.0,6.450979
3,"[Comedy, Drama, Romance]",31357.0,"[Cheated, on,, mistreated, and, stepped, on,, ...",Waiting to Exhale (1995),"[Whitney Houston, Angela Bassett, Loretta Devine]",[Forest Whitaker],"[based on novel, interracial relationship, sin...",34.0,6.209168
4,[Comedy],11862.0,"[Just, when, George, Banks, has, recovered, fr...",Father of the Bride Part II (1995),"[Steve Martin, Diane Keaton, Martin Short]",[Charles Shyer],"[baby, midlife crisis, confidence, aging, daug...",173.0,5.801562
...,...,...,...,...,...,...,...,...,...
45256,[Comedy],248705.0,"[Stuck, in, the, corridors, of, time,, Godefro...",The Visitors: Bastille Day (2016),"[Jean Reno, Christian Clavier, Franck Dubosc]",[Jean-Marie Poiré],"[nazis, castle, time travel, robespierre]",167.0,4.392156
45261,"[Action, Adventure, Thriller]",44918.0,"[On, the, 100th, anniversary, of, the, origina...",Titanic 2 (2010),"[Shane Van Dyke, Marie Westbrook, Bruce Davison]",[Shane Van Dyke],[suspense],55.0,4.514870
45286,"[Comedy, Crime]",426272.0,"[Ray, is, a, fledgling, entrepreneur, who, spe...",Take Me (2017),"[Taylor Schilling, Pat Healy, Alycia Delmore]",[Pat Healy],[],38.0,6.150325
45293,"[Romance, Comedy]",432789.0,"[Burned, by, a, bad, breakup,, a, struggling, ...",The Incredible Jessica James (2017),"[Jessica Williams, Chris O'Dowd, Keith Stanfield]",[Jim Strouse],[],37.0,6.256668
45354,[Comedy],14008.0,"[Hyperactive, teenager, Kelly, is, enrolled, i...",Cadet Kelly (2002),"[Hilary Duff, Christy Carlson Romano, Gary Cole]",[Larry Shaw],[military school],145.0,5.412421

In [92]:
movies["genres"] = movies["genres"].apply(lambda x:[i.replace(" ", "") for i in x])
movies["cast"] = movies["cast"].apply(lambda x:[i.replace(" ", "") for i in x])
movies["crew"] = movies["crew"].apply(lambda x:[i.replace(" ", "") for i in x])
movies["keywords"] = movies["keywords"].apply(lambda x:[i.replace(" ", "") for i in x])

In [93]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[Animation, Comedy, Family]",862.0,"[Led, by, Woody,, Andy's, toys, live, happily,...",Toy Story (1995),"[TomHanks, TimAllen, DonRickles]",[JohnLasseter],"[jealousy, toy, boy, friendship, friends, riva...",5415.0,7.691379
1,"[Adventure, Fantasy, Family]",8844.0,"[When, siblings, Judy, and, Peter, discover, a...",Jumanji (1995),"[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston],"[boardgame, disappearance, basedonchildren'sbo...",2413.0,6.891918
2,"[Romance, Comedy]",15602.0,"[A, family, wedding, reignites, the, ancient, ...",Grumpier Old Men (1995),"[WalterMatthau, JackLemmon, Ann-Margret]",[HowardDeutch],"[fishing, bestfriend, duringcreditsstinger, ol...",92.0,6.450979
3,"[Comedy, Drama, Romance]",31357.0,"[Cheated, on,, mistreated, and, stepped, on,, ...",Waiting to Exhale (1995),"[WhitneyHouston, AngelaBassett, LorettaDevine]",[ForestWhitaker],"[basedonnovel, interracialrelationship, single...",34.0,6.209168
4,[Comedy],11862.0,"[Just, when, George, Banks, has, recovered, fr...",Father of the Bride Part II (1995),"[SteveMartin, DianeKeaton, MartinShort]",[CharlesShyer],"[baby, midlifecrisis, confidence, aging, daugh...",173.0,5.801562
...,...,...,...,...,...,...,...,...,...
45256,[Comedy],248705.0,"[Stuck, in, the, corridors, of, time,, Godefro...",The Visitors: Bastille Day (2016),"[JeanReno, ChristianClavier, FranckDubosc]",[Jean-MariePoiré],"[nazis, castle, timetravel, robespierre]",167.0,4.392156
45261,"[Action, Adventure, Thriller]",44918.0,"[On, the, 100th, anniversary, of, the, origina...",Titanic 2 (2010),"[ShaneVanDyke, MarieWestbrook, BruceDavison]",[ShaneVanDyke],[suspense],55.0,4.514870
45286,"[Comedy, Crime]",426272.0,"[Ray, is, a, fledgling, entrepreneur, who, spe...",Take Me (2017),"[TaylorSchilling, PatHealy, AlyciaDelmore]",[PatHealy],[],38.0,6.150325
45293,"[Romance, Comedy]",432789.0,"[Burned, by, a, bad, breakup,, a, struggling, ...",The Incredible Jessica James (2017),"[JessicaWilliams, ChrisO'Dowd, KeithStanfield]",[JimStrouse],[],37.0,6.256668
45354,[Comedy],14008.0,"[Hyperactive, teenager, Kelly, is, enrolled, i...",Cadet Kelly (2002),"[HilaryDuff, ChristyCarlsonRomano, GaryCole]",[LarryShaw],[militaryschool],145.0,5.412421

In [94]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
STOP_WORDS = set(stopwords.words('english'))

def clean_overview(word_list, max_words=50):
    meaningful_words = [w for w in word_list if w.lower() not in STOP_WORDS]
    return meaningful_words[:max_words]

# Apply the stop-word filter
movies["overview"] = movies["overview"].apply(lambda x: clean_overview(x, 50))

[nltk_data] Downloading package stopwords to C:\Users\Varun
[nltk_data]     Bahuguna\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [95]:
movies["tag"] = (
    movies["crew"] * 3 +
    movies["genres"] * 4 +
    movies["keywords"] * 4 +
    movies["cast"] * 2 +
    movies["overview"]
)

In [96]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg,tag
0,"[Animation, Comedy, Family]",862.0,"[Led, Woody,, Andy's, toys, live, happily, roo...",Toy Story (1995),"[TomHanks, TimAllen, DonRickles]",[JohnLasseter],"[jealousy, toy, boy, friendship, friends, riva...",5415.0,7.691379,"[JohnLasseter, JohnLasseter, JohnLasseter, Ani..."
1,"[Adventure, Fantasy, Family]",8844.0,"[siblings, Judy, Peter, discover, enchanted, b...",Jumanji (1995),"[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston],"[boardgame, disappearance, basedonchildren'sbo...",2413.0,6.891918,"[JoeJohnston, JoeJohnston, JoeJohnston, Advent..."
2,"[Romance, Comedy]",15602.0,"[family, wedding, reignites, ancient, feud, ne...",Grumpier Old Men (1995),"[WalterMatthau, JackLemmon, Ann-Margret]",[HowardDeutch],"[fishing, bestfriend, duringcreditsstinger, ol...",92.0,6.450979,"[HowardDeutch, HowardDeutch, HowardDeutch, Rom..."
3,"[Comedy, Drama, Romance]",31357.0,"[Cheated, on,, mistreated, stepped, on,, women...",Waiting to Exhale (1995),"[WhitneyHouston, AngelaBassett, LorettaDevine]",[ForestWhitaker],"[basedonnovel, interracialrelationship, single...",34.0,6.209168,"[ForestWhitaker, ForestWhitaker, ForestWhitake..."
4,[Comedy],11862.0,"[George, Banks, recovered, daughter's, wedding...",Father of the Bride Part II (1995),"[SteveMartin, DianeKeaton, MartinShort]",[CharlesShyer],"[baby, midlifecrisis, confidence, aging, daugh...",173.0,5.801562,"[CharlesShyer, CharlesShyer, CharlesShyer, Com..."
...,...,...,...,...,...,...,...,...,...,...
45256,[Comedy],248705.0,"[Stuck, corridors, time,, Godefroy, de, Montmi...",The Visitors: Bastille Day (2016),"[JeanReno, ChristianClavier, FranckDubosc]",[Jean-MariePoiré],"[nazis, castle, timetravel, robespierre]",167.0,4.392156,"[Jean-MariePoiré, Jean-MariePoiré, Jean-MarieP..."
45261,"[Action, Adventure, Thriller]",44918.0,"[100th, anniversary, original, voyage,, modern...",Titanic 2 (2010),"[ShaneVanDyke, MarieWestbrook, BruceDavison]",[ShaneVanDyke],[suspense],55.0,4.514870,"[ShaneVanDyke, ShaneVanDyke, ShaneVanDyke, Act..."
45286,"[Comedy, Crime]",426272.0,"[Ray, fledgling, entrepreneur, specializes, hi...",Take Me (2017),"[TaylorSchilling, PatHealy, AlyciaDelmore]",[PatHealy],[],38.0,6.150325,"[PatHealy, PatHealy, PatHealy, Comedy, Crime, ..."
45293,"[Romance, Comedy]",432789.0,"[Burned, bad, breakup,, struggling, New, York,...",The Incredible Jessica James (2017),"[JessicaWilliams, ChrisO'Dowd, KeithStanfield]",[JimStrouse],[],37.0,6.256668,"[JimStrouse, JimStrouse, JimStrouse, Romance, ..."
45354,[Comedy],14008.0,"[Hyperactive, teenager, Kelly, enrolled, milit...",Cadet Kelly (2002),"[HilaryDuff, ChristyCarlsonRomano, GaryCole]",[LarryShaw],[militaryschool],145.0,5.412421,"[LarryShaw, LarryShaw, LarryShaw, Comedy, Come..."

In [97]:
movies = movies[["id", "title", "tag", "vote_count", "new_vote_avg", "crew"]]

In [98]:
movies

,id,title,tag,vote_count,new_vote_avg,crew
0,862.0,Toy Story (1995),"[JohnLasseter, JohnLasseter, JohnLasseter, Ani...",5415.0,7.691379,[JohnLasseter]
1,8844.0,Jumanji (1995),"[JoeJohnston, JoeJohnston, JoeJohnston, Advent...",2413.0,6.891918,[JoeJohnston]
2,15602.0,Grumpier Old Men (1995),"[HowardDeutch, HowardDeutch, HowardDeutch, Rom...",92.0,6.450979,[HowardDeutch]
3,31357.0,Waiting to Exhale (1995),"[ForestWhitaker, ForestWhitaker, ForestWhitake...",34.0,6.209168,[ForestWhitaker]
4,11862.0,Father of the Bride Part II (1995),"[CharlesShyer, CharlesShyer, CharlesShyer, Com...",173.0,5.801562,[CharlesShyer]
...,...,...,...,...,...,...
45256,248705.0,The Visitors: Bastille Day (2016),"[Jean-MariePoiré, Jean-MariePoiré, Jean-MarieP...",167.0,4.392156,[Jean-MariePoiré]
45261,44918.0,Titanic 2 (2010),"[ShaneVanDyke, ShaneVanDyke, ShaneVanDyke, Act...",55.0,4.514870,[ShaneVanDyke]
45286,426272.0,Take Me (2017),"[PatHealy, PatHealy, PatHealy, Comedy, Crime, ...",38.0,6.150325,[PatHealy]
45293,432789.0,The Incredible Jessica James (2017),"[JimStrouse, JimStrouse, JimStrouse, Romance, ...",37.0,6.256668,[JimStrouse]
45354,14008.0,Cadet Kelly (2002),"[LarryShaw, LarryShaw, LarryShaw, Comedy, Come...",145.0,5.412421,[LarryShaw]

In [99]:
movies["tag"] = movies["tag"].apply(lambda x : " ".join(x))

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_16464\2733104798.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["tag"] = movies["tag"].apply(lambda x : " ".join(x))

In [100]:
movies

,id,title,tag,vote_count,new_vote_avg,crew
0,862.0,Toy Story (1995),JohnLasseter JohnLasseter JohnLasseter Animati...,5415.0,7.691379,[JohnLasseter]
1,8844.0,Jumanji (1995),JoeJohnston JoeJohnston JoeJohnston Adventure ...,2413.0,6.891918,[JoeJohnston]
2,15602.0,Grumpier Old Men (1995),HowardDeutch HowardDeutch HowardDeutch Romance...,92.0,6.450979,[HowardDeutch]
3,31357.0,Waiting to Exhale (1995),ForestWhitaker ForestWhitaker ForestWhitaker C...,34.0,6.209168,[ForestWhitaker]
4,11862.0,Father of the Bride Part II (1995),CharlesShyer CharlesShyer CharlesShyer Comedy ...,173.0,5.801562,[CharlesShyer]
...,...,...,...,...,...,...
45256,248705.0,The Visitors: Bastille Day (2016),Jean-MariePoiré Jean-MariePoiré Jean-MariePoir...,167.0,4.392156,[Jean-MariePoiré]
45261,44918.0,Titanic 2 (2010),ShaneVanDyke ShaneVanDyke ShaneVanDyke Action ...,55.0,4.514870,[ShaneVanDyke]
45286,426272.0,Take Me (2017),PatHealy PatHealy PatHealy Comedy Crime Comedy...,38.0,6.150325,[PatHealy]
45293,432789.0,The Incredible Jessica James (2017),JimStrouse JimStrouse JimStrouse Romance Comed...,37.0,6.256668,[JimStrouse]
45354,14008.0,Cadet Kelly (2002),LarryShaw LarryShaw LarryShaw Comedy Comedy Co...,145.0,5.412421,[LarryShaw]

In [101]:
movies["tag"] = movies["tag"].str.lower()

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_16464\121673973.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["tag"] = movies["tag"].str.lower()

In [102]:
movies

,id,title,tag,vote_count,new_vote_avg,crew
0,862.0,Toy Story (1995),johnlasseter johnlasseter johnlasseter animati...,5415.0,7.691379,[JohnLasseter]
1,8844.0,Jumanji (1995),joejohnston joejohnston joejohnston adventure ...,2413.0,6.891918,[JoeJohnston]
2,15602.0,Grumpier Old Men (1995),howarddeutch howarddeutch howarddeutch romance...,92.0,6.450979,[HowardDeutch]
3,31357.0,Waiting to Exhale (1995),forestwhitaker forestwhitaker forestwhitaker c...,34.0,6.209168,[ForestWhitaker]
4,11862.0,Father of the Bride Part II (1995),charlesshyer charlesshyer charlesshyer comedy ...,173.0,5.801562,[CharlesShyer]
...,...,...,...,...,...,...
45256,248705.0,The Visitors: Bastille Day (2016),jean-mariepoiré jean-mariepoiré jean-mariepoir...,167.0,4.392156,[Jean-MariePoiré]
45261,44918.0,Titanic 2 (2010),shanevandyke shanevandyke shanevandyke action ...,55.0,4.514870,[ShaneVanDyke]
45286,426272.0,Take Me (2017),pathealy pathealy pathealy comedy crime comedy...,38.0,6.150325,[PatHealy]
45293,432789.0,The Incredible Jessica James (2017),jimstrouse jimstrouse jimstrouse romance comed...,37.0,6.256668,[JimStrouse]
45354,14008.0,Cadet Kelly (2002),larryshaw larryshaw larryshaw comedy comedy co...,145.0,5.412421,[LarryShaw]

In [103]:
movies["crew"] = movies["crew"].apply(lambda x : " ".join(x))

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_16464\692877924.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["crew"] = movies["crew"].apply(lambda x : " ".join(x))

In [104]:
movies["crew"] = movies["crew"].str.lower()

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_16464\235839181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["crew"] = movies["crew"].str.lower()

In [105]:
movies

,id,title,tag,vote_count,new_vote_avg,crew
0,862.0,Toy Story (1995),johnlasseter johnlasseter johnlasseter animati...,5415.0,7.691379,johnlasseter
1,8844.0,Jumanji (1995),joejohnston joejohnston joejohnston adventure ...,2413.0,6.891918,joejohnston
2,15602.0,Grumpier Old Men (1995),howarddeutch howarddeutch howarddeutch romance...,92.0,6.450979,howarddeutch
3,31357.0,Waiting to Exhale (1995),forestwhitaker forestwhitaker forestwhitaker c...,34.0,6.209168,forestwhitaker
4,11862.0,Father of the Bride Part II (1995),charlesshyer charlesshyer charlesshyer comedy ...,173.0,5.801562,charlesshyer
...,...,...,...,...,...,...
45256,248705.0,The Visitors: Bastille Day (2016),jean-mariepoiré jean-mariepoiré jean-mariepoir...,167.0,4.392156,jean-mariepoiré
45261,44918.0,Titanic 2 (2010),shanevandyke shanevandyke shanevandyke action ...,55.0,4.514870,shanevandyke
45286,426272.0,Take Me (2017),pathealy pathealy pathealy comedy crime comedy...,38.0,6.150325,pathealy
45293,432789.0,The Incredible Jessica James (2017),jimstrouse jimstrouse jimstrouse romance comed...,37.0,6.256668,jimstrouse
45354,14008.0,Cadet Kelly (2002),larryshaw larryshaw larryshaw comedy comedy co...,145.0,5.412421,larryshaw

In [106]:
movies = movies.reset_index(drop=True)

In [107]:
movies

,id,title,tag,vote_count,new_vote_avg,crew
0,862.0,Toy Story (1995),johnlasseter johnlasseter johnlasseter animati...,5415.0,7.691379,johnlasseter
1,8844.0,Jumanji (1995),joejohnston joejohnston joejohnston adventure ...,2413.0,6.891918,joejohnston
2,15602.0,Grumpier Old Men (1995),howarddeutch howarddeutch howarddeutch romance...,92.0,6.450979,howarddeutch
3,31357.0,Waiting to Exhale (1995),forestwhitaker forestwhitaker forestwhitaker c...,34.0,6.209168,forestwhitaker
4,11862.0,Father of the Bride Part II (1995),charlesshyer charlesshyer charlesshyer comedy ...,173.0,5.801562,charlesshyer
...,...,...,...,...,...,...
11190,248705.0,The Visitors: Bastille Day (2016),jean-mariepoiré jean-mariepoiré jean-mariepoir...,167.0,4.392156,jean-mariepoiré
11191,44918.0,Titanic 2 (2010),shanevandyke shanevandyke shanevandyke action ...,55.0,4.514870,shanevandyke
11192,426272.0,Take Me (2017),pathealy pathealy pathealy comedy crime comedy...,38.0,6.150325,pathealy
11193,432789.0,The Incredible Jessica James (2017),jimstrouse jimstrouse jimstrouse romance comed...,37.0,6.256668,jimstrouse
11194,14008.0,Cadet Kelly (2002),larryshaw larryshaw larryshaw comedy comedy co...,145.0,5.412421,larryshaw

In [108]:
movies.rename(columns={"new_vote_avg": "rating"}, inplace=True)

In [109]:
movies

,id,title,tag,vote_count,rating,crew
0,862.0,Toy Story (1995),johnlasseter johnlasseter johnlasseter animati...,5415.0,7.691379,johnlasseter
1,8844.0,Jumanji (1995),joejohnston joejohnston joejohnston adventure ...,2413.0,6.891918,joejohnston
2,15602.0,Grumpier Old Men (1995),howarddeutch howarddeutch howarddeutch romance...,92.0,6.450979,howarddeutch
3,31357.0,Waiting to Exhale (1995),forestwhitaker forestwhitaker forestwhitaker c...,34.0,6.209168,forestwhitaker
4,11862.0,Father of the Bride Part II (1995),charlesshyer charlesshyer charlesshyer comedy ...,173.0,5.801562,charlesshyer
...,...,...,...,...,...,...
11190,248705.0,The Visitors: Bastille Day (2016),jean-mariepoiré jean-mariepoiré jean-mariepoir...,167.0,4.392156,jean-mariepoiré
11191,44918.0,Titanic 2 (2010),shanevandyke shanevandyke shanevandyke action ...,55.0,4.514870,shanevandyke
11192,426272.0,Take Me (2017),pathealy pathealy pathealy comedy crime comedy...,38.0,6.150325,pathealy
11193,432789.0,The Incredible Jessica James (2017),jimstrouse jimstrouse jimstrouse romance comed...,37.0,6.256668,jimstrouse
11194,14008.0,Cadet Kelly (2002),larryshaw larryshaw larryshaw comedy comedy co...,145.0,5.412421,larryshaw

In [110]:
import nltk
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [111]:
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to C:\Users\Varun
[nltk_data]     Bahuguna\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\Varun
[nltk_data]     Bahuguna\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [112]:
from nltk.corpus import wordnet
from nltk import pos_tag

def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [113]:
def lemmatize_text(text):
    words = text.split()
    tagged_words = pos_tag(words)

    lemmatized = []

    for word, tag in tagged_words:
        lemmatized.append(lemmatizer.lemmatize(word, get_wordnet_pos(tag)))
    
    return " ".join(lemmatized)

In [114]:
movies["tag"] = movies["tag"].apply(lemmatize_text)

In [115]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [116]:
tfidf = TfidfVectorizer(max_features=5000, stop_words="english", ngram_range=(1, 3))

In [117]:
vectors = tfidf.fit_transform(movies["tag"])

In [118]:
vectors.shape

(11195, 5000)

In [119]:
tfidf.get_feature_names_out()[:1000]

array(['000', '10', '10 year', '11', '12', '12 year', '12 year old', '13',
       '15', '15 year', '16', '17', '17thcentury', '18', '18thcentury',
       '1920s', '1930s', '1940s', '1950s', '1960s', '1970s', '1980s',
       '1990s', '19th', '19th century', '19thcentury', '20', '20 year',
       '30', '3d', '40', 'aaroneckhart', 'abandon', 'abduct', 'ability',
       'able', 'aboard', 'abortion', 'abuse', 'abusive', 'academy',
       'accept', 'accident', 'accidentally', 'accompany', 'account',
       'accountant', 'accuse', 'achieve', 'act', 'action',
       'action action', 'action action action', 'action adventure',
       'action adventure action', 'action adventure animation',
       'action adventure comedy', 'action adventure crime',
       'action adventure drama', 'action adventure family',
       'action adventure fantasy', 'action adventure horror',
       'action adventure sciencefiction', 'action adventure thriller',
       'action animation', 'action animation action',
       'action animation adventure', 'action animation sciencefiction',
       'action comedy', 'action comedy action', 'action comedy adventure',
       'action comedy crime', 'action comedy drama',
       'action comedy family', 'action comedy horror',
       'action comedy romance', 'action comedy sciencefiction',
       'action comedy thriller', 'action comedy western', 'action crime',
       'action crime action', 'action crime comedy', 'action crime drama',
       'action crime mystery', 'action crime thriller', 'action drama',
       'action drama action', 'action drama crime',
       'action drama fantasy', 'action drama history',
       'action drama horror', 'action drama mystery',
       'action drama romance', 'action drama sciencefiction',
       'action drama thriller', 'action drama war',
       'action drama western', 'action family', 'action fantasy',
       'action fantasy action', 'action fantasy adventure',
       'action fantasy horror', 'action fantasy sciencefiction',
       'action history', 'action history war', 'action horror',
       'action horror action', 'action horror sciencefiction',
       'action horror thriller', 'action mystery',
       'action mystery thriller', 'action romance',
       'action sciencefiction', 'action sciencefiction action',
       'action sciencefiction adventure', 'action sciencefiction horror',
       'action sciencefiction thriller', 'action thriller',
       'action thriller action', 'action thriller adventure',
       'action thriller crime', 'action thriller drama',
       'action thriller horror', 'action thriller mystery',
       'action thriller sciencefiction', 'action thriller war',
       'action war', 'action western', 'actionhero', 'activist',
       'activity', 'actor', 'actress', 'actually', 'adam', 'adamsandler',
       'adapt', 'adaptation', 'addict', 'addiction', 'adolescence',
       'adolfhitler', 'adopt', 'adoption', 'adrienbrody', 'adult',
       'adultanimation', 'adultery', 'adultery basedonnovel', 'adventure',
       'adventure action', 'adventure action adventure',
       'adventure action comedy', 'adventure action drama',
       'adventure action fantasy', 'adventure action sciencefiction',
       'adventure action thriller', 'adventure adventure',
       'adventure adventure adventure', 'adventure animation',
       'adventure animation action', 'adventure animation comedy',
       'adventure animation drama', 'adventure animation family',
       'adventure animation fantasy', 'adventure comedy',
       'adventure comedy action', 'adventure comedy adventure',
       'adventure comedy crime', 'adventure comedy drama',
       'adventure comedy family', 'adventure comedy fantasy',
       'adventure comedy romance', 'adventure comedy sciencefiction',
       'adventure comedy thriller', 'adventure crime',
       'adventure crime action', 'adventure crime drama',
       'adventure crime thriller', 'adventure drama',
       'adventure drama action', 'adventure drama adventure',
       'adventure drama family', 'adventure drama fantasy',
       'adventure drama history', 'adventure drama romance',
       'adventure drama sciencefiction', 'adventure drama thriller',
       'adventure drama western', 'adventure family',
       'adventure family adventure', 'adventure family animation',
       'adventure family comedy', 'adventure family fantasy',
       'adventure fantasy', 'adventure fantasy action',
       'adventure fantasy animation', 'adventure fantasy comedy',
       'adventure fantasy drama', 'adventure fantasy family',
       'adventure fantasy sciencefiction', 'adventure history',
       'adventure horror', 'adventure horror sciencefiction',
       'adventure mystery', 'adventure romance',
       'adventure sciencefiction', 'adventure sciencefiction action',
       'adventure sciencefiction thriller', 'adventure thriller',
       'adventure thriller action', 'adventure thriller sciencefiction',
       'adventure war', 'adventure western', 'adventurer', 'adversary',
       'advertising', 'advice', 'affair', 'affection', 'afghanistan',
       'africa', 'african', 'africanamerican', 'aftercreditsstinger',
       'aftercreditsstinger duringcreditsstinger', 'afterlife',
       'aftermath', 'age', 'aged', 'agedifference', 'agency', 'agent',
       'aggressionbyanimal', 'ago', 'agree', 'aid', 'air', 'airforce',
       'airplane', 'airplanecrash', 'airport', 'akirakurosawa', 'al',
       'alanparker', 'alanrickman', 'alaska', 'albert', 'alcatraz',
       'alcohol', 'alcohol sex', 'alcoholabuse', 'alcoholic',
       'alcoholism', 'alecbaldwin', 'alex', 'alfredhitchcock',
       'alfredhitchcock alfredhitchcock',
       'alfredhitchcock alfredhitchcock alfredhitchcock', 'alice',
       'alien', 'alien independentfilm', 'alieninfection',
       'alieninvasion', 'alienlife', 'alienlife form', 'alienplanet',
       'alike', 'alive', 'allegory', 'alliance', 'allow', 'ally',
       'alpacino', 'alter', 'alternatedimension', 'alternatereality',
       'alzheimer', 'amazon', 'ambassador', 'ambition', 'ambitious',
       'ambulance', 'ambush', 'america', 'american', 'americanabroad',
       'americancivilwar', 'americandream', 'americanfootball',
       'americanfootballplayer', 'amnesia', 'amp', 'amusementpark', 'amy',
       'amyadams', 'anarchiccomedy', 'ancient', 'ancientgreece',
       'ancientrome', 'ancientworld', 'anderson', 'android', 'andy',
       'andygarcía', 'angel', 'angeles', 'angelinajolie', 'anger',
       'anglee', 'angry', 'animal', 'animalattack', 'animalhorror',
       'animate', 'animation', 'animation action',
       'animation action adventure', 'animation action animation',
       'animation action sciencefiction', 'animation adventure',
       'animation adventure comedy', 'animation adventure family',
       'animation animation', 'animation animation animation',
       'animation comedy', 'animation comedy adventure',
       'animation comedy animation', 'animation comedy drama',
       'animation comedy family', 'animation drama',
       'animation drama family', 'animation family',
       'animation family adventure', 'animation family animation',
       'animation family comedy', 'animation family fantasy',
       'animation fantasy', 'animation horror', 'animation romance',
       'animation sciencefiction', 'animation sciencefiction action',
       'animation sciencefiction family', 'anime', 'ann', 'anna',
       'annafaris', 'annakendrick', 'anne', 'annehathaway',
       'annettebening', 'annie', 'answer', 'ant', 'anthology',
       'anthonyhopkins', 'anthropomorphism', 'anti', 'anti christ',
       'antihero', 'antisemitism', 'antoinefuqua', 'antoniobanderas',
       'apache', 'apart', 'apartheid', 'apartment', 'ape', 'apocalypse',
       'apocalyptic', 'apocalyptic dystopia', 'appear', 'appearance',
       'apple', 'apprentice', 'approach', 'aquarium', 'arab', 'arabian',
       'arbitrarylaw', 'archaeologist', 'archeology', 'architect',
       'arctic', 'area', 'arena', 'argentina', 'argument', 'aristocrat',
       'arizona', 'arkansas', 'arm', 'armsdealer', 'army',
       'arnoldschwarzenegger', 'arrangedmarriage', 'arrest', 'arrival',
       'arrive', 'arrives', 'arson', 'art', 'artgallery', 'arthur',
       'artifact', 'artificialintelligence',
       'artificialintelligence manvsmachine', 'artist', 'ash',
       'ashtonkutcher', 'asia', 'ask', 'aspire', 'assassin',
       'assassination', 'assault', 'assign', 'assignment', 'assistant',
       'assume', 'asteroid', 'astronaut', 'asylum', 'atheist', 'athlete',
       'atomicbomb', 'attack', 'attempt', 'attemptedmurder',
       'attempttoescape', 'attend', 'attention', 'attic', 'attorney',
       'attract', 'attraction', 'attractive', 'audience', 'audition',
       'audreyhepburn', 'audreytautou', 'aunt', 'australia', 'australian',
       'australianoutback', 'austria', 'author', 'authority', 'autism',
       'auto', 'autobiography', 'automobileracing', 'autopsy', 'avenge',
       'aviation', 'avoid', 'awaken', 'award', 'away', 'awry', 'ax',
       'axe', 'axemurder', 'baby', 'baby snatching', 'babysitter',
       'bachelor', 'backpacker', 'bad', 'badluck', 'badmother',
       'badmother law', 'bag', 'bahamas', 'balance', 'ball', 'ballet',
       'baltimore', 'band', 'bandit', 'bangkok', 'bank', 'banker',
       'bankrobber', 'bankrobbery', 'bar', 'barbie', 'barcelonaspain',
       'barn', 'barrylevinson', 'barrylevinson barrylevinson',
       'barrysonnenfeld', 'bartender', 'base', 'base true',
       'base true story', 'baseball', 'baseball sport', 'basedoncartoon',
       'basedonchildren', 'basedonchildren sbook', 'basedoncomic',
       'basedoncomic superhuman', 'basedonfairytale',
       'basedongraphicnovel', 'basedonmanga', 'basedonnovel',
       'basedonplayormusical', 'basedonshortfilm', 'basedonshortstory',
       'basedontoy', 'basedontrueevents', 'basedontruestory',
       'basedontvseries', 'basedonvideogame', 'basedonyoungadultnovel',
       'basement', 'basketball', 'bat', 'bath', 'bathtub', 'batman',
       'battle', 'battlefield', 'battleforpower', 'bdsm', 'beach',
       'beachhouse', 'bear', 'beast', 'beat', 'beautiful',
       'beautifulwoman', 'beauty', 'becominganadult', 'bed', 'bedroom',
       'beer', 'befriend', 'begin', 'behavior', 'belgium', 'believe',
       'bell', 'beloved', 'ben', 'benaffleck', 'benkingsley',
       'benstiller', 'bent', 'berlin', 'best', 'best friend',
       'bestfriend', 'bestfriendsinlove', 'bet', 'betrayal', 'bible',
       'bicycle', 'big', 'big city', 'biker', 'bikini', 'billionaire',
       'billmurray', 'billnighy', 'billpaxton', 'billpullman', 'billy',
       'billybobthornton', 'billycrystal', 'billywilder',
       'billywilder billywilder', 'biography',
       'biography basedontruestory', 'biography biography',
       'biography historicalfigure', 'biography sport',
       'biologicalweapon', 'bird', 'birth', 'birthday', 'birthdayparty',
       'bisexuality', 'bishop', 'bite', 'bitter', 'bizarre', 'black',
       'blackandwhite', 'blackhumor', 'blackmagic', 'blackmail',
       'blackout', 'blackpeople', 'blade', 'blakeedwards',
       'blakeedwards blakeedwards', 'blame', 'blast', 'blaxploitation',
       'blind', 'blinddate', 'blindness', 'blindnessandimpairedvision',
       'blizzard', 'block', 'blonde', 'blood', 'blood slasher',
       'blood violence', 'bloodsplatter', 'bloody', 'blow', 'blue',
       'bmovie', 'board', 'boardingschool', 'boat', 'bob', 'bobby',
       'bobbyfarrelly', 'bobbyfarrelly peterfarrelly', 'body',
       'body swap', 'bodyguard', 'bodyhorror', 'bollywood', 'bomb',
       'bomber', 'bond', 'bondage', 'bone', 'book', 'border', 'bore',
       'boredom', 'born', 'bos', 'boss', 'boston', 'bound', 'bounty',
       'bountyhunter', 'box', 'boxer', 'boxingmatch', 'boy', 'boyfriend',
       'boys', 'bradleycooper', 'bradpitt', 'brain', 'brainwash', 'brave',
       'bravery', 'brawl', 'brazil', 'brazilian', 'brazilian comedy',
       'break', 'breakingthefourthwall', 'brendanfraser', 'brettratner',
       'brian', 'briandepalma', 'briandepalma briandepalma', 'bride',
       'bridge', 'brien', 'brilliant', 'bring', 'brings', 'britain',
       'british', 'britisharmy', 'britishsecretservice', 'broadway',
       'broker', 'brooklynnewyorkcity', 'broom', 'brothel', 'brother',
       'brother law', 'brotherbrotherrelationship', 'brothers',
       'brothersisterrelationship', 'brown', 'bruce', 'brucewillis',
       'brutal', 'brutality', 'brutality violence', 'brutally', 'bud',
       'buddy', 'buddycomedy', 'buddycop', 'budget', 'budspencer',
       'build', 'building', 'bullet', 'bulletwound', 'bully', 'bumble',
       'bunker', 'burglar', 'burglary', 'buriedalive', 'burn',
       'burnedalive', 'burtlancaster', 'bury', 'bus', 'business',
       'businessman', 'butcher', 'butler', 'buy', 'cabin', 'cage',
       'cairo', 'california', 'camcorder', 'camera', 'camerondiaz',
       'camp', 'campaign', 'campus', 'canada', 'canadian', 'cancer',
       'cannabis', 'cannibal', 'cannibalism', 'canuxploitation',
       'capitalism', 'captain', 'captive', 'capture', 'car',
       'car accident', 'caraccident', 'carchase', 'carcrash', 'cardealer',
       'cardgame', 'care', 'career', 'caretaker', 'caribbean',
       'carjourney', 'carloverdone', 'carmechanic', 'carnival', 'carrace',
       'carrie', 'carry', 'carter', 'carygrant', 'case', 'cash', 'casino',
       'cast', 'castle', 'castration', 'cat', 'cat mouse', 'cataclysm',
       'catastrophe', 'catch', 'cateblanchett', 'catherinedeneuve',
       'catherinekeener', 'catherinezeta', 'catherinezeta jones',
       'catholic', 'catholicism', 'cattle', 'cause', 'cavalry', 'cave',
       'caveman', 'celebrate', 'celebration', 'celebrity', 'cell',
       'cellphone', 'cemetery', 'center', 'central', 'century', 'certain',
       'cgi', 'chain', 'chainsaw', 'challenge', 'champion',
       'championship', 'chance', 'change', 'channingtatum', 'chaos',
       'character', 'characters', 'charge', 'charismatic', 'charles',
       'charlie', 'charliechaplin', 'charliesheen', 'charlizetheron',
       'charm', 'chase', 'chasesandraces', 'chauffeur', 'cheat',
       'cheatinghusband', 'cheatingwife', 'cheerlead', 'cheerleader',
       'chef', 'chess', 'chevychase', 'chicago', 'chicken', 'chief',
       'child', 'childabuse', 'childhero', 'childhood',
       'childhoodfriends', 'childhoodmemory', 'childhoodtrauma',
       'childkidnapping', 'childmurder', 'childmurderer', 'childprodigy',
       'children', 'chile', 'chimp', 'chimpanzee', 'china',
       'china martialarts', 'chinatown', 'chinese', 'chinesemafia',
       'chocolate', 'choice', 'choose', 'chris', 'chriscolumbus',
       'chrisevans', 'chriso', 'chrispine', 'chrisrock', 'christ',
       'christian', 'christianbale', 'christianclavier', 'christianity',
       'christianslater', 'christinaricci', 'christmas', 'christmas eve',
       'christmas holiday', 'christmaseve', 'christmasparty',
       'christmastree', 'christopherlee', 'christopherlloyd',
       'christopherplummer', 'christopherwalken', 'chronicle', 'church',
       'cia', 'cigarette', 'cigarettesmoking', 'cigarsmoking',
       'cinderella', 'cinema', 'circle', 'circus', 'citizen', 'city',
       'civil', 'civil war', 'civilization', 'civilwar', 'claim', 'clan',
       'clash', 'class', 'classdifferences', 'classic', 'classicnoir',
       'classmate', 'classroom', 'claudevandamme', 'claustrophobia',
       'clean', 'clear', 'clerk', 'client', 'climb', 'clinteastwood',
       'clinteastwood clinteastwood',
       'clinteastwood clinteastwood clinteastwood', 'clique', 'cliveowen',
       'clock', 'clocktower', 'clone', 'close', 'clown', 'club', 'clue',
       'coach', 'coast', 'cocaine', 'code', 'coffin', 'cold', 'coldwar',
       'colinfarrell', 'colinfirth', 'collapse', 'colleague', 'collect',
       'collector', 'college', 'college student', 'collegestudent',
       'colombia', 'colonel', 'colonialism', 'colony', 'colorado', 'coma',
       'combat', 'come', 'come true', 'comeback', 'comedian', 'comedy',
       'comedy action', 'comedy action adventure', 'comedy action comedy',
       'comedy adventure', 'comedy adventure action',
       'comedy adventure comedy', 'comedy adventure family',
       'comedy animation', 'comedy animation comedy',
       'comedy animation family', 'comedy brazilian', 'comedy comedy',
       'comedy comedy comedy', 'comedy crime', 'comedy crime action',
       'comedy crime adventure', 'comedy crime comedy',
       'comedy crime drama', 'comedy crime mystery',
       'comedy crime romance', 'comedy crime thriller',
       'comedy documentary', 'comedy drama', 'comedy drama action',
       'comedy drama adventure', 'comedy drama comedy',
       'comedy drama crime', 'comedy drama family',
       'comedy drama fantasy', 'comedy drama history',
       'comedy drama horror', 'comedy drama music',
       'comedy drama mystery', 'comedy drama romance',
       'comedy drama sciencefiction', 'comedy drama thriller',
       'comedy drama war', 'comedy family', 'comedy family action',
       'comedy family adventure', 'comedy family animation',
       'comedy family comedy', 'comedy family drama',
       'comedy family fantasy', 'comedy family music',
       'comedy family romance', 'comedy family sciencefiction',
       'comedy fantasy', 'comedy fantasy comedy', 'comedy fantasy horror',
       'comedy fantasy romance', 'comedy fantasy sciencefiction',
       'comedy history', 'comedy horror'], dtype=object)

In [120]:
from sklearn.metrics.pairwise import cosine_similarity

In [121]:
# Normalization

min_votes = movies["vote_count"].min()
max_votes = movies["vote_count"].max()

def norm_votes(v):
    return (v - min_votes) / (max_votes - min_votes)

In [122]:
def recommend(target_idx):
    dist = cosine_similarity(vectors[target_idx], vectors).flatten()

    similar_indices = sorted(
        list(enumerate(dist)), 
        reverse=True, 
        key=lambda x: x[1]
    )[1:51]

    rec_list = []

    for i in similar_indices:
        idx_i = i[0]
        sim_score = i[1]
        temp_df = movies.iloc[idx_i]

        # filter weak films
        if temp_df["rating"] < 6.5:
            continue

        rating_score = temp_df["rating"] / 10
        popularity_score = norm_votes(temp_df["vote_count"])

        final_score = (
            0.6 * sim_score +
            0.25 * rating_score +
            0.15 * popularity_score
        )

        rec_list.append({
            "title": temp_df["title"],
            "rating": temp_df["rating"],
            "score": final_score
        })

    final_recommendations = sorted(
        rec_list, 
        key=lambda x: x["score"], 
        reverse=True
    )

    print(f"Top 10 High Quality Recommendation for {movies.loc[target_idx, 'title']}")
    print("-" * 30)

    for movie in final_recommendations[:10]:
        print(f"- {movie['title']} (Rating: {movie['rating']:.2f})")

In [123]:
def director_spotlight_by_idx(target_idx):
    target_director = movies.loc[target_idx, "crew"]

    director_movies = movies[(movies["crew"]==target_director) & (movies.index != target_idx)]

    if director_movies.empty:
        return target_director, []

    top_director_df = director_movies.sort_values("rating", ascending = False).head(5)
    director_recs = top_director_df[["title", "rating"]].to_dict("records")

    return target_director, director_recs

In [124]:
def enhanced_recommend(movie_title):
    movie_title = movie_title.lower()

    match = movies[movies["title"].str.lower() == movie_title]

    if match.empty:
        match = movies[movies["title"].str.lower().str.contains(movie_title)]

    if match.empty:
        print("Movie not found 😅")
        return 

    target_idx = match.sort_values("rating", ascending=False).index[0]

    print("\n" + "=" * 60)

    recommend(target_idx)

    director_name, dir_recs = director_spotlight_by_idx(target_idx)

    if dir_recs:
        print(f"\n🎥 Director's Spotlight: More from {director_name}")
        print("-" * 30)
        for d_movie in dir_recs:
            print(f"- {d_movie['title']} (Rating: {d_movie['rating']:.2f})")
    else:
        print(f"\n🎥 No other high-quality films by this director in our database.")

In [125]:
movies_to_test = [
    "Finding Nemo",
    "Pulp Fiction",
    "The Avengers",
    "Inception",
    "The Dark Knight",
    "Toy Story",
    "Fight Club",
    "Interstellar",
    "Before Sunset",
    "Eternal Sunshine of the Spotless Mind",
    "Memento",
    "Taare Zameen Par",
    "Shutter Island",
    "Wolf of Wall Street",
    "Lord of the Rings",
    "Harry Potter",
    "12 Angry Men",
    "Pather Panchali",
    "Silence of the Lambs",
    "Schindler's List",
    "The Godfather",
    "prestige",
    "Incendies",
    "Psycho"
]

In [126]:
def batch_recommend(movie_list):
    for movie in movie_list:
        enhanced_recommend(movie)

In [127]:
batch_recommend(movies_to_test)

============================================================
Top 10 High Quality Recommendation for Finding Nemo (2003)
------------------------------
- Coraline (2009) (Rating: 7.28)
- WALL·E (2008) (Rating: 7.79)
- Winnie the Pooh (2011) (Rating: 6.74)
- Monsters University (2013) (Rating: 6.99)
- Azur & Asmar: The Princes' Quest (2006) (Rating: 7.18)
- Anastasia (1997) (Rating: 7.38)
- Professor Layton and the Eternal Diva (2009) (Rating: 7.03)
- Mickey's Twice Upon a Christmas (2004) (Rating: 6.81)
- The Sword in the Stone (1963) (Rating: 6.88)
- Kung Fu Panda 2 (2011) (Rating: 6.69)

🎥 Director's Spotlight: More from andrewstanton
------------------------------
- WALL·E (2008) (Rating: 7.79)
- John Carter (2012) (Rating: 6.10)

============================================================
Top 10 High Quality Recommendation for Pulp Fiction (1994)
------------------------------
- Reservoir Dogs (1992) (Rating: 8.08)
- A Pure Formality (1994) (Rating: 7.19)
- Million Dollar Baby (2004) (Rating: 7.68)
- Ali (2001) (Rating: 6.67)
- John Doe: Vigilante (2014) (Rating: 6.56)
- Snatch (2000) (Rating: 7.68)
- The Night of the Hunter (1955) (Rating: 7.75)
- Headhunters (2011) (Rating: 7.13)
- The Absent One (2014) (Rating: 6.88)
- The Raid (2011) (Rating: 7.27)

🎥 Director's Spotlight: More from quentintarantino
------------------------------
- Reservoir Dogs (1992) (Rating: 8.08)
- Inglourious Basterds (2009) (Rating: 7.89)
- Django Unchained (2012) (Rating: 7.80)
- Kill Bill: Vol. 1 (2003) (Rating: 7.69)
- Kill Bill: Vol. 2 (2004) (Rating: 7.69)

============================================================
Top 10 High Quality Recommendation for The Avengers (2012)
------------------------------
- Ant-Man (2015) (Rating: 7.00)
- Captain America: The Winter Soldier (2014) (Rating: 7.59)
- Iron Man 3 (2013) (Rating: 6.80)
- Avengers: Age of Ultron (2015) (Rating: 7.30)
- Doctor Strange (2016) (Rating: 7.10)
- Thor: The Dark World (2013) (Rating: 6.80)
- Captain America: The First Avenger (2011) (Rating: 6.60)
- Deadpool (2016) (Rating: 7.40)
- Iron Man (2008) (Rating: 7.40)
- Iron Man 2 (2010) (Rating: 6.60)

🎥 Director's Spotlight: More from josswhedon
------------------------------
- Serenity (2005) (Rating: 7.37)
- Avengers: Age of Ultron (2015) (Rating: 7.30)
- Much Ado About Nothing (2012) (Rating: 6.92)

============================================================
Top 10 High Quality Recommendation for Inception (2010)
------------------------------
- Minority Report (2002) (Rating: 7.09)
- Super 8 (2011) (Rating: 6.60)
- Source Code (2011) (Rating: 7.09)
- The Thirteenth Floor (1999) (Rating: 6.76)
- 2001: A Space Odyssey (1968) (Rating: 7.88)
- Gattaca (1997) (Rating: 7.48)
- Sherlock Holmes: A Game of Shadows (2011) (Rating: 6.99)
- Cube (1997) (Rating: 6.88)
- Looper (2012) (Rating: 6.60)
- The Matrix Reloaded (2003) (Rating: 6.70)

🎥 Director's Spotlight: More from christophernolan
------------------------------
- The Dark Knight (2008) (Rating: 8.29)
- Interstellar (2014) (Rating: 8.09)
- Memento (2000) (Rating: 8.09)
- The Prestige (2006) (Rating: 7.99)
- The Dark Knight Rises (2012) (Rating: 7.60)

============================================================
Top 10 High Quality Recommendation for The Dark Knight (2008)
------------------------------
- The Dark Knight Rises (2012) (Rating: 7.60)
- Batman Begins (2005) (Rating: 7.49)
- Batman: Under the Red Hood (2010) (Rating: 7.51)
- Batman Returns (1992) (Rating: 6.59)
- Batman: Assault on Arkham (2014) (Rating: 7.20)
- The Lego Batman Movie (2017) (Rating: 7.18)
- Kill the Irishman (2011) (Rating: 6.64)
- Thursday (1998) (Rating: 6.80)
- Metro Manila (2013) (Rating: 6.87)
- Batman (1989) (Rating: 6.99)

🎥 Director's Spotlight: More from christophernolan
------------------------------
- Inception (2010) (Rating: 8.10)
- Interstellar (2014) (Rating: 8.09)
- Memento (2000) (Rating: 8.09)
- The Prestige (2006) (Rating: 7.99)
- The Dark Knight Rises (2012) (Rating: 7.60)

============================================================
Top 10 High Quality Recommendation for Toy Story (1995)
------------------------------
- Toy Story 2 (1999) (Rating: 7.29)
- Monsters, Inc. (2001) (Rating: 7.49)
- Toy Story 3 (2010) (Rating: 7.59)
- Despicable Me 2 (2013) (Rating: 7.00)
- Up (2009) (Rating: 7.79)
- The Lego Movie (2014) (Rating: 7.49)
- The SpongeBob SquarePants Movie (2004) (Rating: 6.68)
- Frankenweenie (2012) (Rating: 6.59)
- Meet the Robinsons (2007) (Rating: 6.68)
- The Simpsons Movie (2007) (Rating: 6.89)

🎥 Director's Spotlight: More from johnlasseter
------------------------------
- Toy Story 2 (1999) (Rating: 7.29)
- A Bug's Life (1998) (Rating: 6.79)

============================================================
Top 10 High Quality Recommendation for Fight Club (1999)
------------------------------
- Se7en (1995) (Rating: 8.09)
- The Machinist (2004) (Rating: 7.27)
- One Flew Over the Cuckoo's Nest (1975) (Rating: 8.28)
- Mouchette (1967) (Rating: 6.88)
- The Social Network (2010) (Rating: 7.09)
- I Stand Alone (1998) (Rating: 7.20)
- Oldboy (2003) (Rating: 7.97)
- Dead Man's Shoes (2004) (Rating: 7.04)
- A Touch of Sin (2013) (Rating: 7.01)
- The Life of Oharu (1952) (Rating: 7.42)

🎥 Director's Spotlight: More from davidfincher
------------------------------
- Se7en (1995) (Rating: 8.09)
- Gone Girl (2014) (Rating: 7.89)
- The Game (1997) (Rating: 7.47)
- The Curious Case of Benjamin Button (2008) (Rating: 7.29)
- Zodiac (2007) (Rating: 7.28)

============================================================
Top 10 High Quality Recommendation for Interstellar (2014)
------------------------------
- The Martian (2015) (Rating: 7.59)
- Guardians of the Galaxy (2014) (Rating: 7.89)
- Apollo 13 (1995) (Rating: 7.28)
- The Matrix (1999) (Rating: 7.89)
- Passengers (2016) (Rating: 6.70)
- Rogue One: A Star Wars Story (2016) (Rating: 7.39)
- 2001: A Space Odyssey (1968) (Rating: 7.88)
- Alien (1979) (Rating: 7.89)
- A.I. Artificial Intelligence (2001) (Rating: 6.79)
- Gravity (2013) (Rating: 7.29)

🎥 Director's Spotlight: More from christophernolan
------------------------------
- The Dark Knight (2008) (Rating: 8.29)
- Inception (2010) (Rating: 8.10)
- Memento (2000) (Rating: 8.09)
- The Prestige (2006) (Rating: 7.99)
- The Dark Knight Rises (2012) (Rating: 7.60)

============================================================
Top 10 High Quality Recommendation for Before Sunset (2004)
------------------------------
- Before Sunrise (1995) (Rating: 7.65)
- Two Lovers (2008) (Rating: 6.55)
- Veer-Zaara (2004) (Rating: 7.10)
- Letter from an Unknown Woman (1948) (Rating: 7.44)
- Frida (2002) (Rating: 7.22)
- The Notebook (2004) (Rating: 7.69)
- An Officer and a Gentleman (1982) (Rating: 6.74)
- The Magnificent Ambersons (1942) (Rating: 7.14)
- A Beautiful Mind (2001) (Rating: 7.68)
- Sex and Lucia (2001) (Rating: 6.54)

🎥 Director's Spotlight: More from richardlinklater
------------------------------
- Before Sunrise (1995) (Rating: 7.65)
- Boyhood (2014) (Rating: 7.48)
- Waking Life (2001) (Rating: 7.45)
- Dazed and Confused (1993) (Rating: 7.34)
- Before Midnight (2013) (Rating: 7.25)

============================================================
Top 10 High Quality Recommendation for Eternal Sunshine of the Spotless Mind (2004)
------------------------------
- Her (2013) (Rating: 7.89)
- Nineteen Eighty-Four (1984) (Rating: 6.75)
- In Your Eyes (2014) (Rating: 7.01)
- On the Beach (1959) (Rating: 6.56)
- Mr. Nobody (2009) (Rating: 7.87)
- Never Let Me Go (2010) (Rating: 6.78)
- Comet (2014) (Rating: 6.71)
- Arrival (2016) (Rating: 7.19)
- Safety Not Guaranteed (2012) (Rating: 6.77)
- The Disappearance of Haruhi Suzumiya (2010) (Rating: 7.21)

🎥 Director's Spotlight: More from michelgondry
------------------------------
- The Science of Sleep (2006) (Rating: 6.74)
- Be Kind Rewind (2008) (Rating: 6.21)
- Human Nature (2001) (Rating: 6.17)
- Microbe and Gasoline (2015) (Rating: 6.15)
- Mood Indigo (2013) (Rating: 6.05)

============================================================
Top 10 High Quality Recommendation for Memento (2000)
------------------------------
- Blue Ruin (2014) (Rating: 6.86)
- The Hound of the Baskervilles (1939) (Rating: 6.88)
- New World (2013) (Rating: 7.00)
- Salton Sea (2002) (Rating: 6.84)
- The Last Seduction (1994) (Rating: 6.59)
- The Aura (2005) (Rating: 6.64)
- The Hidden Face (2011) (Rating: 7.16)
- Insomnia (2002) (Rating: 6.79)
- Talaash (2012) (Rating: 6.56)
- SPL: Kill Zone (2005) (Rating: 6.65)

🎥 Director's Spotlight: More from christophernolan
------------------------------
- The Dark Knight (2008) (Rating: 8.29)
- Inception (2010) (Rating: 8.10)
- Interstellar (2014) (Rating: 8.09)
- The Prestige (2006) (Rating: 7.99)
- The Dark Knight Rises (2012) (Rating: 7.60)

============================================================
Top 10 High Quality Recommendation for Taare Zameen Par (2007)
------------------------------
- Like Father, Like Son (2013) (Rating: 7.32)
- Kes (1969) (Rating: 7.26)
- Glory Road (2006) (Rating: 7.03)
- The Chorus (2004) (Rating: 7.43)
- Skirt Day (2008) (Rating: 6.81)
- The Hunt (2012) (Rating: 7.85)
- Modigliani (2004) (Rating: 6.86)
- Coach Carter (2005) (Rating: 7.24)
- Swades: We, the People (2004) (Rating: 7.00)
- Andrei Rublev (1966) (Rating: 7.67)

🎥 No other high-quality films by this director in our database.

============================================================
Top 10 High Quality Recommendation for Shutter Island (2010)
------------------------------
- Confessions (2010) (Rating: 7.44)
- Before I Fall (2017) (Rating: 6.78)
- The Collector (1965) (Rating: 6.63)
- The Game (1997) (Rating: 7.47)
- Murder on the Orient Express (1974) (Rating: 6.83)
- Pi (1998) (Rating: 7.06)
- Death and the Maiden (1994) (Rating: 6.89)
- Tinker Tailor Soldier Spy (2011) (Rating: 6.59)
- Caché (2005) (Rating: 6.91)
- The Curious Case of Benjamin Button (2008) (Rating: 7.29)

🎥 Director's Spotlight: More from martinscorsese
------------------------------
- GoodFellas (1990) (Rating: 8.18)
- Taxi Driver (1976) (Rating: 8.08)
- The Wolf of Wall Street (2013) (Rating: 7.89)
- The Departed (2006) (Rating: 7.89)
- Casino (1995) (Rating: 7.76)

============================================================
Top 10 High Quality Recommendation for The Wolf of Wall Street (2013)
------------------------------
- War Dogs (2016) (Rating: 6.79)
- Adaptation. (2002) (Rating: 7.25)
- Gentlemen of Fortune (1971) (Rating: 6.90)
- The Ax (2005) (Rating: 6.67)
- Spun (2002) (Rating: 6.54)
- Four Lions (2010) (Rating: 7.04)
- Filth (2013) (Rating: 6.78)
- The Big Short (2015) (Rating: 7.29)
- Gridlock'd (1997) (Rating: 6.62)
- Dope (2015) (Rating: 7.16)

🎥 Director's Spotlight: More from martinscorsese
------------------------------
- GoodFellas (1990) (Rating: 8.18)
- Taxi Driver (1976) (Rating: 8.08)
- The Departed (2006) (Rating: 7.89)
- Shutter Island (2010) (Rating: 7.79)
- Casino (1995) (Rating: 7.76)

============================================================
Top 10 High Quality Recommendation for The Lord of the Rings: The Return of the King (2003)
------------------------------
- The Lord of the Rings: The Two Towers (2002) (Rating: 7.99)
- The Lord of the Rings: The Fellowship of the Ring (2001) (Rating: 7.99)
- The Hobbit: The Battle of the Five Armies (2014) (Rating: 7.09)
- The Hobbit: An Unexpected Journey (2012) (Rating: 7.00)
- The Hobbit: The Desolation of Smaug (2013) (Rating: 7.59)
- Conan the Barbarian (1982) (Rating: 6.59)
- Thor (2011) (Rating: 6.60)
- Pirates of the Caribbean: The Curse of the Black Pearl (2003) (Rating: 7.49)
- Wonder Woman (2017) (Rating: 7.19)
- Pirates of the Caribbean: Dead Man's Chest (2006) (Rating: 7.00)

🎥 Director's Spotlight: More from peterjackson
------------------------------
- The Lord of the Rings: The Fellowship of the Ring (2001) (Rating: 7.99)
- The Lord of the Rings: The Two Towers (2002) (Rating: 7.99)
- The Hobbit: The Desolation of Smaug (2013) (Rating: 7.59)
- Braindead (1992) (Rating: 7.31)
- The Hobbit: The Battle of the Five Armies (2014) (Rating: 7.09)

============================================================
Top 10 High Quality Recommendation for Harry Potter and the Deathly Hallows: Part 2 (2011)
------------------------------
- Fantastic Beasts and Where to Find Them (2016) (Rating: 7.19)
- Return to Oz (1985) (Rating: 6.54)
- Sapphire Blue (2014) (Rating: 6.84)
- Jason and the Argonauts (1963) (Rating: 6.95)
- Harry Potter and the Goblet of Fire (2005) (Rating: 7.49)
- Gulliver's Travels (1996) (Rating: 6.61)
- The Chronicles of Narnia: The Lion, the Witch and the Wardrobe (2005) (Rating: 6.70)
- Harry Potter and the Philosopher's Stone (2001) (Rating: 7.49)
- Labyrinth (1986) (Rating: 7.06)
- Spirited Away (2001) (Rating: 8.28)

🎥 Director's Spotlight: More from davidyates
------------------------------
- Harry Potter and the Deathly Hallows: Part 1 (2010) (Rating: 7.49)
- Harry Potter and the Order of the Phoenix (2007) (Rating: 7.39)
- Harry Potter and the Half-Blood Prince (2009) (Rating: 7.39)
- Fantastic Beasts and Where to Find Them (2016) (Rating: 7.19)
- The Legend of Tarzan (2016) (Rating: 5.51)

============================================================
Top 10 High Quality Recommendation for 12 Angry Men (1957)
------------------------------
- The Verdict (1982) (Rating: 7.18)
- 12 Angry Men (1997) (Rating: 7.07)
- Anatomy of a Murder (1959) (Rating: 7.51)
- The Rainmaker (1997) (Rating: 6.65)
- Philadelphia (1993) (Rating: 7.56)
- Runaway Jury (2003) (Rating: 6.85)
- The Judge (2014) (Rating: 7.18)
- The Passion of Joan of Arc (1928) (Rating: 7.87)
- Hamlet (1948) (Rating: 6.78)
- A Time to Kill (1996) (Rating: 6.96)

🎥 Director's Spotlight: More from sidneylumet
------------------------------
- Network (1976) (Rating: 7.68)
- Dog Day Afternoon (1975) (Rating: 7.54)
- Serpico (1973) (Rating: 7.41)
- Fail-Safe (1964) (Rating: 7.23)
- The Verdict (1982) (Rating: 7.18)

============================================================
Top 10 High Quality Recommendation for Pather Panchali (1955)
------------------------------
- Calvary (2014) (Rating: 7.03)
- Diary of a Country Priest (1951) (Rating: 7.07)
- The World of Apu (1959) (Rating: 7.34)
- 8½ (1963) (Rating: 7.78)
- Bicycle Thieves (1948) (Rating: 7.87)
- La Notte (1961) (Rating: 7.26)
- La Haine (1995) (Rating: 7.83)
- Front of the Class (2008) (Rating: 7.06)
- Departures (2008) (Rating: 7.50)
- Winter Light (1963) (Rating: 7.21)

🎥 Director's Spotlight: More from satyajitray
------------------------------
- The World of Apu (1959) (Rating: 7.34)
- Aparajito (1956) (Rating: 7.21)

============================================================
Top 10 High Quality Recommendation for The Silence of the Lambs (1991)
------------------------------
- Red Dragon (2002) (Rating: 6.69)
- The Bandit (1996) (Rating: 7.03)
- Suburra (2015) (Rating: 7.29)
- Zulu (2013) (Rating: 6.64)
- Animal Kingdom (2010) (Rating: 6.65)
- End of Watch (2012) (Rating: 7.18)
- Stray Dog (1949) (Rating: 6.93)
- Antibodies (2005) (Rating: 6.52)
- Road to Perdition (2002) (Rating: 7.27)
- Frenzy (1972) (Rating: 7.05)

🎥 Director's Spotlight: More from jonathandemme
------------------------------
- Stop Making Sense (1984) (Rating: 7.70)
- Philadelphia (1993) (Rating: 7.56)
- Something Wild (1986) (Rating: 6.44)
- The Manchurian Candidate (2004) (Rating: 6.21)
- Rachel Getting Married (2008) (Rating: 6.14)

============================================================
Top 10 High Quality Recommendation for Schindler's List (1993)
------------------------------
- Come and See (1985) (Rating: 7.81)
- Winter in Wartime (2008) (Rating: 6.64)
- Stalingrad (1993) (Rating: 7.15)
- Land of Mine (2015) (Rating: 7.64)
- Katyn (2007) (Rating: 6.55)
- Beneath Hill 60 (2010) (Rating: 6.80)
- Max Manus: Man of War (2008) (Rating: 6.73)
- Che: Part Two (2009) (Rating: 6.63)
- The Boy in the Striped Pyjamas (2008) (Rating: 7.67)
- The Round Up (2010) (Rating: 7.39)

🎥 Director's Spotlight: More from stevenspielberg
------------------------------
- Saving Private Ryan (1998) (Rating: 7.89)
- Raiders of the Lost Ark (1981) (Rating: 7.69)
- Catch Me If You Can (2002) (Rating: 7.69)
- Jurassic Park (1993) (Rating: 7.59)
- Indiana Jones and the Last Crusade (1989) (Rating: 7.59)

============================================================
Top 10 High Quality Recommendation for The Godfather (1972)
------------------------------
- The Godfather: Part II (1974) (Rating: 8.28)
- The Shawshank Redemption (1994) (Rating: 8.49)
- The Consequences of Love (2004) (Rating: 7.33)
- Election 2 (2006) (Rating: 6.73)
- Serial Killer 1 (2015) (Rating: 6.81)
- One Hundred Steps (2000) (Rating: 7.46)
- GoodFellas (1990) (Rating: 8.18)
- Election (2005) (Rating: 6.55)
- A Gang Story (2011) (Rating: 6.59)
- The Godfather: Part III (1990) (Rating: 7.08)

🎥 Director's Spotlight: More from francisfordcoppola
------------------------------
- The Godfather: Part II (1974) (Rating: 8.28)
- Apocalypse Now (1979) (Rating: 7.97)
- The Conversation (1974) (Rating: 7.40)
- The Godfather: Part III (1990) (Rating: 7.08)
- Dracula (1992) (Rating: 7.08)

============================================================
Top 10 High Quality Recommendation for The Prestige (2006)
------------------------------
- Gone Girl (2014) (Rating: 7.89)
- The Return (2003) (Rating: 7.13)
- Disturbia (2007) (Rating: 6.59)
- The Sixth Sense (1999) (Rating: 7.69)
- Page Eight (2011) (Rating: 6.63)
- Gosford Park (2001) (Rating: 6.74)
- The Constant Gardener (2005) (Rating: 6.86)
- Rear Window (1954) (Rating: 8.16)
- Kiss Me Deadly (1955) (Rating: 6.87)
- Spellbound (1945) (Rating: 7.13)

🎥 Director's Spotlight: More from christophernolan
------------------------------
- The Dark Knight (2008) (Rating: 8.29)
- Inception (2010) (Rating: 8.10)
- Interstellar (2014) (Rating: 8.09)
- Memento (2000) (Rating: 8.09)
- The Dark Knight Rises (2012) (Rating: 7.60)

============================================================
Top 10 High Quality Recommendation for Incendies (2010)
------------------------------
- Feed (2017) (Rating: 6.90)
- Waltz with Bashir (2008) (Rating: 7.65)
- Black Narcissus (1947) (Rating: 7.36)
- The Message (1977) (Rating: 7.08)
- Taste of Cherry (1997) (Rating: 6.86)
- Before the Rain (1994) (Rating: 7.11)
- Testament of Youth (2014) (Rating: 7.10)
- The Battle of Algiers (1966) (Rating: 7.55)
- Escape Plan (2013) (Rating: 6.69)
- Beasts of No Nation (2015) (Rating: 7.51)

🎥 Director's Spotlight: More from denisvilleneuve
------------------------------
- Prisoners (2013) (Rating: 7.88)
- Arrival (2016) (Rating: 7.19)
- Sicario (2015) (Rating: 7.19)
- Enemy (2013) (Rating: 6.69)
- Polytechnique (2009) (Rating: 6.67)

============================================================
Top 10 High Quality Recommendation for Psycho (1960)
------------------------------
- The Cremator (1969) (Rating: 7.22)
- Peeping Tom (1960) (Rating: 7.36)
- Bleeder (1999) (Rating: 6.71)
- Goodnight Mommy (2014) (Rating: 6.57)
- Magic (1978) (Rating: 6.75)
- Thirst (2009) (Rating: 6.90)
- Black Christmas (1974) (Rating: 6.70)
- Diabolique (1955) (Rating: 7.67)
- Funny Games (1997) (Rating: 7.22)
- The Texas Chain Saw Massacre (1974) (Rating: 7.06)

🎥 Director's Spotlight: More from alfredhitchcock
------------------------------
- Rear Window (1954) (Rating: 8.16)
- Vertigo (1958) (Rating: 7.95)
- Dial M for Murder (1954) (Rating: 7.81)
- North by Northwest (1959) (Rating: 7.75)
- Rope (1948) (Rating: 7.71)