In [1]:
import pandas as pd
import numpy as np

In [2]:
credits = pd.read_csv(r"C:\Users\Varun Bahuguna\OneDrive\Desktop\content-based-recommendation-system\data\credits.csv")
keywords = pd.read_csv(r"C:\Users\Varun Bahuguna\OneDrive\Desktop\content-based-recommendation-system\data\keywords.csv")
meta = pd.read_csv(r"C:\Users\Varun Bahuguna\OneDrive\Desktop\content-based-recommendation-system\data\movies_metadata.csv")

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_18640\3024848566.py:3: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  meta = pd.read_csv(r"C:\Users\Varun Bahuguna\OneDrive\Desktop\content-based-recommendation-system\data\movies_metadata.csv")

In [3]:
credits

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862
...,...,...,...
45471,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de...",439050
45472,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...",111109
45473,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",67758
45474,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",227506
45475,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",461257

In [4]:
credits.shape

(45476, 3)

In [5]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB

In [6]:
keywords

           id                                           keywords
0         862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1        8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2       15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3       31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4       11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...
...       ...                                                ...
46414  439050             [{'id': 10703, 'name': 'tragic love'}]
46415  111109  [{'id': 2679, 'name': 'artist'}, {'id': 14531,...
46416   67758                                                 []
46417  227506                                                 []
46418  461257                                                 []

[46419 rows x 2 columns]

In [7]:
keywords.shape

(46419, 2)

In [8]:
keywords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46419 entries, 0 to 46418
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46419 non-null  int64
 1   keywords  46419 non-null  object
dtypes: int64(1), object(1)
memory usage: 725.4+ KB

In [9]:
meta

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

In [10]:
meta.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [11]:
meta.shape

(45466, 24)

In [12]:
meta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [13]:
# id is the common column in all, and its int in credits and keywords, but is string in meta
# convert string id in meta to int id !

meta['id'] = pd.to_numeric(meta['id'], errors='coerce')

In [14]:
meta['id'].isnull().sum()

np.int64(3)

In [15]:
meta[meta['id'].isnull()]

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
19730,- Written by Ørnås,0.065736,/ff9qCepilowshEtG2GYWwzt2bs4.jpg,"[{'name': 'Carousel Productions', 'id': 11176}...","[{'iso_3166_1': 'CA', 'name': 'Canada'}, {'iso...",NaN,0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29503,Rune Balot goes to a casino connected to the ...,1.931659,/zV8bHuSL6WXoD6FWogP9j4x80bL.jpg,"[{'name': 'Aniplex', 'id': 2883}, {'name': 'Go...","[{'iso_3166_1': 'US', 'name': 'United States o...",NaN,0,68.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,...,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35587,Avalanche Sharks tells the story of a bikini ...,2.185485,/zaSf5OG7V8X8gqFvly88zDdRm46.jpg,"[{'name': 'Odyssey Media', 'id': 17161}, {'nam...","[{'iso_3166_1': 'CA', 'name': 'Canada'}]",NaN,0,82.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,...,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
meta = meta.dropna(subset=["id"])

In [17]:
meta.shape

(45463, 24)

In [18]:
meta.info()

<class 'pandas.core.frame.DataFrame'>
Index: 45463 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45463 non-null  object
 1   belongs_to_collection  4491 non-null   object
 2   budget                 45463 non-null  object
 3   genres                 45463 non-null  object
 4   homepage               7779 non-null   object
 5   id                     45463 non-null  float64
 6   imdb_id                45446 non-null  object
 7   original_language      45452 non-null  object
 8   original_title         45463 non-null  object
 9   overview               44509 non-null  object
 10  popularity             45460 non-null  object
 11  poster_path            45077 non-null  object
 12  production_companies   45460 non-null  object
 13  production_countries   45460 non-null  object
 14  release_date           45376 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(5), object(19)
memory usage: 8.7+ MB

In [19]:
meta["release_date"]

0        1995-10-30
1        1995-12-15
2        1995-12-22
3        1995-12-22
4        1995-02-10
            ...
45461           NaN
45462    2011-11-17
45463    2003-08-01
45464    1917-10-21
45465    2017-06-09
Name: release_date, Length: 45463, dtype: object

In [20]:
# Convert release_date to datetime and extract year
meta['year'] = pd.to_datetime(meta['release_date'], errors='coerce').dt.year.fillna(0).astype(int)

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_18640\3858204944.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta['year'] = pd.to_datetime(meta['release_date'], errors='coerce').dt.year.fillna(0).astype(int)

In [21]:
meta

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,year
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862.0,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,1995
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844.0,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0,1995
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602.0,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0,1995
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357.0,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0,1995
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862.0,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050.0,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0,0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109.0,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0,2011
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758.0,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0,2003
45464,False,NaN,0,[],NaN,227506.0,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0,1917
45465,False,NaN,0,[],NaN,461257.0,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0,2017

In [22]:
# Create a unique display title: "Toy Story (1995)"
# We do this BEFORE the merge to ensure we have the year ready
meta['title'] = meta['title'] + " (" + meta['year'].astype(str) + ")"

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_18640\2973620798.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta['title'] = meta['title'] + " (" + meta['year'].astype(str) + ")"

In [23]:
meta['title']

0                          Toy Story (1995)
1                            Jumanji (1995)
2                   Grumpier Old Men (1995)
3                  Waiting to Exhale (1995)
4        Father of the Bride Part II (1995)
                        ...
45461                            Subdue (0)
45462            Century of Birthing (2011)
45463                       Betrayal (2003)
45464               Satan Triumphant (1917)
45465                       Queerama (2017)
Name: title, Length: 45463, dtype: object

In [24]:
meta.duplicated(subset = ["title"]).sum()

np.int64(83)

In [25]:
meta[meta.duplicated(subset = ["title"], keep = False)].sort_values("title")

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,year
24109,False,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",NaN,2965.0,tt0118247,en,"20,000 Leagues Under the Sea","In the 19th century, an expert marine biologis...",...,0.0,95.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Darkness is to be feared... above and below.,"20,000 Leagues Under the Sea (1997)",False,6.3,3.0,1997
20848,False,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,2966.0,tt0118248,en,"20,000 Leagues Under the Sea","The year is 1886, when New England's fishing h...",...,0.0,158.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Welcome to the last place on earth.,"20,000 Leagues Under the Sea (1997)",False,4.6,13.0,1997
949,False,NaN,4,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,22649.0,tt0022879,en,A Farewell to Arms,British nurse Catherine Barkley (Helen Hayes) ...,...,25.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Every woman who has loved will understand,A Farewell to Arms (1932),False,6.2,29.0,1932
15074,False,NaN,4,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,22649.0,tt0022879,en,A Farewell to Arms,British nurse Catherine Barkley (Helen Hayes) ...,...,25.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Every woman who has loved will understand,A Farewell to Arms (1932),False,6.2,29.0,1932
2564,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,84198.0,tt1736049,en,A Place at the Table,"Using personal stories, this powerful document...",...,0.0,84.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,One Nation. Underfed.,A Place at the Table (2012),False,6.9,7.0,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
838,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,132641.0,tt0046468,ja,Tsuma,"Ten years into a marriage, the wife is disappo...",...,0.0,89.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Wife (1953),False,0.0,0.0,1953
30001,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,132641.0,tt0046468,ja,Tsuma,"Ten years into a marriage, the wife is disappo...",...,0.0,89.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Wife (1953),False,0.0,0.0,1953
19729,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,82663.0,tt0113002,en,Midnight Man,British soldiers force a recently captured IRA...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
29502,False,"{'id': 122661, 'name': 'Mardock Scramble Colle...",0,"[{'id': 16, 'name': 'Animation'}, {'id': 878, ...",http://m-scramble.jp/exhaust/,122662.0,tt2423504,ja,マルドゥック・スクランブル 排気,Third film of the Mardock Scramble series.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
35586,False,NaN,0,"[{'id': 10770, 'name': 'TV Movie'}, {'id': 28,...",NaN,249260.0,tt2622826,en,Avalanche Sharks,A group of skiers are terrorized during spring...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [26]:
credits.shape

(45476, 3)

In [27]:
credits.duplicated(subset=['id']).sum()

np.int64(44)

In [28]:
credits[credits.duplicated(subset = ["id"], keep = False)].sort_values("id")

,cast,crew,id
25950,"[{'cast_id': 12, 'character': 'The Creature', ...","[{'credit_id': '52fe4380c3a36847f80590dd', 'de...",3057
25885,"[{'cast_id': 12, 'character': 'The Creature', ...","[{'credit_id': '52fe4380c3a36847f80590dd', 'de...",3057
5865,"[{'cast_id': 15, 'character': 'Chuck Barris', ...","[{'credit_id': '52fe43e2c3a36847f80760b5', 'de...",4912
33838,"[{'cast_id': 15, 'character': 'Chuck Barris', ...","[{'credit_id': '52fe43e2c3a36847f80760a9', 'de...",4912
9165,"[{'cast_id': 11, 'character': 'Jef Costello', ...","[{'credit_id': '52fe440ac3a36847f807ee01', 'de...",5511
...,...,...,...
25954,"[{'cast_id': 7, 'character': 'Hollander', 'cre...","[{'credit_id': '52fe4da29251416c9111ce5d', 'de...",199591
24163,"[{'cast_id': 2, 'character': 'Ebba', 'credit_i...","[{'credit_id': '534fd1a80e0a267eb6000e32', 'de...",265189
45275,"[{'cast_id': 2, 'character': 'Ebba', 'credit_i...","[{'credit_id': '534fd1a80e0a267eb6000e32', 'de...",265189
33196,"[{'cast_id': 1, 'character': 'Jenjira', 'credi...","[{'credit_id': '5448c8efc3a3680fb4001582', 'de...",298721
40051,"[{'cast_id': 1, 'character': 'Jenjira', 'credi...","[{'credit_id': '5739ceeac3a3683c9d000c12', 'de...",298721

In [29]:
credits = credits.drop_duplicates(subset=['id'])

In [30]:
credits.duplicated(subset=['id']).sum()

np.int64(0)

In [31]:
credits.shape

(45432, 3)

In [32]:
keywords.shape

(46419, 2)

In [33]:
keywords.duplicated(subset=['id']).sum()

np.int64(987)

In [34]:
keywords[keywords.duplicated(subset = ["id"], keep = False)].sort_values("id")

           id                                           keywords
37095    1998  [{'id': 417, 'name': 'corruption'}, {'id': 612...
36138    1998  [{'id': 417, 'name': 'corruption'}, {'id': 612...
36822    3025  [{'id': 212, 'name': 'london england'}, {'id':...
35865    3025  [{'id': 212, 'name': 'london england'}, {'id':...
35999    3692  [{'id': 470, 'name': 'spy'}, {'id': 591, 'name...
...       ...                                                ...
36190  380841                                                 []
36193  380864                                                 []
37150  380864                                                 []
37280  381353                                                 []
36323  381353                                                 []

[1972 rows x 2 columns]

In [35]:
keywords = keywords.drop_duplicates(subset=['id'])

In [36]:
keywords.duplicated(subset=['id']).sum()

np.int64(0)

In [37]:
keywords.shape

(45432, 2)

In [38]:
meta.shape

(45463, 25)

In [39]:
meta.duplicated(subset=['id']).sum()

np.int64(30)

In [40]:
meta[meta.duplicated(subset = ["id"], keep = False)].sort_values("id")

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,year
5865,False,NaN,30000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,4912.0,tt0270288,en,Confessions of a Dangerous Mind,"Television made him famous, but his biggest hi...",...,33013805.0,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some things are better left top secret.,Confessions of a Dangerous Mind (2002),False,6.6,281.0,2002
33826,False,NaN,30000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,4912.0,tt0270288,en,Confessions of a Dangerous Mind,"Television made him famous, but his biggest hi...",...,33013805.0,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some things are better left top secret.,Confessions of a Dangerous Mind (2002),False,6.6,281.0,2002
9165,False,NaN,0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,5511.0,tt0062229,fr,Le Samouraï,Hitman Jef Costello is a perfectionist who alw...,...,39481.0,105.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,There is no solitude greater than that of the ...,Le Samouraï (1967),False,7.9,187.0,1967
7345,False,NaN,0,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,5511.0,tt0062229,fr,Le Samouraï,Hitman Jef Costello is a perfectionist who alw...,...,39481.0,105.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,There is no solitude greater than that of the ...,Le Samouraï (1967),False,7.9,187.0,1967
44821,False,"{'id': 34055, 'name': 'Pokémon Collection', 'p...",16000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://movies.warnerbros.com/pk3/,10991.0,tt0235679,ja,Pokémon 3: The Movie,When Molly Hale's sadness of her father's disa...,...,68411275.0,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown (2000),False,6.0,144.0,2000
4114,False,"{'id': 34055, 'name': 'Pokémon Collection', 'p...",16000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://movies.warnerbros.com/pk3/,10991.0,tt0235679,ja,Pokémon 3: The Movie,When Molly Hale's sadness of her father's disa...,...,68411275.0,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Pokémon: Spell of the Unknown,Pokémon: Spell of the Unknown (2000),False,6.0,143.0,2000
14012,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.dealthemovie.com/,11115.0,tt0446676,en,Deal,As an ex-gambler teaches a hot-shot college ki...,...,0.0,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Deal (2008),False,5.2,22.0,2008
24844,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.dealthemovie.com/,11115.0,tt0446676,en,Deal,As an ex-gambler teaches a hot-shot college ki...,...,0.0,85.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Deal (2008),False,5.2,22.0,2008
44826,False,"{'id': 34055, 'name': 'Pokémon Collection', 'p...",0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.pokemon.com/us/movies/movie-pokemon...,12600.0,tt0287635,ja,劇場版ポケットモンスター セレビィ 時を越えた遭遇（であい）,"All your favorite Pokémon characters are back,...",...,28023563.0,75.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Pokémon 4Ever: Celebi - Voice of the Forest (2...,False,5.7,82.0,2001
5535,False,"{'id': 34055, 'name': 'Pokémon Collection', 'p...",0,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.pokemon.com/us/movies/movie-pokemon...,12600.0,tt0287635,ja,劇場版ポケットモンスター セレビィ 時を越えた遭遇（であい）,"All your favorite Pokémon characters are back,...",...,28023563.0,75.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Pokémon 4Ever: Celebi - Voice of the Forest (2...,False,5.7,82.0,2001
11342,False,NaN,2500,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,13209.0,tt0499537,fa,Offside,"Since women are banned from soccer matches, Ir...",...,0.0,93.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,NaN,Offside (2006),False,6.7,27.0,2006
15765,False,NaN,2500,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,13209.0,tt0499537,fa,Offside,"Since women are banned from soccer matches, Ir...",...,0.0,93.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,NaN,Offside (2006),False,6.7,27.0,2006
10419,False,NaN,1600000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.bubblethefilm.com/,14788.0,tt0454792,en,Bubble,Set against the backdrop of a decaying Midwest...,...,0.0,73.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Bubble (2005),False,6.4,36.0,2005
12066,False,NaN,1600000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.bubblethefilm.com/,14788.0,tt0454792,en,Bubble,Set against the backdrop of a decaying Midwest...,...,0.0,73.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Bubble (2005),False,6.4,36.0,2005
5130,False,NaN,26000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",NaN,15028.0,tt0157472,en,Clockstoppers,"Until now, Zak Gibbs' greatest challenge has b...",...,38793283.0,94.0,"[{'iso_639_1': 'cs', 'name': 'Český'}, {'iso_6...",Released,"The adventure of a lifetime, in a few mere sec...",Clockstoppers (2002),False,4.9,89.0,2002
33743,False,NaN,26000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",NaN,15028.0,tt0157472,en,Clockstoppers,"Until now, Zak Gibbs' greatest challenge has b...",...,38793283.0,94.0,"[{'iso_639_1': 'cs', 'name': 'Český'}, {'iso_6...",Released,"The adventure of a lifetime, in a few mere sec...",Clockstoppers (2002),False,4.9,90.0,2002
22151,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 27, 'nam...",http://www.daysofdarknessthemovie.com/,18440.0,tt0499456,en,Days of Darkness,When a comet strikes Earth and kicks up a clou...,...,0.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Days of Darkness (2007),False,5.0,5.0,2007
14000,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 27, 'nam...",http://www.daysofdarknessthemovie.com/,18440.0,tt0499456,en,Days of Darkness,When a comet strikes Earth and kicks up a clou...,...,0.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Days of Darkness (2007),False,5.0,5.0,2007
949,False,NaN,4,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,22649.0,tt0022879,en,A Farewell to Arms,British nurse Catherine Barkley (Helen Hayes) ...,...,25.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Every woman who has loved will understand,A Farewell to Arms (1932),False,6.2,29.0,1932
15074,False,NaN,4,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,22649.0,tt0022879,en,A Farewell to Arms,British nurse Catherine Barkley (Helen Hayes) ...,...,25.0,89.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Every woman who has loved will understand,A Farewell to Arms (1932),False,6.2,29.0,1932
8068,False,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",NaN,23305.0,tt0295682,en,The Warrior,"In feudal India, a warrior (Khan) who renounce...",...,0.0,86.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,The Warrior (2001),False,6.3,15.0,2001
9327,False,NaN,0,"[{'id': 12, 'name': 'Adventure'}, {'id': 16, '...",NaN,23305.0,tt0295682,en,The Warrior,"In feudal India, a warrior (Khan) who renounce...",...,0.0,86.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,The Warrior (2001),False,6.3,15.0,2001
23044,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,25541.0,tt1327820,da,Broderskab,Former Danish servicemen Lars and Jimmy are th...,...,0.0,90.0,"[{'iso_639_1': 'da', 'name': 'Dansk'}]",Released,NaN,Brotherhood (2009),False,7.1,21.0,2009
17229,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,25541.0,tt1327820,da,Broderskab,Former Danish servicemen Lars and Jimmy are th...,...,0.0,90.0,"[{'iso_639_1': 'da', 'name': 'Dansk'}]",Released,NaN,Brotherhood (2009),False,7.1,21.0,2009
15702,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",NaN,42495.0,tt0067306,en,King Lear,"King Lear, old and tired, divides his kingdom ...",...,0.0,137.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Rumored,NaN,King Lear (1971),False,8.0,3.0,1971
29374,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10769, 'n...",NaN,42495.0,tt0067306,en,King Lear,"King Lear, old and tired, divides his kingdom ...",...,0.0,137.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Rumored,NaN,King Lear (1971),False,8.0,3.0,1971
26625,False,NaN,10000000,"[{'id': 18, 'name': 'Drama'}, {'id': 27, 'name...",NaN,69234.0,tt0100361,en,The Phantom of the Opera,Count de Chagnie has discovered Christine's si...,...,0.0,168.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,The Phantom of the Opera (1990),False,5.0,3.0,1990
9576,False,NaN,10000000,"[{'id': 18, 'name': 'Drama'}, {'id': 27, 'name...",NaN,69234.0,tt0100361,en,The Phantom of the Opera,Count de Chagnie has discovered Christine's si...,...,0.0,168.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,The Phantom of the Opera (1990),False,5.0,3.0,1990
11155,False,NaN,40000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",NaN,77221.0,tt1701210,en,Black Gold,"On the Arabian Peninsula in the 1930s, two war...",...,5446000.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Black Gold (2011),False,5.9,77.0,2011
20843,False,NaN,40000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",NaN,77221.0,tt1701210,en,Black Gold,"On the Arabian Peninsula in the 1930s, two war...",...,5446000.0,130.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Black Gold (2011),False,5.9,77.0,2011
21116,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,84198.0,tt1736049,en,A Place at the Table,"Using personal stories, this powerful document...",...,0.0,84.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,One Nation. Underfed.,A Place at the Table (2012),False,6.9,7.0,2012
2564,False,NaN,0,"[{'id': 99, 'name': 'Documentary'}]",NaN,84198.0,tt1736049,en,A Place at the Table,"Using personal stories, this powerful document...",...,0.0,84.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,One Nation. Underfed.,A Place at the Table (2012),False,6.9,7.0,2012
40276,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,97995.0,tt0127834,en,Seven Years Bad Luck,"After breaking a mirror in his home, superstit...",...,0.0,62.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Seven Years Bad Luck (1921),False,5.6,4.0,1921
13946,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}]",NaN,97995.0,tt0127834,en,Seven Years Bad Luck,"After breaking a mirror in his home, superstit...",...,0.0,62.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Seven Years Bad Luck (1921),False,5.6,4.0,1921
16167,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,99080.0,tt0022537,en,The Viking,"Originally called White Thunder, American prod...",...,0.0,70.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Actually produced during the Great Newfoundlan...,The Viking (1931),False,0.0,0.0,1931
38871,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,99080.0,tt0022537,en,The Viking,"Originally called White Thunder, American prod...",...,0.0,70.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Actually produced during the Great Newfoundlan...,The Viking (1931),False,0.0,0.0,1931
1465,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,105045.0,tt0111613,de,Das Versprechen,"East-Berlin, 1961, shortly after the erection ...",...,0.0,115.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,"A love, a hope, a wall.",The Promise (1995),False,5.0,1.0,1995
676,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,105045.0,tt0111613,de,Das Versprechen,"East-Berlin, 1961, shortly after the erection ...",...,0.0,115.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,"A love, a hope, a wall.",The Promise (1995),False,5.0,1.0,1995
20899,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,109962.0,tt0082992,en,Rich and Famous,Two literary women compete for 20 years: one w...,...,0.0,115.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"From the very beginning, they knew they'd be f...",Rich and Famous (1981),False,4.9,7.0,1981
5710,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,109962.0,tt0082992,en,Rich and Famous,Two literary women compete for 20 years: one w...,...,0.0,115.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"From the very beginning, they knew they'd be f...",Rich and Famous (1981),False,4.9,7.0,1981
4356,False,NaN,3512454,"[{'id': 18, 'name': 'Drama'}]",NaN,110428.0,tt2018086,fr,Camille Claudel 1915,"Winter, 1915. Confined by her family to an asy...",...,115860.0,95.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,NaN,Camille Claudel 1915 (2013),False,7.0,20.0,2013
23534,False,NaN,3512454,"[{'id': 18, 'name': 'Drama'}]",NaN,110428.0,tt2018086,fr,Camille Claudel 1915,"Winter, 1915. Confined by her family to an asy...",...,115860.0,95.0,"[{'iso_639_1': 'fr', 'name': 'Français'}]",Released,NaN,Camille Claudel 1915 (2013),False,7.0,20.0,2013
21165,False,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",NaN,119916.0,tt0080000,en,The Tempest,"Prospero, the true Duke of Milan is now living...",...,0.0,123.0,[],Released,NaN,The Tempest (1980),False,0.0,0.0,1980
19890,False,NaN,0,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",NaN,119916.0,tt0080000,en,The Tempest,"Prospero, the true Duke of Milan is now living...",...,0.0,123.0,[],Released,NaN,The Tempest (1980),False,0.0,0.0,1980
30001,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,132641.0,tt0046468,ja,Tsuma,"Ten years into a marriage, the wife is disappo...",...,0.0,89.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Wife (1953),False,0.0,0.0,1953
838,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,132641.0,tt0046468,ja,Tsuma,"Ten years into a marriage, the wife is disappo...",...,0.0,89.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,NaN,Wife (1953),False,0.0,0.0,1953
13261,False,NaN,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",NaN,141971.0,tt1180333,fi,Blackout,Recovering from a nail gun shot to the head an...,...,0.0,108.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,Which one is the first to return - memory or t...,Blackout (2008),False,6.7,3.0,2008
13375,False,NaN,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",NaN,141971.0,tt1180333,fi,Blackout,Recovering from a nail gun shot to the head an...,...,0.0,108.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,Which one is the first to return - memory or t...,Blackout (2008),False,6.7,3.0,2008
16764,False,NaN,0,"[{'id': 53, 'name': 'Thriller'}, {'id': 9648, ...",NaN,141971.0,tt1180333,fi,Blackout,Recovering from a nail gun shot to the head an...,...,0.0,108.0,"[{'iso_639_1': 'fi', 'name': 'suomi'}]",Released,Which one is the first to return - memory or t...,Blackout (2008),False,6.7,3.0,2008
21854,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",NaN,152795.0,tt1821641,en,The Congress,More than two decades after catapulting to sta...,...,455815.0,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,The Congress (2013),False,6.4,165.0,2013
19925,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",NaN,152795.0,tt1821641,en,The Congress,More than two decades after catapulting to sta...,...,455815.0,122.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,The Congress (2013),False,6.4,165.0,2013
13220,False,"{'id': 158365, 'name': 'Why We Fight', 'poster...",0,"[{'id': 99, 'name': 'Documentary'}]",NaN,159849.0,tt0173769,en,Why We Fight: Divide and Conquer,"The third film of Frank Capra's 'Why We Fight""...",...,0.0,57.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Why We Fight: Divide and Conquer (1943),False,5.0,1.0,1943
35798,False,"{'id': 158365, 'name': 'Why We Fight', 'poster...",0,"[{'id': 99, 'name': 'Documentary'}]",NaN,159849.0,tt0173769,en,Why We Fight: Divide and Conquer,"The third film of Frank Capra's 'Why We Fight""...",...,0.0,57.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Why We Fight: Divide and Conquer (1943),False,5.0,1.0,1943
13603,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,168538.0,tt0084387,en,Nana,"In Zola's Paris, an ingenue arrives at a tony ...",...,0.0,92.0,[],Released,NaN,"Nana, the True Key of Pleasure (1983)",False,4.7,3.0,1983
28860,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,168538.0,tt0084387,en,Nana,"In Zola's Paris, an ingenue arrives at a tony ...",...,0.0,92.0,[],Released,NaN,"Nana, the True Key of Pleasure (1983)",False,4.7,3.0,1983
24164,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,265189.0,tt2121382,sv,Turist,"While holidaying in the French Alps, a Swedish...",...,1359497.0,118.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,NaN,Force Majeure (2014),False,6.8,255.0,2014
45265,False,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,265189.0,tt2121382,sv,Turist,"While holidaying in the French Alps, a Swedish...",...,1359497.0,118.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,NaN,Force Majeure (2014),False,6.8,255.0,2014
33184,False,NaN,980000,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",NaN,298721.0,tt2818654,th,รักที่ขอนแก่น,"In a hospital, ten soldiers are being treated ...",...,0.0,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Cemetery of Splendour (2015),False,4.4,50.0,2015
40040,False,NaN,980000,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",NaN,298721.0,tt2818654,th,รักที่ขอนแก่น,"In a hospital, ten soldiers are being treated ...",...,0.0,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Cemetery of Splendour (2015),False,4.4,50.0,2015

In [41]:
meta = meta.drop_duplicates(subset=['id'])

In [42]:
meta.duplicated(subset=['id']).sum()

np.int64(0)

In [43]:
meta.shape

(45433, 25)

In [44]:
movies = meta.merge(credits, on='id').merge(keywords, on='id')

In [45]:
movies

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,status,tagline,title,video,vote_average,vote_count,year,cast,crew,keywords
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862.0,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,Released,NaN,Toy Story (1995),False,7.7,5415.0,1995,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844.0,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,Released,Roll the dice and unleash the excitement!,Jumanji (1995),False,6.9,2413.0,1995,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1..."
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602.0,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men (1995),False,6.5,92.0,1995,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392..."
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357.0,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,Released,Friends are the people who let you be yourself...,Waiting to Exhale (1995),False,6.1,34.0,1995,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':..."
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862.0,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II (1995),False,5.7,173.0,1995,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45427,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050.0,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,Released,Rising and falling between a man and woman,Subdue (0),False,4.0,1.0,0,"[{'cast_id': 0, 'character': '', 'credit_id': ...","[{'credit_id': '5894a97d925141426c00818c', 'de...","[{'id': 10703, 'name': 'tragic love'}]"
45428,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109.0,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,Released,NaN,Century of Birthing (2011),False,9.0,3.0,2011,"[{'cast_id': 1002, 'character': 'Sister Angela...","[{'credit_id': '52fe4af1c3a36847f81e9b15', 'de...","[{'id': 2679, 'name': 'artist'}, {'id': 14531,..."
45429,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758.0,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,Released,A deadly game of wits.,Betrayal (2003),False,3.8,6.0,2003,"[{'cast_id': 6, 'character': 'Emily Shaw', 'cr...","[{'credit_id': '52fe4776c3a368484e0c8387', 'de...",[]
45430,False,NaN,0,[],NaN,227506.0,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,Released,NaN,Satan Triumphant (1917),False,0.0,0.0,1917,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '533bccebc3a36844cf0011a7', 'de...",[]
45431,False,NaN,0,[],NaN,461257.0,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,Released,NaN,Queerama (2017),False,0.0,0.0,2017,[],"[{'credit_id': '593e676c92514105b702e68e', 'de...",[]

In [46]:
movies.shape

(45432, 28)

In [47]:
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'year', 'cast', 'crew', 'keywords'],
      dtype='object')

In [48]:
movies["status"]

0        Released
1        Released
2        Released
3        Released
4        Released
           ...
45427    Released
45428    Released
45429    Released
45430    Released
45431    Released
Name: status, Length: 45432, dtype: object

In [49]:
movies["status"].value_counts()

status
Released           44984
Rumored              229
Post Production       98
In Production         20
Planned               15
Canceled               2
Name: count, dtype: int64

In [50]:
movies = movies[movies['status'] == 'Released']

In [51]:
movies.shape

(44984, 28)

In [52]:
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'year', 'cast', 'crew', 'keywords'],
      dtype='object')

In [53]:
movies["vote_count"].describe()

count    44984.000000
mean       110.930575
std        493.787335
min          0.000000
25%          3.000000
50%         10.000000
75%         35.000000
max      14075.000000
Name: vote_count, dtype: float64

In [54]:
movies = movies[movies['vote_count'] >= 34]

In [55]:
movies.shape

(11489, 28)

In [56]:
# Constants based on your descriptive stats
m = 34
C = movies['vote_average'].mean()

def weighted_rating(x, m=m, C=C):
    v = x['vote_count']
    R = x['vote_average']
    # Calculation based on the IMDB formula
    return (v/(v+m) * R) + (m/(v+m) * C)

In [57]:
# Create the score column
movies['new_vote_avg'] = movies.apply(weighted_rating, axis=1)

In [58]:
movies["new_vote_avg"].describe()

count    11489.000000
mean         6.341057
std          0.687137
min          3.128329
25%          5.887290
50%          6.366901
75%          6.803557
max          8.963913
Name: new_vote_avg, dtype: float64

In [59]:
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'year', 'cast', 'crew', 'keywords',
       'new_vote_avg'],
      dtype='object')

In [60]:
movies["runtime"]

0         81.0
1        104.0
2        101.0
3        127.0
4        106.0
         ...
45314     90.0
45339     83.0
45346     83.0
45403      4.0
45407    101.0
Name: runtime, Length: 11489, dtype: float64

In [61]:
movies = movies[movies["runtime"]>50]

In [62]:
movies.shape

(11229, 29)

In [63]:
movies["runtime"].describe()

count    11229.000000
mean       106.163861
std         27.297554
min         51.000000
25%         92.000000
50%        101.000000
75%        115.000000
max        877.000000
Name: runtime, dtype: float64

In [64]:
movies.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'year', 'cast', 'crew', 'keywords',
       'new_vote_avg'],
      dtype='object')

In [65]:
movies = movies[['genres', 'id', 'overview', 'title', 'cast', 'crew', 'keywords', 'vote_count', 'new_vote_avg']]

In [66]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",5415.0,7.691378
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",2413.0,6.891917
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",92.0,6.450950
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",34.0,6.209113
4,"[{'id': 35, 'name': 'Comedy'}]",11862.0,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995),"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",173.0,5.801544
...,...,...,...,...,...,...,...,...,...
45309,"[{'id': 35, 'name': 'Comedy'}]",248705.0,"Stuck in the corridors of time, Godefroy de Mo...",The Visitors: Bastille Day (2016),"[{'cast_id': 2, 'character': 'Le comte Godefro...","[{'credit_id': '52fe4f37c3a36847f82c5efb', 'de...","[{'id': 2652, 'name': 'nazis'}, {'id': 3098, '...",167.0,4.392138
45314,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",44918.0,On the 100th anniversary of the original voyag...,Titanic 2 (2010),"[{'cast_id': 1, 'character': 'Hayden Walsh', '...","[{'credit_id': '52fe46a3c3a36847f810a04b', 'de...","[{'id': 9937, 'name': 'suspense'}]",55.0,4.514828
45339,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",426272.0,Ray is a fledgling entrepreneur who specialize...,Take Me (2017),"[{'cast_id': 1, 'character': 'Anna St. Blair',...","[{'credit_id': '582c3222c3a36872c0006604', 'de...",[],38.0,6.150273
45346,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",432789.0,"Burned by a bad breakup, a struggling New York...",The Incredible Jessica James (2017),"[{'cast_id': 6, 'character': 'Jessica James', ...","[{'credit_id': '586a688dc3a3680f4e017d65', 'de...",[],37.0,6.256615
45407,"[{'id': 35, 'name': 'Comedy'}]",14008.0,Hyperactive teenager Kelly is enrolled into a ...,Cadet Kelly (2002),"[{'cast_id': 1, 'character': 'Kelly Collins', ...","[{'credit_id': '52fe45c29251416c75061803', 'de...","[{'id': 171803, 'name': 'military school'}]",145.0,5.412400

In [67]:
movies.shape

(11229, 9)

In [68]:
movies.isnull().sum()

genres           0
id               0
overview        18
title            0
cast             0
crew             0
keywords         0
vote_count       0
new_vote_avg     0
dtype: int64

In [69]:
movies['overview'] = movies['overview'].fillna('')

In [70]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",5415.0,7.691378
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",2413.0,6.891917
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",92.0,6.450950
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",34.0,6.209113
4,"[{'id': 35, 'name': 'Comedy'}]",11862.0,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995),"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",173.0,5.801544
...,...,...,...,...,...,...,...,...,...
45309,"[{'id': 35, 'name': 'Comedy'}]",248705.0,"Stuck in the corridors of time, Godefroy de Mo...",The Visitors: Bastille Day (2016),"[{'cast_id': 2, 'character': 'Le comte Godefro...","[{'credit_id': '52fe4f37c3a36847f82c5efb', 'de...","[{'id': 2652, 'name': 'nazis'}, {'id': 3098, '...",167.0,4.392138
45314,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",44918.0,On the 100th anniversary of the original voyag...,Titanic 2 (2010),"[{'cast_id': 1, 'character': 'Hayden Walsh', '...","[{'credit_id': '52fe46a3c3a36847f810a04b', 'de...","[{'id': 9937, 'name': 'suspense'}]",55.0,4.514828
45339,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",426272.0,Ray is a fledgling entrepreneur who specialize...,Take Me (2017),"[{'cast_id': 1, 'character': 'Anna St. Blair',...","[{'credit_id': '582c3222c3a36872c0006604', 'de...",[],38.0,6.150273
45346,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",432789.0,"Burned by a bad breakup, a struggling New York...",The Incredible Jessica James (2017),"[{'cast_id': 6, 'character': 'Jessica James', ...","[{'credit_id': '586a688dc3a3680f4e017d65', 'de...",[],37.0,6.256615
45407,"[{'id': 35, 'name': 'Comedy'}]",14008.0,Hyperactive teenager Kelly is enrolled into a ...,Cadet Kelly (2002),"[{'cast_id': 1, 'character': 'Kelly Collins', ...","[{'credit_id': '52fe45c29251416c75061803', 'de...","[{'id': 171803, 'name': 'military school'}]",145.0,5.412400

In [71]:
# Check for empty lists in JSON columns
for col in ['genres', 'cast', 'crew', 'keywords']:
    empty_count = movies[col].apply(lambda x: x == [] or x == "[]").sum()
    print(f"Movies with empty {col}: {empty_count}")

Movies with empty genres: 8
Movies with empty cast: 17
Movies with empty crew: 9
Movies with empty keywords: 1041

In [72]:
movies = movies[movies['cast'].apply(lambda x: len(x) > 0 and x != '[]')]
movies = movies[movies['crew'].apply(lambda x: len(x) > 0 and x != '[]')]
movies = movies[movies['genres'].apply(lambda x: len(x) > 0 and x != '[]')]

In [73]:
# Check for empty lists in JSON columns
for col in ['genres', 'cast', 'crew', 'keywords']:
    empty_count = movies[movies[col].apply(lambda x: x == [] or x == "[]")].shape[0]
    print(f"Movies with empty {col}: {empty_count}")

Movies with empty genres: 0
Movies with empty cast: 0
Movies with empty crew: 0
Movies with empty keywords: 1029

In [74]:
movies.shape

(11198, 9)

In [75]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",5415.0,7.691378
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",2413.0,6.891917
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",92.0,6.450950
3,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",34.0,6.209113
4,"[{'id': 35, 'name': 'Comedy'}]",11862.0,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995),"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",173.0,5.801544
...,...,...,...,...,...,...,...,...,...
45309,"[{'id': 35, 'name': 'Comedy'}]",248705.0,"Stuck in the corridors of time, Godefroy de Mo...",The Visitors: Bastille Day (2016),"[{'cast_id': 2, 'character': 'Le comte Godefro...","[{'credit_id': '52fe4f37c3a36847f82c5efb', 'de...","[{'id': 2652, 'name': 'nazis'}, {'id': 3098, '...",167.0,4.392138
45314,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",44918.0,On the 100th anniversary of the original voyag...,Titanic 2 (2010),"[{'cast_id': 1, 'character': 'Hayden Walsh', '...","[{'credit_id': '52fe46a3c3a36847f810a04b', 'de...","[{'id': 9937, 'name': 'suspense'}]",55.0,4.514828
45339,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",426272.0,Ray is a fledgling entrepreneur who specialize...,Take Me (2017),"[{'cast_id': 1, 'character': 'Anna St. Blair',...","[{'credit_id': '582c3222c3a36872c0006604', 'de...",[],38.0,6.150273
45346,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",432789.0,"Burned by a bad breakup, a struggling New York...",The Incredible Jessica James (2017),"[{'cast_id': 6, 'character': 'Jessica James', ...","[{'credit_id': '586a688dc3a3680f4e017d65', 'de...",[],37.0,6.256615
45407,"[{'id': 35, 'name': 'Comedy'}]",14008.0,Hyperactive teenager Kelly is enrolled into a ...,Cadet Kelly (2002),"[{'cast_id': 1, 'character': 'Kelly Collins', ...","[{'credit_id': '52fe45c29251416c75061803', 'de...","[{'id': 171803, 'name': 'military school'}]",145.0,5.412400

In [76]:
movies.iloc[0].genres

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [77]:
import ast

def convert(obj):
    L = []

    for i in ast.literal_eval(obj):
        L.append(i['name'])

    return L

In [78]:
movies["genres"] = movies["genres"].apply(convert)

In [79]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[Animation, Comedy, Family]",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...",5415.0,7.691378
1,"[Adventure, Fantasy, Family]",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[{'id': 10090, 'name': 'board game'}, {'id': 1...",2413.0,6.891917
2,"[Romance, Comedy]",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[{'id': 1495, 'name': 'fishing'}, {'id': 12392...",92.0,6.450950
3,"[Comedy, Drama, Romance]",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[{'id': 818, 'name': 'based on novel'}, {'id':...",34.0,6.209113
4,[Comedy],11862.0,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995),"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...",173.0,5.801544
...,...,...,...,...,...,...,...,...,...
45309,[Comedy],248705.0,"Stuck in the corridors of time, Godefroy de Mo...",The Visitors: Bastille Day (2016),"[{'cast_id': 2, 'character': 'Le comte Godefro...","[{'credit_id': '52fe4f37c3a36847f82c5efb', 'de...","[{'id': 2652, 'name': 'nazis'}, {'id': 3098, '...",167.0,4.392138
45314,"[Action, Adventure, Thriller]",44918.0,On the 100th anniversary of the original voyag...,Titanic 2 (2010),"[{'cast_id': 1, 'character': 'Hayden Walsh', '...","[{'credit_id': '52fe46a3c3a36847f810a04b', 'de...","[{'id': 9937, 'name': 'suspense'}]",55.0,4.514828
45339,"[Comedy, Crime]",426272.0,Ray is a fledgling entrepreneur who specialize...,Take Me (2017),"[{'cast_id': 1, 'character': 'Anna St. Blair',...","[{'credit_id': '582c3222c3a36872c0006604', 'de...",[],38.0,6.150273
45346,"[Romance, Comedy]",432789.0,"Burned by a bad breakup, a struggling New York...",The Incredible Jessica James (2017),"[{'cast_id': 6, 'character': 'Jessica James', ...","[{'credit_id': '586a688dc3a3680f4e017d65', 'de...",[],37.0,6.256615
45407,[Comedy],14008.0,Hyperactive teenager Kelly is enrolled into a ...,Cadet Kelly (2002),"[{'cast_id': 1, 'character': 'Kelly Collins', ...","[{'credit_id': '52fe45c29251416c75061803', 'de...","[{'id': 171803, 'name': 'military school'}]",145.0,5.412400

In [80]:
movies.iloc[0].keywords

"[{'id': 931, 'name': 'jealousy'}, {'id': 4290, 'name': 'toy'}, {'id': 5202, 'name': 'boy'}, {'id': 6054, 'name': 'friendship'}, {'id': 9713, 'name': 'friends'}, {'id': 9823, 'name': 'rivalry'}, {'id': 165503, 'name': 'boy next door'}, {'id': 170722, 'name': 'new toy'}, {'id': 187065, 'name': 'toy comes to life'}]"

In [81]:
movies["keywords"] = movies["keywords"].apply(convert)

In [82]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[Animation, Comedy, Family]",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[jealousy, toy, boy, friendship, friends, riva...",5415.0,7.691378
1,"[Adventure, Fantasy, Family]",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[board game, disappearance, based on children'...",2413.0,6.891917
2,"[Romance, Comedy]",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[fishing, best friend, duringcreditsstinger, o...",92.0,6.450950
3,"[Comedy, Drama, Romance]",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...","[based on novel, interracial relationship, sin...",34.0,6.209113
4,[Comedy],11862.0,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995),"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[baby, midlife crisis, confidence, aging, daug...",173.0,5.801544
...,...,...,...,...,...,...,...,...,...
45309,[Comedy],248705.0,"Stuck in the corridors of time, Godefroy de Mo...",The Visitors: Bastille Day (2016),"[{'cast_id': 2, 'character': 'Le comte Godefro...","[{'credit_id': '52fe4f37c3a36847f82c5efb', 'de...","[nazis, castle, time travel, robespierre]",167.0,4.392138
45314,"[Action, Adventure, Thriller]",44918.0,On the 100th anniversary of the original voyag...,Titanic 2 (2010),"[{'cast_id': 1, 'character': 'Hayden Walsh', '...","[{'credit_id': '52fe46a3c3a36847f810a04b', 'de...",[suspense],55.0,4.514828
45339,"[Comedy, Crime]",426272.0,Ray is a fledgling entrepreneur who specialize...,Take Me (2017),"[{'cast_id': 1, 'character': 'Anna St. Blair',...","[{'credit_id': '582c3222c3a36872c0006604', 'de...",[],38.0,6.150273
45346,"[Romance, Comedy]",432789.0,"Burned by a bad breakup, a struggling New York...",The Incredible Jessica James (2017),"[{'cast_id': 6, 'character': 'Jessica James', ...","[{'credit_id': '586a688dc3a3680f4e017d65', 'de...",[],37.0,6.256615
45407,[Comedy],14008.0,Hyperactive teenager Kelly is enrolled into a ...,Cadet Kelly (2002),"[{'cast_id': 1, 'character': 'Kelly Collins', ...","[{'credit_id': '52fe45c29251416c75061803', 'de...",[military school],145.0,5.412400

In [83]:
movies.iloc[0].cast

"[{'cast_id': 14, 'character': 'Woody (voice)', 'credit_id': '52fe4284c3a36847f8024f95', 'gender': 2, 'id': 31, 'name': 'Tom Hanks', 'order': 0, 'profile_path': '/pQFoyx7rp09CJTAb932F2g8Nlho.jpg'}, {'cast_id': 15, 'character': 'Buzz Lightyear (voice)', 'credit_id': '52fe4284c3a36847f8024f99', 'gender': 2, 'id': 12898, 'name': 'Tim Allen', 'order': 1, 'profile_path': '/uX2xVf6pMmPepxnvFWyBtjexzgY.jpg'}, {'cast_id': 16, 'character': 'Mr. Potato Head (voice)', 'credit_id': '52fe4284c3a36847f8024f9d', 'gender': 2, 'id': 7167, 'name': 'Don Rickles', 'order': 2, 'profile_path': '/h5BcaDMPRVLHLDzbQavec4xfSdt.jpg'}, {'cast_id': 17, 'character': 'Slinky Dog (voice)', 'credit_id': '52fe4284c3a36847f8024fa1', 'gender': 2, 'id': 12899, 'name': 'Jim Varney', 'order': 3, 'profile_path': '/eIo2jVVXYgjDtaHoF19Ll9vtW7h.jpg'}, {'cast_id': 18, 'character': 'Rex (voice)', 'credit_id': '52fe4284c3a36847f8024fa5', 'gender': 2, 'id': 12900, 'name': 'Wallace Shawn', 'order': 4, 'profile_path': '/oGE6JqPP2xH4tNORKNqxbNPYi7u.jpg'}, {'cast_id': 19, 'character': 'Hamm (voice)', 'credit_id': '52fe4284c3a36847f8024fa9', 'gender': 2, 'id': 7907, 'name': 'John Ratzenberger', 'order': 5, 'profile_path': '/yGechiKWL6TJDfVE2KPSJYqdMsY.jpg'}, {'cast_id': 20, 'character': 'Bo Peep (voice)', 'credit_id': '52fe4284c3a36847f8024fad', 'gender': 1, 'id': 8873, 'name': 'Annie Potts', 'order': 6, 'profile_path': '/eryXT84RL41jHSJcMy4kS3u9y6w.jpg'}, {'cast_id': 26, 'character': 'Andy (voice)', 'credit_id': '52fe4284c3a36847f8024fc1', 'gender': 0, 'id': 1116442, 'name': 'John Morris', 'order': 7, 'profile_path': '/vYGyvK4LzeaUCoNSHtsuqJUY15M.jpg'}, {'cast_id': 22, 'character': 'Sid (voice)', 'credit_id': '52fe4284c3a36847f8024fb1', 'gender': 2, 'id': 12901, 'name': 'Erik von Detten', 'order': 8, 'profile_path': '/twnF1ZaJ1FUNUuo6xLXwcxjayBE.jpg'}, {'cast_id': 23, 'character': 'Mrs. Davis (voice)', 'credit_id': '52fe4284c3a36847f8024fb5', 'gender': 1, 'id': 12133, 'name': 'Laurie Metcalf', 'order': 9, 'profile_path': '/unMMIT60eoBM2sN2nyR7EZ2BvvD.jpg'}, {'cast_id': 24, 'character': 'Sergeant (voice)', 'credit_id': '52fe4284c3a36847f8024fb9', 'gender': 2, 'id': 8655, 'name': 'R. Lee Ermey', 'order': 10, 'profile_path': '/r8GBqFBjypLUP9VVqDqfZ7wYbSs.jpg'}, {'cast_id': 25, 'character': 'Hannah (voice)', 'credit_id': '52fe4284c3a36847f8024fbd', 'gender': 1, 'id': 12903, 'name': 'Sarah Freeman', 'order': 11, 'profile_path': None}, {'cast_id': 27, 'character': 'TV Announcer (voice)', 'credit_id': '52fe4284c3a36847f8024fc5', 'gender': 2, 'id': 37221, 'name': 'Penn Jillette', 'order': 12, 'profile_path': '/zmAaXUdx12NRsssgHbk1T31j2x9.jpg'}]"

In [84]:
def convert3(obj):
    cnt = 0
    L = []

    for i in ast.literal_eval(obj):
        if cnt!=3:
            L.append(i['name'])
            cnt+=1
        else:
            break

    return L

In [85]:
movies["cast"] = movies["cast"].apply(convert3)

In [86]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg
0,"[Animation, Comedy, Family]",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[Tom Hanks, Tim Allen, Don Rickles]","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[jealousy, toy, boy, friendship, friends, riva...",5415.0,7.691378
1,"[Adventure, Fantasy, Family]",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[Robin Williams, Jonathan Hyde, Kirsten Dunst]","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...","[board game, disappearance, based on children'...",2413.0,6.891917
2,"[Romance, Comedy]",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[Walter Matthau, Jack Lemmon, Ann-Margret]","[{'credit_id': '52fe466a9251416c75077a89', 'de...","[fishing, best friend, duringcreditsstinger, o...",92.0,6.450950
3,"[Comedy, Drama, Romance]",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[Whitney Houston, Angela Bassett, Loretta Devine]","[{'credit_id': '52fe44779251416c91011acb', 'de...","[based on novel, interracial relationship, sin...",34.0,6.209113
4,[Comedy],11862.0,Just when George Banks has recovered from his ...,Father of the Bride Part II (1995),"[Steve Martin, Diane Keaton, Martin Short]","[{'credit_id': '52fe44959251416c75039ed7', 'de...","[baby, midlife crisis, confidence, aging, daug...",173.0,5.801544
...,...,...,...,...,...,...,...,...,...
45309,[Comedy],248705.0,"Stuck in the corridors of time, Godefroy de Mo...",The Visitors: Bastille Day (2016),"[Jean Reno, Christian Clavier, Franck Dubosc]","[{'credit_id': '52fe4f37c3a36847f82c5efb', 'de...","[nazis, castle, time travel, robespierre]",167.0,4.392138
45314,"[Action, Adventure, Thriller]",44918.0,On the 100th anniversary of the original voyag...,Titanic 2 (2010),"[Shane Van Dyke, Marie Westbrook, Bruce Davison]","[{'credit_id': '52fe46a3c3a36847f810a04b', 'de...",[suspense],55.0,4.514828
45339,"[Comedy, Crime]",426272.0,Ray is a fledgling entrepreneur who specialize...,Take Me (2017),"[Taylor Schilling, Pat Healy, Alycia Delmore]","[{'credit_id': '582c3222c3a36872c0006604', 'de...",[],38.0,6.150273
45346,"[Romance, Comedy]",432789.0,"Burned by a bad breakup, a struggling New York...",The Incredible Jessica James (2017),"[Jessica Williams, Chris O'Dowd, Keith Stanfield]","[{'credit_id': '586a688dc3a3680f4e017d65', 'de...",[],37.0,6.256615
45407,[Comedy],14008.0,Hyperactive teenager Kelly is enrolled into a ...,Cadet Kelly (2002),"[Hilary Duff, Christy Carlson Romano, Gary Cole]","[{'credit_id': '52fe45c29251416c75061803', 'de...",[military school],145.0,5.412400

In [87]:
movies.iloc[2].crew

"[{'credit_id': '52fe466a9251416c75077a89', 'department': 'Directing', 'gender': 2, 'id': 26502, 'job': 'Director', 'name': 'Howard Deutch', 'profile_path': '/68Vae1HkU1NxQZ6KEmuxIpno7c9.jpg'}, {'credit_id': '52fe466b9251416c75077aa3', 'department': 'Writing', 'gender': 2, 'id': 16837, 'job': 'Characters', 'name': 'Mark Steven Johnson', 'profile_path': '/6trChNn3o2bi4i2ipgMEAytwmZp.jpg'}, {'credit_id': '52fe466b9251416c75077aa9', 'department': 'Writing', 'gender': 2, 'id': 16837, 'job': 'Writer', 'name': 'Mark Steven Johnson', 'profile_path': '/6trChNn3o2bi4i2ipgMEAytwmZp.jpg'}, {'credit_id': '5675eb4b92514179dd003933', 'department': 'Crew', 'gender': 2, 'id': 1551320, 'job': 'Sound Recordist', 'name': 'Jack Keller', 'profile_path': None}]"

In [88]:
def fetch_director(obj):
    L = []

    for i in ast.literal_eval(obj):
        if(i["job"]=="Director"):
            L.append(i["name"])

    return L

In [89]:
movies["crew"] = movies["crew"].apply(fetch_director)

In [90]:
movies['director'] = movies['crew'].apply(lambda x: " & ".join(x) if x else "Unknown")

In [91]:
movies.head(4)

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg,director
0,"[Animation, Comedy, Family]",862.0,"Led by Woody, Andy's toys live happily in his ...",Toy Story (1995),"[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter],"[jealousy, toy, boy, friendship, friends, riva...",5415.0,7.691378,John Lasseter
1,"[Adventure, Fantasy, Family]",8844.0,When siblings Judy and Peter discover an encha...,Jumanji (1995),"[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston],"[board game, disappearance, based on children'...",2413.0,6.891917,Joe Johnston
2,"[Romance, Comedy]",15602.0,A family wedding reignites the ancient feud be...,Grumpier Old Men (1995),"[Walter Matthau, Jack Lemmon, Ann-Margret]",[Howard Deutch],"[fishing, best friend, duringcreditsstinger, o...",92.0,6.450950,Howard Deutch
3,"[Comedy, Drama, Romance]",31357.0,"Cheated on, mistreated and stepped on, the wom...",Waiting to Exhale (1995),"[Whitney Houston, Angela Bassett, Loretta Devine]",[Forest Whitaker],"[based on novel, interracial relationship, sin...",34.0,6.209113,Forest Whitaker

In [92]:
movies.iloc[0].overview

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences."

In [93]:
movies["overview"] = movies["overview"].apply(lambda x:x.split())

In [94]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg,director
0,"[Animation, Comedy, Family]",862.0,"[Led, by, Woody,, Andy's, toys, live, happily,...",Toy Story (1995),"[Tom Hanks, Tim Allen, Don Rickles]",[John Lasseter],"[jealousy, toy, boy, friendship, friends, riva...",5415.0,7.691378,John Lasseter
1,"[Adventure, Fantasy, Family]",8844.0,"[When, siblings, Judy, and, Peter, discover, a...",Jumanji (1995),"[Robin Williams, Jonathan Hyde, Kirsten Dunst]",[Joe Johnston],"[board game, disappearance, based on children'...",2413.0,6.891917,Joe Johnston
2,"[Romance, Comedy]",15602.0,"[A, family, wedding, reignites, the, ancient, ...",Grumpier Old Men (1995),"[Walter Matthau, Jack Lemmon, Ann-Margret]",[Howard Deutch],"[fishing, best friend, duringcreditsstinger, o...",92.0,6.450950,Howard Deutch
3,"[Comedy, Drama, Romance]",31357.0,"[Cheated, on,, mistreated, and, stepped, on,, ...",Waiting to Exhale (1995),"[Whitney Houston, Angela Bassett, Loretta Devine]",[Forest Whitaker],"[based on novel, interracial relationship, sin...",34.0,6.209113,Forest Whitaker
4,[Comedy],11862.0,"[Just, when, George, Banks, has, recovered, fr...",Father of the Bride Part II (1995),"[Steve Martin, Diane Keaton, Martin Short]",[Charles Shyer],"[baby, midlife crisis, confidence, aging, daug...",173.0,5.801544,Charles Shyer
...,...,...,...,...,...,...,...,...,...,...
45309,[Comedy],248705.0,"[Stuck, in, the, corridors, of, time,, Godefro...",The Visitors: Bastille Day (2016),"[Jean Reno, Christian Clavier, Franck Dubosc]",[Jean-Marie Poiré],"[nazis, castle, time travel, robespierre]",167.0,4.392138,Jean-Marie Poiré
45314,"[Action, Adventure, Thriller]",44918.0,"[On, the, 100th, anniversary, of, the, origina...",Titanic 2 (2010),"[Shane Van Dyke, Marie Westbrook, Bruce Davison]",[Shane Van Dyke],[suspense],55.0,4.514828,Shane Van Dyke
45339,"[Comedy, Crime]",426272.0,"[Ray, is, a, fledgling, entrepreneur, who, spe...",Take Me (2017),"[Taylor Schilling, Pat Healy, Alycia Delmore]",[Pat Healy],[],38.0,6.150273,Pat Healy
45346,"[Romance, Comedy]",432789.0,"[Burned, by, a, bad, breakup,, a, struggling, ...",The Incredible Jessica James (2017),"[Jessica Williams, Chris O'Dowd, Keith Stanfield]",[Jim Strouse],[],37.0,6.256615,Jim Strouse
45407,[Comedy],14008.0,"[Hyperactive, teenager, Kelly, is, enrolled, i...",Cadet Kelly (2002),"[Hilary Duff, Christy Carlson Romano, Gary Cole]",[Larry Shaw],[military school],145.0,5.412400,Larry Shaw

In [95]:
movies["genres"] = movies["genres"].apply(lambda x:[i.replace(" ", "") for i in x])
movies["cast"] = movies["cast"].apply(lambda x:[i.replace(" ", "") for i in x])
movies["crew"] = movies["crew"].apply(lambda x:[i.replace(" ", "") for i in x])
movies["keywords"] = movies["keywords"].apply(lambda x:[i.replace(" ", "") for i in x])

In [96]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg,director
0,"[Animation, Comedy, Family]",862.0,"[Led, by, Woody,, Andy's, toys, live, happily,...",Toy Story (1995),"[TomHanks, TimAllen, DonRickles]",[JohnLasseter],"[jealousy, toy, boy, friendship, friends, riva...",5415.0,7.691378,John Lasseter
1,"[Adventure, Fantasy, Family]",8844.0,"[When, siblings, Judy, and, Peter, discover, a...",Jumanji (1995),"[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston],"[boardgame, disappearance, basedonchildren'sbo...",2413.0,6.891917,Joe Johnston
2,"[Romance, Comedy]",15602.0,"[A, family, wedding, reignites, the, ancient, ...",Grumpier Old Men (1995),"[WalterMatthau, JackLemmon, Ann-Margret]",[HowardDeutch],"[fishing, bestfriend, duringcreditsstinger, ol...",92.0,6.450950,Howard Deutch
3,"[Comedy, Drama, Romance]",31357.0,"[Cheated, on,, mistreated, and, stepped, on,, ...",Waiting to Exhale (1995),"[WhitneyHouston, AngelaBassett, LorettaDevine]",[ForestWhitaker],"[basedonnovel, interracialrelationship, single...",34.0,6.209113,Forest Whitaker
4,[Comedy],11862.0,"[Just, when, George, Banks, has, recovered, fr...",Father of the Bride Part II (1995),"[SteveMartin, DianeKeaton, MartinShort]",[CharlesShyer],"[baby, midlifecrisis, confidence, aging, daugh...",173.0,5.801544,Charles Shyer
...,...,...,...,...,...,...,...,...,...,...
45309,[Comedy],248705.0,"[Stuck, in, the, corridors, of, time,, Godefro...",The Visitors: Bastille Day (2016),"[JeanReno, ChristianClavier, FranckDubosc]",[Jean-MariePoiré],"[nazis, castle, timetravel, robespierre]",167.0,4.392138,Jean-Marie Poiré
45314,"[Action, Adventure, Thriller]",44918.0,"[On, the, 100th, anniversary, of, the, origina...",Titanic 2 (2010),"[ShaneVanDyke, MarieWestbrook, BruceDavison]",[ShaneVanDyke],[suspense],55.0,4.514828,Shane Van Dyke
45339,"[Comedy, Crime]",426272.0,"[Ray, is, a, fledgling, entrepreneur, who, spe...",Take Me (2017),"[TaylorSchilling, PatHealy, AlyciaDelmore]",[PatHealy],[],38.0,6.150273,Pat Healy
45346,"[Romance, Comedy]",432789.0,"[Burned, by, a, bad, breakup,, a, struggling, ...",The Incredible Jessica James (2017),"[JessicaWilliams, ChrisO'Dowd, KeithStanfield]",[JimStrouse],[],37.0,6.256615,Jim Strouse
45407,[Comedy],14008.0,"[Hyperactive, teenager, Kelly, is, enrolled, i...",Cadet Kelly (2002),"[HilaryDuff, ChristyCarlsonRomano, GaryCole]",[LarryShaw],[militaryschool],145.0,5.412400,Larry Shaw

In [97]:
movies["overview"] = movies["overview"].apply(lambda x: x[:50])

In [98]:
movies["tag"] = (
    movies["crew"] * 3 +
    movies["genres"] * 4 +
    movies["keywords"] * 4 +
    movies["cast"] * 2 +
    movies["overview"]
)

In [99]:
movies

,genres,id,overview,title,cast,crew,keywords,vote_count,new_vote_avg,director,tag
0,"[Animation, Comedy, Family]",862.0,"[Led, by, Woody,, Andy's, toys, live, happily,...",Toy Story (1995),"[TomHanks, TimAllen, DonRickles]",[JohnLasseter],"[jealousy, toy, boy, friendship, friends, riva...",5415.0,7.691378,John Lasseter,"[JohnLasseter, JohnLasseter, JohnLasseter, Ani..."
1,"[Adventure, Fantasy, Family]",8844.0,"[When, siblings, Judy, and, Peter, discover, a...",Jumanji (1995),"[RobinWilliams, JonathanHyde, KirstenDunst]",[JoeJohnston],"[boardgame, disappearance, basedonchildren'sbo...",2413.0,6.891917,Joe Johnston,"[JoeJohnston, JoeJohnston, JoeJohnston, Advent..."
2,"[Romance, Comedy]",15602.0,"[A, family, wedding, reignites, the, ancient, ...",Grumpier Old Men (1995),"[WalterMatthau, JackLemmon, Ann-Margret]",[HowardDeutch],"[fishing, bestfriend, duringcreditsstinger, ol...",92.0,6.450950,Howard Deutch,"[HowardDeutch, HowardDeutch, HowardDeutch, Rom..."
3,"[Comedy, Drama, Romance]",31357.0,"[Cheated, on,, mistreated, and, stepped, on,, ...",Waiting to Exhale (1995),"[WhitneyHouston, AngelaBassett, LorettaDevine]",[ForestWhitaker],"[basedonnovel, interracialrelationship, single...",34.0,6.209113,Forest Whitaker,"[ForestWhitaker, ForestWhitaker, ForestWhitake..."
4,[Comedy],11862.0,"[Just, when, George, Banks, has, recovered, fr...",Father of the Bride Part II (1995),"[SteveMartin, DianeKeaton, MartinShort]",[CharlesShyer],"[baby, midlifecrisis, confidence, aging, daugh...",173.0,5.801544,Charles Shyer,"[CharlesShyer, CharlesShyer, CharlesShyer, Com..."
...,...,...,...,...,...,...,...,...,...,...,...
45309,[Comedy],248705.0,"[Stuck, in, the, corridors, of, time,, Godefro...",The Visitors: Bastille Day (2016),"[JeanReno, ChristianClavier, FranckDubosc]",[Jean-MariePoiré],"[nazis, castle, timetravel, robespierre]",167.0,4.392138,Jean-Marie Poiré,"[Jean-MariePoiré, Jean-MariePoiré, Jean-MarieP..."
45314,"[Action, Adventure, Thriller]",44918.0,"[On, the, 100th, anniversary, of, the, origina...",Titanic 2 (2010),"[ShaneVanDyke, MarieWestbrook, BruceDavison]",[ShaneVanDyke],[suspense],55.0,4.514828,Shane Van Dyke,"[ShaneVanDyke, ShaneVanDyke, ShaneVanDyke, Act..."
45339,"[Comedy, Crime]",426272.0,"[Ray, is, a, fledgling, entrepreneur, who, spe...",Take Me (2017),"[TaylorSchilling, PatHealy, AlyciaDelmore]",[PatHealy],[],38.0,6.150273,Pat Healy,"[PatHealy, PatHealy, PatHealy, Comedy, Crime, ..."
45346,"[Romance, Comedy]",432789.0,"[Burned, by, a, bad, breakup,, a, struggling, ...",The Incredible Jessica James (2017),"[JessicaWilliams, ChrisO'Dowd, KeithStanfield]",[JimStrouse],[],37.0,6.256615,Jim Strouse,"[JimStrouse, JimStrouse, JimStrouse, Romance, ..."
45407,[Comedy],14008.0,"[Hyperactive, teenager, Kelly, is, enrolled, i...",Cadet Kelly (2002),"[HilaryDuff, ChristyCarlsonRomano, GaryCole]",[LarryShaw],[militaryschool],145.0,5.412400,Larry Shaw,"[LarryShaw, LarryShaw, LarryShaw, Comedy, Come..."

In [100]:
movies = movies[["id", "title", "tag", "vote_count", "new_vote_avg", "crew", "director"]]

In [101]:
movies

,id,title,tag,vote_count,new_vote_avg,crew,director
0,862.0,Toy Story (1995),"[JohnLasseter, JohnLasseter, JohnLasseter, Ani...",5415.0,7.691378,[JohnLasseter],John Lasseter
1,8844.0,Jumanji (1995),"[JoeJohnston, JoeJohnston, JoeJohnston, Advent...",2413.0,6.891917,[JoeJohnston],Joe Johnston
2,15602.0,Grumpier Old Men (1995),"[HowardDeutch, HowardDeutch, HowardDeutch, Rom...",92.0,6.450950,[HowardDeutch],Howard Deutch
3,31357.0,Waiting to Exhale (1995),"[ForestWhitaker, ForestWhitaker, ForestWhitake...",34.0,6.209113,[ForestWhitaker],Forest Whitaker
4,11862.0,Father of the Bride Part II (1995),"[CharlesShyer, CharlesShyer, CharlesShyer, Com...",173.0,5.801544,[CharlesShyer],Charles Shyer
...,...,...,...,...,...,...,...
45309,248705.0,The Visitors: Bastille Day (2016),"[Jean-MariePoiré, Jean-MariePoiré, Jean-MarieP...",167.0,4.392138,[Jean-MariePoiré],Jean-Marie Poiré
45314,44918.0,Titanic 2 (2010),"[ShaneVanDyke, ShaneVanDyke, ShaneVanDyke, Act...",55.0,4.514828,[ShaneVanDyke],Shane Van Dyke
45339,426272.0,Take Me (2017),"[PatHealy, PatHealy, PatHealy, Comedy, Crime, ...",38.0,6.150273,[PatHealy],Pat Healy
45346,432789.0,The Incredible Jessica James (2017),"[JimStrouse, JimStrouse, JimStrouse, Romance, ...",37.0,6.256615,[JimStrouse],Jim Strouse
45407,14008.0,Cadet Kelly (2002),"[LarryShaw, LarryShaw, LarryShaw, Comedy, Come...",145.0,5.412400,[LarryShaw],Larry Shaw

In [102]:
movies["tag"] = movies["tag"].apply(lambda x : " ".join(x))

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_18640\2733104798.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["tag"] = movies["tag"].apply(lambda x : " ".join(x))

In [103]:
movies

,id,title,tag,vote_count,new_vote_avg,crew,director
0,862.0,Toy Story (1995),JohnLasseter JohnLasseter JohnLasseter Animati...,5415.0,7.691378,[JohnLasseter],John Lasseter
1,8844.0,Jumanji (1995),JoeJohnston JoeJohnston JoeJohnston Adventure ...,2413.0,6.891917,[JoeJohnston],Joe Johnston
2,15602.0,Grumpier Old Men (1995),HowardDeutch HowardDeutch HowardDeutch Romance...,92.0,6.450950,[HowardDeutch],Howard Deutch
3,31357.0,Waiting to Exhale (1995),ForestWhitaker ForestWhitaker ForestWhitaker C...,34.0,6.209113,[ForestWhitaker],Forest Whitaker
4,11862.0,Father of the Bride Part II (1995),CharlesShyer CharlesShyer CharlesShyer Comedy ...,173.0,5.801544,[CharlesShyer],Charles Shyer
...,...,...,...,...,...,...,...
45309,248705.0,The Visitors: Bastille Day (2016),Jean-MariePoiré Jean-MariePoiré Jean-MariePoir...,167.0,4.392138,[Jean-MariePoiré],Jean-Marie Poiré
45314,44918.0,Titanic 2 (2010),ShaneVanDyke ShaneVanDyke ShaneVanDyke Action ...,55.0,4.514828,[ShaneVanDyke],Shane Van Dyke
45339,426272.0,Take Me (2017),PatHealy PatHealy PatHealy Comedy Crime Comedy...,38.0,6.150273,[PatHealy],Pat Healy
45346,432789.0,The Incredible Jessica James (2017),JimStrouse JimStrouse JimStrouse Romance Comed...,37.0,6.256615,[JimStrouse],Jim Strouse
45407,14008.0,Cadet Kelly (2002),LarryShaw LarryShaw LarryShaw Comedy Comedy Co...,145.0,5.412400,[LarryShaw],Larry Shaw

In [104]:
movies["tag"] = movies["tag"].str.lower()

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_18640\121673973.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["tag"] = movies["tag"].str.lower()

In [105]:
movies

,id,title,tag,vote_count,new_vote_avg,crew,director
0,862.0,Toy Story (1995),johnlasseter johnlasseter johnlasseter animati...,5415.0,7.691378,[JohnLasseter],John Lasseter
1,8844.0,Jumanji (1995),joejohnston joejohnston joejohnston adventure ...,2413.0,6.891917,[JoeJohnston],Joe Johnston
2,15602.0,Grumpier Old Men (1995),howarddeutch howarddeutch howarddeutch romance...,92.0,6.450950,[HowardDeutch],Howard Deutch
3,31357.0,Waiting to Exhale (1995),forestwhitaker forestwhitaker forestwhitaker c...,34.0,6.209113,[ForestWhitaker],Forest Whitaker
4,11862.0,Father of the Bride Part II (1995),charlesshyer charlesshyer charlesshyer comedy ...,173.0,5.801544,[CharlesShyer],Charles Shyer
...,...,...,...,...,...,...,...
45309,248705.0,The Visitors: Bastille Day (2016),jean-mariepoiré jean-mariepoiré jean-mariepoir...,167.0,4.392138,[Jean-MariePoiré],Jean-Marie Poiré
45314,44918.0,Titanic 2 (2010),shanevandyke shanevandyke shanevandyke action ...,55.0,4.514828,[ShaneVanDyke],Shane Van Dyke
45339,426272.0,Take Me (2017),pathealy pathealy pathealy comedy crime comedy...,38.0,6.150273,[PatHealy],Pat Healy
45346,432789.0,The Incredible Jessica James (2017),jimstrouse jimstrouse jimstrouse romance comed...,37.0,6.256615,[JimStrouse],Jim Strouse
45407,14008.0,Cadet Kelly (2002),larryshaw larryshaw larryshaw comedy comedy co...,145.0,5.412400,[LarryShaw],Larry Shaw

In [106]:
movies["crew"] = movies["crew"].apply(lambda x : " ".join(x))

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_18640\692877924.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["crew"] = movies["crew"].apply(lambda x : " ".join(x))

In [107]:
movies["crew"] = movies["crew"].str.lower()

C:\Users\Varun Bahuguna\AppData\Local\Temp\ipykernel_18640\235839181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["crew"] = movies["crew"].str.lower()

In [108]:
movies

,id,title,tag,vote_count,new_vote_avg,crew,director
0,862.0,Toy Story (1995),johnlasseter johnlasseter johnlasseter animati...,5415.0,7.691378,johnlasseter,John Lasseter
1,8844.0,Jumanji (1995),joejohnston joejohnston joejohnston adventure ...,2413.0,6.891917,joejohnston,Joe Johnston
2,15602.0,Grumpier Old Men (1995),howarddeutch howarddeutch howarddeutch romance...,92.0,6.450950,howarddeutch,Howard Deutch
3,31357.0,Waiting to Exhale (1995),forestwhitaker forestwhitaker forestwhitaker c...,34.0,6.209113,forestwhitaker,Forest Whitaker
4,11862.0,Father of the Bride Part II (1995),charlesshyer charlesshyer charlesshyer comedy ...,173.0,5.801544,charlesshyer,Charles Shyer
...,...,...,...,...,...,...,...
45309,248705.0,The Visitors: Bastille Day (2016),jean-mariepoiré jean-mariepoiré jean-mariepoir...,167.0,4.392138,jean-mariepoiré,Jean-Marie Poiré
45314,44918.0,Titanic 2 (2010),shanevandyke shanevandyke shanevandyke action ...,55.0,4.514828,shanevandyke,Shane Van Dyke
45339,426272.0,Take Me (2017),pathealy pathealy pathealy comedy crime comedy...,38.0,6.150273,pathealy,Pat Healy
45346,432789.0,The Incredible Jessica James (2017),jimstrouse jimstrouse jimstrouse romance comed...,37.0,6.256615,jimstrouse,Jim Strouse
45407,14008.0,Cadet Kelly (2002),larryshaw larryshaw larryshaw comedy comedy co...,145.0,5.412400,larryshaw,Larry Shaw

In [109]:
movies = movies.reset_index(drop=True)

In [110]:
movies

,id,title,tag,vote_count,new_vote_avg,crew,director
0,862.0,Toy Story (1995),johnlasseter johnlasseter johnlasseter animati...,5415.0,7.691378,johnlasseter,John Lasseter
1,8844.0,Jumanji (1995),joejohnston joejohnston joejohnston adventure ...,2413.0,6.891917,joejohnston,Joe Johnston
2,15602.0,Grumpier Old Men (1995),howarddeutch howarddeutch howarddeutch romance...,92.0,6.450950,howarddeutch,Howard Deutch
3,31357.0,Waiting to Exhale (1995),forestwhitaker forestwhitaker forestwhitaker c...,34.0,6.209113,forestwhitaker,Forest Whitaker
4,11862.0,Father of the Bride Part II (1995),charlesshyer charlesshyer charlesshyer comedy ...,173.0,5.801544,charlesshyer,Charles Shyer
...,...,...,...,...,...,...,...
11193,248705.0,The Visitors: Bastille Day (2016),jean-mariepoiré jean-mariepoiré jean-mariepoir...,167.0,4.392138,jean-mariepoiré,Jean-Marie Poiré
11194,44918.0,Titanic 2 (2010),shanevandyke shanevandyke shanevandyke action ...,55.0,4.514828,shanevandyke,Shane Van Dyke
11195,426272.0,Take Me (2017),pathealy pathealy pathealy comedy crime comedy...,38.0,6.150273,pathealy,Pat Healy
11196,432789.0,The Incredible Jessica James (2017),jimstrouse jimstrouse jimstrouse romance comed...,37.0,6.256615,jimstrouse,Jim Strouse
11197,14008.0,Cadet Kelly (2002),larryshaw larryshaw larryshaw comedy comedy co...,145.0,5.412400,larryshaw,Larry Shaw

In [111]:
movies.rename(columns={"new_vote_avg": "rating"}, inplace=True)

In [112]:
movies

,id,title,tag,vote_count,rating,crew,director
0,862.0,Toy Story (1995),johnlasseter johnlasseter johnlasseter animati...,5415.0,7.691378,johnlasseter,John Lasseter
1,8844.0,Jumanji (1995),joejohnston joejohnston joejohnston adventure ...,2413.0,6.891917,joejohnston,Joe Johnston
2,15602.0,Grumpier Old Men (1995),howarddeutch howarddeutch howarddeutch romance...,92.0,6.450950,howarddeutch,Howard Deutch
3,31357.0,Waiting to Exhale (1995),forestwhitaker forestwhitaker forestwhitaker c...,34.0,6.209113,forestwhitaker,Forest Whitaker
4,11862.0,Father of the Bride Part II (1995),charlesshyer charlesshyer charlesshyer comedy ...,173.0,5.801544,charlesshyer,Charles Shyer
...,...,...,...,...,...,...,...
11193,248705.0,The Visitors: Bastille Day (2016),jean-mariepoiré jean-mariepoiré jean-mariepoir...,167.0,4.392138,jean-mariepoiré,Jean-Marie Poiré
11194,44918.0,Titanic 2 (2010),shanevandyke shanevandyke shanevandyke action ...,55.0,4.514828,shanevandyke,Shane Van Dyke
11195,426272.0,Take Me (2017),pathealy pathealy pathealy comedy crime comedy...,38.0,6.150273,pathealy,Pat Healy
11196,432789.0,The Incredible Jessica James (2017),jimstrouse jimstrouse jimstrouse romance comed...,37.0,6.256615,jimstrouse,Jim Strouse
11197,14008.0,Cadet Kelly (2002),larryshaw larryshaw larryshaw comedy comedy co...,145.0,5.412400,larryshaw,Larry Shaw

In [113]:
from sentence_transformers import SentenceTransformer
import torch

In [114]:
model = SentenceTransformer('all-MiniLM-L6-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [115]:
print("Generating Transformer Embeddings... 🍿")
sbert_vectors = model.encode(movies['tag'].tolist(), show_progress_bar=True)

Generating Transformer Embeddings... 🍿

Batches:   0%|          | 0/350 [00:00<?, ?it/s]

In [116]:
import nltk
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [117]:
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to C:\Users\Varun
[nltk_data]     Bahuguna\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:\Users\Varun
[nltk_data]     Bahuguna\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [118]:
from nltk.corpus import wordnet
from nltk import pos_tag

def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

In [119]:
def lemmatize_text(text):
    words = text.split()
    tagged_words = pos_tag(words)

    lemmatized = []

    for word, tag in tagged_words:
        lemmatized.append(lemmatizer.lemmatize(word, get_wordnet_pos(tag)))
    
    return " ".join(lemmatized)

In [120]:
movies["tag"] = movies["tag"].apply(lemmatize_text)

In [121]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [122]:
tfidf = TfidfVectorizer(max_features=5000, stop_words="english", ngram_range=(1, 3))

In [123]:
tfidf_vectors = tfidf.fit_transform(movies["tag"])

In [124]:
tfidf_vectors.shape

(11198, 5000)

In [125]:
tfidf.get_feature_names_out()[:1000]

array(['000', '10', '10 year', '11', '12', '12 year', '12 year old', '13',
       '15', '15 year', '16', '17', '17thcentury', '18', '18thcentury',
       '1920s', '1930s', '1940s', '1950s', '1960s', '1970s', '1980s',
       '1990s', '19th', '19th century', '19thcentury', '20', '20 year',
       '30', '3d', '40', 'aaroneckhart', 'abandon', 'abduct',
       'abigailbreslin', 'ability', 'able', 'aboard', 'abortion', 'abuse',
       'abusive', 'academy', 'accept', 'accident', 'accidentally',
       'accompany', 'account', 'accountant', 'accuse', 'achieve', 'act',
       'action', 'action action', 'action action action',
       'action adventure', 'action adventure action',
       'action adventure animation', 'action adventure comedy',
       'action adventure crime', 'action adventure drama',
       'action adventure family', 'action adventure fantasy',
       'action adventure history', 'action adventure horror',
       'action adventure sciencefiction', 'action adventure thriller',
       'action animation', 'action animation action',
       'action animation adventure', 'action animation sciencefiction',
       'action comedy', 'action comedy action', 'action comedy adventure',
       'action comedy crime', 'action comedy drama',
       'action comedy family', 'action comedy horror',
       'action comedy romance', 'action comedy sciencefiction',
       'action comedy thriller', 'action comedy western', 'action crime',
       'action crime action', 'action crime comedy', 'action crime drama',
       'action crime mystery', 'action crime thriller', 'action drama',
       'action drama action', 'action drama crime',
       'action drama fantasy', 'action drama history',
       'action drama horror', 'action drama mystery',
       'action drama romance', 'action drama sciencefiction',
       'action drama thriller', 'action drama war',
       'action drama western', 'action family', 'action fantasy',
       'action fantasy action', 'action fantasy adventure',
       'action fantasy horror', 'action fantasy sciencefiction',
       'action history', 'action history war', 'action horror',
       'action horror action', 'action horror sciencefiction',
       'action horror thriller', 'action mystery',
       'action mystery thriller', 'action romance',
       'action sciencefiction', 'action sciencefiction action',
       'action sciencefiction adventure', 'action sciencefiction horror',
       'action sciencefiction thriller', 'action thriller',
       'action thriller action', 'action thriller adventure',
       'action thriller crime', 'action thriller drama',
       'action thriller horror', 'action thriller mystery',
       'action thriller sciencefiction', 'action thriller war',
       'action war', 'action western', 'actionhero', 'activist', 'actor',
       'actress', 'actually', 'adam', 'adamsandler', 'adapt',
       'adaptation', 'addict', 'addiction', 'adolescence', 'adolfhitler',
       'adopt', 'adoption', 'adrienbrody', 'adult', 'adultanimation',
       'adultery', 'adultery basedonnovel', 'adventure',
       'adventure action', 'adventure action adventure',
       'adventure action comedy', 'adventure action drama',
       'adventure action fantasy', 'adventure action sciencefiction',
       'adventure action thriller', 'adventure adventure',
       'adventure adventure adventure', 'adventure animation',
       'adventure animation action', 'adventure animation comedy',
       'adventure animation drama', 'adventure animation family',
       'adventure animation fantasy', 'adventure comedy',
       'adventure comedy action', 'adventure comedy adventure',
       'adventure comedy crime', 'adventure comedy drama',
       'adventure comedy family', 'adventure comedy fantasy',
       'adventure comedy romance', 'adventure comedy sciencefiction',
       'adventure comedy thriller', 'adventure crime',
       'adventure crime action', 'adventure crime drama',
       'adventure crime thriller', 'adventure drama',
       'adventure drama action', 'adventure drama adventure',
       'adventure drama family', 'adventure drama fantasy',
       'adventure drama history', 'adventure drama romance',
       'adventure drama sciencefiction', 'adventure drama thriller',
       'adventure drama western', 'adventure family',
       'adventure family adventure', 'adventure family animation',
       'adventure family comedy', 'adventure family fantasy',
       'adventure fantasy', 'adventure fantasy action',
       'adventure fantasy animation', 'adventure fantasy comedy',
       'adventure fantasy drama', 'adventure fantasy family',
       'adventure fantasy sciencefiction', 'adventure history',
       'adventure horror', 'adventure horror sciencefiction',
       'adventure horror thriller', 'adventure mystery',
       'adventure romance', 'adventure sciencefiction',
       'adventure sciencefiction action',
       'adventure sciencefiction adventure',
       'adventure sciencefiction thriller', 'adventure thriller',
       'adventure thriller action', 'adventure thriller sciencefiction',
       'adventure war', 'adventure western', 'adventurer', 'adversary',
       'advertising', 'advice', 'affair', 'affection', 'afghanistan',
       'africa', 'african', 'africanamerican', 'aftercreditsstinger',
       'aftercreditsstinger duringcreditsstinger', 'afterlife',
       'aftermath', 'age', 'aged', 'agedifference', 'agency', 'agent',
       'aggressionbyanimal', 'ago', 'agree', 'aid', 'air', 'airforce',
       'airplane', 'airplanecrash', 'airport', 'akirakurosawa',
       'akirakurosawa akirakurosawa', 'al', 'alainchabat', 'alanparker',
       'alanrickman', 'alaska', 'alcatraz', 'alcohol', 'alcohol sex',
       'alcoholabuse', 'alcoholic', 'alcoholism', 'alecbaldwin', 'alex',
       'alfredhitchcock', 'alfredhitchcock alfredhitchcock',
       'alfredhitchcock alfredhitchcock alfredhitchcock', 'alice',
       'alien', 'alien independentfilm', 'alieninfection',
       'alieninvasion', 'alienlife', 'alienlife form', 'alienplanet',
       'alive', 'allegory', 'allow', 'ally', 'alpacino', 'alter',
       'alternatedimension', 'alternatereality', 'alzheimer', 'amazon',
       'ambassador', 'ambition', 'ambitious', 'ambulance', 'ambush',
       'america', 'american', 'americanabroad', 'americancivilwar',
       'americandream', 'americanfootball', 'americanfootballplayer',
       'amnesia', 'amp', 'amusementpark', 'amyadams', 'anarchiccomedy',
       'ancient', 'ancientgreece', 'ancientrome', 'ancientworld',
       'anderson', 'andrew', 'andrewdavis', 'android', 'andy',
       'andygarcía', 'andylau', 'angel', 'angeles', 'angelinajolie',
       'anger', 'anglee', 'animal', 'animalattack', 'animalhorror',
       'animation', 'animation action', 'animation action adventure',
       'animation action animation', 'animation action sciencefiction',
       'animation adventure', 'animation adventure comedy',
       'animation adventure family', 'animation animation',
       'animation animation animation', 'animation comedy',
       'animation comedy adventure', 'animation comedy animation',
       'animation comedy drama', 'animation comedy family',
       'animation drama', 'animation drama animation',
       'animation drama family', 'animation family',
       'animation family adventure', 'animation family animation',
       'animation family comedy', 'animation family fantasy',
       'animation fantasy', 'animation fantasy sciencefiction',
       'animation horror', 'animation romance',
       'animation sciencefiction', 'animation sciencefiction action',
       'animation sciencefiction family', 'anime', 'anjelicahuston',
       'ann', 'anna', 'annafaris', 'annakendrick', 'anne', 'annehathaway',
       'annemoss', 'annettebening', 'annie', 'answer', 'ant', 'anthology',
       'anthonyhopkins', 'anthropomorphism', 'anti', 'anti christ',
       'antihero', 'antisemitism', 'antoinefuqua', 'antoniobanderas',
       'apache', 'apart', 'apartheid', 'apartment', 'ape', 'apocalypse',
       'apocalyptic', 'apocalyptic dystopia', 'appear', 'appearance',
       'apple', 'apprentice', 'approach', 'aquarium', 'arab', 'arabian',
       'arbitrarylaw', 'archaeologist', 'archeology', 'architect',
       'arctic', 'area', 'arena', 'argentina', 'argument', 'aristocrat',
       'arizona', 'arkansas', 'arm', 'armsdealer', 'army',
       'arnoldschwarzenegger', 'arrangedmarriage', 'arrest', 'arrival',
       'arrive', 'arrives', 'arson', 'art', 'artgallery', 'arthur',
       'artifact', 'artificialintelligence',
       'artificialintelligence manvsmachine', 'artist', 'ash',
       'ashleyjudd', 'ashtonkutcher', 'asia', 'ask', 'aspire', 'assassin',
       'assassination', 'assault', 'assign', 'assignment', 'assistant',
       'asteroid', 'astronaut', 'asylum', 'atheist', 'athlete',
       'atomicbomb', 'attack', 'attempt', 'attemptedmurder',
       'attempttoescape', 'attend', 'attention', 'attic', 'attorney',
       'attract', 'attraction', 'attractive', 'auction', 'audience',
       'audition', 'audreyhepburn', 'audreytautou', 'aunt', 'australia',
       'australian', 'australianoutback', 'austria', 'author',
       'authority', 'autism', 'auto', 'autobiography', 'automobileracing',
       'autopsy', 'avenge', 'aviation', 'avoid', 'await', 'awaken',
       'award', 'away', 'awry', 'ax', 'axe', 'axemurder', 'baby',
       'baby snatching', 'babysitter', 'bachelor', 'backpacker', 'bad',
       'badluck', 'badmother', 'badmother law', 'bahamas', 'ball',
       'ballet', 'baltimore', 'band', 'bandit', 'bangkok', 'bank',
       'banker', 'bankrobber', 'bankrobbery', 'bar', 'barbie',
       'barcelonaspain', 'barn', 'barrylevinson',
       'barrylevinson barrylevinson', 'barrysonnenfeld', 'bartender',
       'base', 'base true', 'base true story', 'baseball',
       'baseball sport', 'basedoncartoon', 'basedonchildren',
       'basedonchildren sbook', 'basedoncomic', 'basedoncomic superhuman',
       'basedonfairytale', 'basedongraphicnovel', 'basedonmanga',
       'basedonnovel', 'basedonplayormusical', 'basedonshortfilm',
       'basedonshortstory', 'basedontoy', 'basedontrueevents',
       'basedontruestory', 'basedontvseries', 'basedonvideogame',
       'basedonyoungadultnovel', 'basement', 'basketball', 'bat', 'bath',
       'bathtub', 'batman', 'battle', 'battlefield', 'battleforpower',
       'bdsm', 'beach', 'beachhouse', 'bear', 'beast', 'beat',
       'beautiful', 'beautifulwoman', 'beauty', 'becominganadult', 'bed',
       'bedroom', 'beer', 'befriend', 'begin', 'beginning', 'behavior',
       'belgium', 'believe', 'bell', 'beloved', 'ben', 'benaffleck',
       'benkingsley', 'benstiller', 'berlin', 'best', 'best friend',
       'bestfriend', 'bestfriendsinlove', 'bet', 'betrayal', 'bible',
       'bicycle', 'big', 'biker', 'bikini', 'billionaire', 'billmurray',
       'billnighy', 'billpaxton', 'billpullman', 'billy',
       'billybobthornton', 'billycrystal', 'billywilder',
       'billywilder billywilder', 'biography',
       'biography basedontruestory', 'biography biography',
       'biography historicalfigure', 'biography sport',
       'biologicalweapon', 'bird', 'birth', 'birthday', 'birthdayparty',
       'bisexuality', 'bishop', 'bite', 'bizarre', 'black',
       'blackandwhite', 'blackhumor', 'blackmagic', 'blackmail',
       'blackout', 'blackpeople', 'blade', 'blakeedwards',
       'blakeedwards blakeedwards', 'blaxploitation', 'blind',
       'blinddate', 'blindness', 'blindnessandimpairedvision', 'blizzard',
       'blonde', 'blood', 'blood slasher', 'blood violence',
       'bloodsplatter', 'bloody', 'blow', 'blue', 'bmovie', 'board',
       'boardingschool', 'boat', 'bob', 'bobby', 'bobbyfarrelly',
       'bobbyfarrelly peterfarrelly', 'body', 'body swap', 'bodyguard',
       'bodyhorror', 'bollywood', 'bomb', 'bomber', 'bond', 'bondage',
       'bone', 'book', 'border', 'boredom', 'born', 'bos', 'boss',
       'boston', 'bound', 'bounty', 'bountyhunter', 'box', 'boxer',
       'boxingmatch', 'boy', 'boyfriend', 'boys', 'bradleycooper',
       'bradpitt', 'brain', 'brainwash', 'brave', 'bravery', 'brawl',
       'brazil', 'brazilian', 'brazilian comedy', 'break',
       'breakingthefourthwall', 'brendanfraser', 'brettratner', 'brian',
       'briancox', 'briandepalma', 'briandepalma briandepalma',
       'brianlevant', 'bride', 'bridge', 'brien', 'brilliant', 'bring',
       'britain', 'british', 'britisharmy', 'britishsecretservice',
       'broadway', 'broker', 'brooklynnewyorkcity', 'broom', 'brothel',
       'brother', 'brother law', 'brotherbrotherrelationship', 'brothers',
       'brothersisterrelationship', 'brown', 'bruce', 'brucewillis',
       'brutal', 'brutality', 'brutality violence', 'brutally', 'buddy',
       'buddycomedy', 'buddycop', 'budget', 'budspencer', 'build',
       'building', 'bullet', 'bulletwound', 'bully', 'bunker', 'burglar',
       'burglary', 'buriedalive', 'burn', 'burnedalive', 'burtlancaster',
       'bury', 'bus', 'business', 'businessman', 'busterkeaton',
       'butcher', 'butler', 'butterfly', 'buy', 'cabin', 'cage', 'cairo',
       'california', 'camcorder', 'camera', 'camerondiaz', 'camp',
       'campaign', 'campus', 'canada', 'canadian', 'cancer', 'cannabis',
       'cannibal', 'cannibalism', 'canuxploitation', 'capitalism',
       'captain', 'captive', 'capture', 'car', 'car accident',
       'caraccident', 'carchase', 'carcrash', 'cardealer', 'cardgame',
       'care', 'career', 'caribbean', 'carjourney', 'carloverdone',
       'carmechanic', 'carnival', 'carrace', 'carrie', 'carrie annemoss',
       'carry', 'carter', 'carygrant', 'case', 'cash', 'casino', 'cast',
       'castle', 'castration', 'cat', 'cat mouse', 'cataclysm',
       'catastrophe', 'catch', 'cateblanchett', 'catherinedeneuve',
       'catherinekeener', 'catherinezeta', 'catherinezeta jones',
       'catholic', 'catholicism', 'cattle', 'cause', 'cavalry', 'cave',
       'caveman', 'celebrate', 'celebration', 'celebrity', 'cellphone',
       'cemetery', 'center', 'century', 'cgi', 'chain', 'chainsaw',
       'challenge', 'champion', 'championship', 'chance', 'change',
       'channingtatum', 'chaos', 'character', 'charge', 'charismatic',
       'charles', 'charlie', 'charliechaplin', 'charliesheen',
       'charlizetheron', 'charltonheston', 'charm', 'chase',
       'chasesandraces', 'chauffeur', 'cheat', 'cheatinghusband',
       'cheatingwife', 'cheerlead', 'cheerleader', 'chef', 'chess',
       'chevychase', 'chicago', 'chicken', 'chief', 'child', 'childabuse',
       'childhero', 'childhood', 'childhoodfriends', 'childhoodmemory',
       'childhoodtrauma', 'childkidnapping', 'childmurder',
       'childmurderer', 'childprodigy', 'children', 'chile', 'chimp',
       'chimpanzee', 'china', 'china martialarts', 'chinatown', 'chinese',
       'chinesemafia', 'chloëgracemoretz', 'chocolate', 'choice',
       'choose', 'chris', 'chriscolumbus', 'chrisevans', 'chriso',
       'chrispine', 'chrisrock', 'christ', 'christian', 'christianbale',
       'christianclavier', 'christianity', 'christianslater',
       'christinaricci', 'christmas', 'christmas eve',
       'christmas holiday', 'christmaseve', 'christmasparty',
       'christmastree', 'christopherlee', 'christopherlloyd',
       'christophernolan', 'christopherplummer', 'christopherwalken',
       'chronicle', 'church', 'cia', 'cigarette', 'cigarettesmoking',
       'cigarsmoking', 'cinderella', 'cinema', 'circle', 'circus', 'city',
       'civil', 'civil war', 'civilization', 'civilwar', 'claim', 'clan',
       'clash', 'class', 'classdifferences', 'classic', 'classicnoir',
       'classmate', 'classroom', 'claudevandamme', 'claustrophobia',
       'clean', 'clear', 'clerk', 'client', 'climb', 'clinteastwood',
       'clinteastwood clinteastwood',
       'clinteastwood clinteastwood clinteastwood', 'clique', 'cliveowen',
       'clock', 'clocktower', 'clone', 'close', 'clown', 'club', 'clue',
       'coach', 'coast', 'cocaine', 'code', 'coffin', 'cold', 'coldwar',
       'colinfarrell', 'colinfirth', 'colleague', 'collect', 'collector',
       'college', 'college student', 'collegestudent', 'colombia',
       'colonel', 'colonialism', 'colony', 'colorado', 'coma', 'combat',
       'come', 'comeback', 'comedian', 'comedy', 'comedy action',
       'comedy action adventure', 'comedy action comedy',
       'comedy adventure', 'comedy adventure action',
       'comedy adventure comedy', 'comedy adventure family',
       'comedy animation', 'comedy animation comedy',
       'comedy animation family', 'comedy brazilian', 'comedy comedy',
       'comedy comedy comedy', 'comedy crime', 'comedy crime action',
       'comedy crime adventure', 'comedy crime comedy',
       'comedy crime drama', 'comedy crime mystery',
       'comedy crime romance', 'comedy crime thriller',
       'comedy documentary', 'comedy documentary comedy', 'comedy drama',
       'comedy drama action', 'comedy drama adventure',
       'comedy drama comedy', 'comedy drama crime', 'comedy drama family',
       'comedy drama fantasy', 'comedy drama history',
       'comedy drama horror', 'comedy drama music',
       'comedy drama mystery', 'comedy drama romance',
       'comedy drama sciencefiction', 'comedy drama thriller',
       'comedy drama war', 'comedy family', 'comedy family action',
       'comedy family adventure', 'comedy family animation',
       'comedy family comedy', 'comedy family drama',
       'comedy family fantasy', 'comedy family music',
       'comedy family romance', 'comedy family sciencefiction',
       'comedy fantasy', 'comedy fantasy comedy', 'comedy fantasy horror',
       'comedy fantasy romance', 'comedy fantasy sciencefiction',
       'comedy history', 'comedy horror', 'comedy horror action',
       'comedy horror comedy'], dtype=object)

In [126]:
from sklearn.metrics.pairwise import cosine_similarity

In [127]:
min_votes = movies["vote_count"].min()
max_votes = movies["vote_count"].max()

def norm_votes(v):
    return (v - min_votes) / (max_votes - min_votes)

In [136]:
def recommend(target_idx):
    sim_tfidf = cosine_similarity(tfidf_vectors[target_idx], tfidf_vectors).flatten()
    sim_sbert = cosine_similarity([sbert_vectors[target_idx]], sbert_vectors).flatten()
    
    combined_sim = (0.7 * sim_tfidf) + (0.3 * sim_sbert)
    
    similar_indices = sorted(
        list(enumerate(combined_sim)), 
        reverse=True, 
        key=lambda x: x[1]
    )[1:51]

    rec_list = []

    for i in similar_indices:
        idx_i = i[0]
        sim_score = i[1]
        temp_df = movies.iloc[idx_i]

        # Filter weak movies
        if temp_df["rating"] < 6.5:
            continue

        rating_score = temp_df["rating"] / 10
        popularity_score = norm_votes(temp_df["vote_count"])

        final_score = (
            0.6 * sim_score +
            0.25 * rating_score +
            0.15 * popularity_score
        )

        rec_list.append({
            "title": temp_df["title"],
            "rating": temp_df["rating"],
            "score": final_score
        })

    final_recommendations = sorted(
        rec_list, 
        key=lambda x: x["score"], 
        reverse=True
    )

    print(f"Top 10 High Quality Recommendation for {movies.loc[target_idx, 'title']}")
    print("-" * 30)

    rec = []
    for movie in final_recommendations[:10]:
        print(f"- {movie['title']} (Rating: {movie['rating']:.2f})")
        rec.append(movie["title"])

    return rec

In [137]:
def director_spotlight_by_idx(target_idx, n=5):
    target_director = movies.loc[target_idx, "crew"]

    director_movies = movies[(movies["crew"]==target_director) & (movies.index != target_idx)]

    target_director = movies.loc[target_idx, "director"]

    if director_movies.empty:
        return target_director, []

    top_director_df = director_movies.sort_values("rating", ascending = False).head(n)
    director_recs = top_director_df[["title", "rating"]].to_dict("records")

    return target_director, director_recs

In [138]:
def enhanced_recommend(movie_title):
    movie_title = movie_title.lower()

    match = movies[movies["title"].str.lower() == movie_title]

    if match.empty:
        match = movies[movies["title"].str.lower().str.contains(movie_title)]

    if match.empty:
        print("Movie not found 😅")
        return 

    target_idx = match.sort_values("rating", ascending=False).index[0]
    target_title = movies.loc[target_idx, "title"]

    print("\n" + "=" * 60)

    recommend(target_idx)

    director_name, dir_recs = director_spotlight_by_idx(target_idx)

    if dir_recs:
        print(f"\n🎥 Director's Spotlight: More from {director_name}")
        print("-" * 30)
        for d_movie in dir_recs:
            print(f"- {d_movie['title']} (Rating: {d_movie['rating']:.2f})")
    else:
        # Fixed the print here to use the pretty name variable too
        print(f"\n🎥 No other high-quality films by {director_name} in our database.")

In [139]:
movies_to_test = [
    "Finding Nemo",
    "Pulp Fiction",
    "The Avengers",
    "Inception",
    "The Dark Knight",
    "Toy Story",
    "Fight Club",
    "Interstellar",
    "Before Sunset",
    "Eternal Sunshine of the Spotless Mind",
    "Memento",
    "Taare Zameen Par",
    "Shutter Island",
    "Wolf of Wall Street",
    "Lord of the Rings",
    "Harry Potter",
    "12 Angry Men",
    "Pather Panchali",
    "Silence of the Lambs",
    "Schindler's List",
    "The Godfather",
    "prestige",
    "Incendies",
    "Psycho",
    "No Country for Old Men",
    "There will be blood",
    "Machinist"
]

In [140]:
def batch_recommend(movie_list):
    for movie in movie_list:
        print("\n" + "="*60)
        enhanced_recommend(movie)

In [141]:
batch_recommend(movies_to_test)

============================================================

============================================================
Top 10 High Quality Recommendation for Finding Nemo (2003)
------------------------------
- WALL·E (2008) (Rating: 7.79)
- Coraline (2009) (Rating: 7.28)
- Winnie the Pooh (2011) (Rating: 6.74)
- Monsters University (2013) (Rating: 6.99)
- Professor Layton and the Eternal Diva (2009) (Rating: 7.03)
- Wreck-It Ralph (2012) (Rating: 7.09)
- Anastasia (1997) (Rating: 7.38)
- Azur & Asmar: The Princes' Quest (2006) (Rating: 7.18)
- Ponyo (2008) (Rating: 7.46)
- The Sword in the Stone (1963) (Rating: 6.88)

🎥 Director's Spotlight: More from Andrew Stanton
------------------------------
- WALL·E (2008) (Rating: 7.79)
- John Carter (2012) (Rating: 6.10)

============================================================

============================================================
Top 10 High Quality Recommendation for Pulp Fiction (1994)
------------------------------
- Reservoir Dogs (1992) (Rating: 8.08)
- Snatch (2000) (Rating: 7.68)
- Million Dollar Baby (2004) (Rating: 7.68)
- The Night of the Hunter (1955) (Rating: 7.75)
- Ocean's Eleven (2001) (Rating: 7.19)
- Headhunters (2011) (Rating: 7.13)
- Raging Bull (1980) (Rating: 7.65)
- Jackie Brown (1997) (Rating: 7.28)
- A Pure Formality (1994) (Rating: 7.19)
- John Doe: Vigilante (2014) (Rating: 6.56)

🎥 Director's Spotlight: More from Quentin Tarantino
------------------------------
- Reservoir Dogs (1992) (Rating: 8.08)
- Inglourious Basterds (2009) (Rating: 7.89)
- Django Unchained (2012) (Rating: 7.80)
- Kill Bill: Vol. 1 (2003) (Rating: 7.69)
- Kill Bill: Vol. 2 (2004) (Rating: 7.69)

============================================================

============================================================
Top 10 High Quality Recommendation for The Avengers (2012)
------------------------------
- Captain America: The Winter Soldier (2014) (Rating: 7.59)
- Ant-Man (2015) (Rating: 7.00)
- Avengers: Age of Ultron (2015) (Rating: 7.30)
- Iron Man 3 (2013) (Rating: 6.80)
- Deadpool (2016) (Rating: 7.40)
- Thor: The Dark World (2013) (Rating: 6.80)
- Doctor Strange (2016) (Rating: 7.10)
- Captain America: The First Avenger (2011) (Rating: 6.60)
- Iron Man (2008) (Rating: 7.40)
- Captain America: Civil War (2016) (Rating: 7.10)

🎥 Director's Spotlight: More from Joss Whedon
------------------------------
- Serenity (2005) (Rating: 7.37)
- Avengers: Age of Ultron (2015) (Rating: 7.30)
- Much Ado About Nothing (2012) (Rating: 6.92)

============================================================

============================================================
Top 10 High Quality Recommendation for Inception (2010)
------------------------------
- Minority Report (2002) (Rating: 7.09)
- The Thirteenth Floor (1999) (Rating: 6.76)
- Super 8 (2011) (Rating: 6.60)
- Cube (1997) (Rating: 6.88)
- Source Code (2011) (Rating: 7.09)
- Looper (2012) (Rating: 6.60)
- Cypher (2002) (Rating: 6.64)
- Sherlock Holmes: A Game of Shadows (2011) (Rating: 6.99)
- The Matrix Reloaded (2003) (Rating: 6.70)
- Déjà Vu (2006) (Rating: 6.59)

🎥 Director's Spotlight: More from Christopher Nolan
------------------------------
- The Dark Knight (2008) (Rating: 8.29)
- Interstellar (2014) (Rating: 8.09)
- Memento (2000) (Rating: 8.09)
- The Prestige (2006) (Rating: 7.99)
- The Dark Knight Rises (2012) (Rating: 7.60)

============================================================

============================================================
Top 10 High Quality Recommendation for The Dark Knight (2008)
------------------------------
- The Dark Knight Rises (2012) (Rating: 7.60)
- Batman Begins (2005) (Rating: 7.49)
- Batman: Under the Red Hood (2010) (Rating: 7.51)
- Batman Returns (1992) (Rating: 6.59)
- Batman (1989) (Rating: 6.99)
- The Lego Batman Movie (2017) (Rating: 7.18)
- Batman: Assault on Arkham (2014) (Rating: 7.20)
- Kick-Ass (2010) (Rating: 7.09)
- Wonder Woman (2017) (Rating: 7.19)
- Batman vs. Robin (2015) (Rating: 6.73)

🎥 Director's Spotlight: More from Christopher Nolan
------------------------------
- Inception (2010) (Rating: 8.10)
- Interstellar (2014) (Rating: 8.09)
- Memento (2000) (Rating: 8.09)
- The Prestige (2006) (Rating: 7.99)
- The Dark Knight Rises (2012) (Rating: 7.60)

============================================================

============================================================
Top 10 High Quality Recommendation for Toy Story (1995)
------------------------------
- Toy Story 2 (1999) (Rating: 7.29)
- Monsters, Inc. (2001) (Rating: 7.49)
- Toy Story 3 (2010) (Rating: 7.59)
- Up (2009) (Rating: 7.79)
- Despicable Me 2 (2013) (Rating: 7.00)
- The Lego Movie (2014) (Rating: 7.49)
- Frankenweenie (2012) (Rating: 6.59)
- The SpongeBob SquarePants Movie (2004) (Rating: 6.68)
- Meet the Robinsons (2007) (Rating: 6.68)
- The Simpsons Movie (2007) (Rating: 6.89)

🎥 Director's Spotlight: More from John Lasseter
------------------------------
- Toy Story 2 (1999) (Rating: 7.29)
- A Bug's Life (1998) (Rating: 6.79)

============================================================

============================================================
Top 10 High Quality Recommendation for Fight Club (1999)
------------------------------
- Se7en (1995) (Rating: 8.09)
- Gone Girl (2014) (Rating: 7.89)
- The Social Network (2010) (Rating: 7.09)
- The Machinist (2004) (Rating: 7.27)
- One Flew Over the Cuckoo's Nest (1975) (Rating: 8.28)
- Mouchette (1967) (Rating: 6.88)
- Kill Bill: Vol. 2 (2004) (Rating: 7.69)
- The Curious Case of Benjamin Button (2008) (Rating: 7.29)
- I Stand Alone (1998) (Rating: 7.20)
- The Game (1997) (Rating: 7.47)

🎥 Director's Spotlight: More from David Fincher
------------------------------
- Se7en (1995) (Rating: 8.09)
- Gone Girl (2014) (Rating: 7.89)
- The Game (1997) (Rating: 7.47)
- The Curious Case of Benjamin Button (2008) (Rating: 7.29)
- Zodiac (2007) (Rating: 7.28)

============================================================

============================================================
Top 10 High Quality Recommendation for Interstellar (2014)
------------------------------
- The Martian (2015) (Rating: 7.59)
- Guardians of the Galaxy (2014) (Rating: 7.89)
- The Matrix (1999) (Rating: 7.89)
- Apollo 13 (1995) (Rating: 7.28)
- Rogue One: A Star Wars Story (2016) (Rating: 7.39)
- Passengers (2016) (Rating: 6.70)
- 2001: A Space Odyssey (1968) (Rating: 7.88)
- Planet of the Apes (1968) (Rating: 7.46)
- The Matrix Reloaded (2003) (Rating: 6.70)
- The Fifth Element (1997) (Rating: 7.29)

🎥 Director's Spotlight: More from Christopher Nolan
------------------------------
- The Dark Knight (2008) (Rating: 8.29)
- Inception (2010) (Rating: 8.10)
- Memento (2000) (Rating: 8.09)
- The Prestige (2006) (Rating: 7.99)
- The Dark Knight Rises (2012) (Rating: 7.60)

============================================================

============================================================
Top 10 High Quality Recommendation for Before Sunset (2004)
------------------------------
- Before Sunrise (1995) (Rating: 7.65)
- Two Lovers (2008) (Rating: 6.55)
- The Notebook (2004) (Rating: 7.69)
- Letter from an Unknown Woman (1948) (Rating: 7.44)
- Veer-Zaara (2004) (Rating: 7.10)
- Frida (2002) (Rating: 7.22)
- Before Midnight (2013) (Rating: 7.25)
- The Magnificent Ambersons (1942) (Rating: 7.14)
- An Officer and a Gentleman (1982) (Rating: 6.74)
- Charade (1963) (Rating: 7.58)

🎥 Director's Spotlight: More from Richard Linklater
------------------------------
- Before Sunrise (1995) (Rating: 7.65)
- Boyhood (2014) (Rating: 7.48)
- Waking Life (2001) (Rating: 7.45)
- Dazed and Confused (1993) (Rating: 7.34)
- Before Midnight (2013) (Rating: 7.25)

============================================================

============================================================
Top 10 High Quality Recommendation for Eternal Sunshine of the Spotless Mind (2004)
------------------------------
- Her (2013) (Rating: 7.89)
- Nineteen Eighty-Four (1984) (Rating: 6.75)
- In Your Eyes (2014) (Rating: 7.01)
- Never Let Me Go (2010) (Rating: 6.78)
- Mr. Nobody (2009) (Rating: 7.87)
- Arrival (2016) (Rating: 7.19)
- Comet (2014) (Rating: 6.71)
- On the Beach (1959) (Rating: 6.56)
- Safety Not Guaranteed (2012) (Rating: 6.77)
- Facing Windows (2003) (Rating: 6.74)

🎥 Director's Spotlight: More from Michel Gondry
------------------------------
- The Science of Sleep (2006) (Rating: 6.74)
- Be Kind Rewind (2008) (Rating: 6.21)
- Human Nature (2001) (Rating: 6.17)
- Microbe and Gasoline (2015) (Rating: 6.15)
- Mood Indigo (2013) (Rating: 6.05)

============================================================

============================================================
Top 10 High Quality Recommendation for Memento (2000)
------------------------------
- Insomnia (2002) (Rating: 6.79)
- Salton Sea (2002) (Rating: 6.84)
- Following (1998) (Rating: 7.12)
- Chinatown (1974) (Rating: 7.84)
- The Last Seduction (1994) (Rating: 6.59)
- Blue Ruin (2014) (Rating: 6.86)
- Near Dark (1987) (Rating: 6.71)
- Le Trou (1960) (Rating: 7.60)
- New World (2013) (Rating: 7.00)
- The Aura (2005) (Rating: 6.64)

🎥 Director's Spotlight: More from Christopher Nolan
------------------------------
- The Dark Knight (2008) (Rating: 8.29)
- Inception (2010) (Rating: 8.10)
- Interstellar (2014) (Rating: 8.09)
- The Prestige (2006) (Rating: 7.99)
- The Dark Knight Rises (2012) (Rating: 7.60)

============================================================

============================================================
Top 10 High Quality Recommendation for Taare Zameen Par (2007)
------------------------------
- Like Father, Like Son (2013) (Rating: 7.32)
- The Hunt (2012) (Rating: 7.85)
- The Chorus (2004) (Rating: 7.43)
- Kes (1969) (Rating: 7.26)
- Dilwale Dulhania Le Jayenge (1995) (Rating: 8.96)
- Lion (2016) (Rating: 7.97)
- Skirt Day (2008) (Rating: 6.81)
- Glory Road (2006) (Rating: 7.03)
- Swades: We, the People (2004) (Rating: 7.00)
- Coach Carter (2005) (Rating: 7.24)

🎥 No other high-quality films by Aamir Khan in our database.

============================================================

============================================================
Top 10 High Quality Recommendation for Shutter Island (2010)
------------------------------
- Confessions (2010) (Rating: 7.44)
- Before I Fall (2017) (Rating: 6.78)
- The Game (1997) (Rating: 7.47)
- Murder on the Orient Express (1974) (Rating: 6.83)
- Death and the Maiden (1994) (Rating: 6.89)
- The Collector (1965) (Rating: 6.63)
- Pi (1998) (Rating: 7.06)
- Tinker Tailor Soldier Spy (2011) (Rating: 6.59)
- Oldboy (2003) (Rating: 7.97)
- Arlington Road (1999) (Rating: 6.92)

🎥 Director's Spotlight: More from Martin Scorsese
------------------------------
- GoodFellas (1990) (Rating: 8.18)
- Taxi Driver (1976) (Rating: 8.08)
- The Wolf of Wall Street (2013) (Rating: 7.89)
- The Departed (2006) (Rating: 7.89)
- Casino (1995) (Rating: 7.76)

============================================================

============================================================
Top 10 High Quality Recommendation for The Wolf of Wall Street (2013)
------------------------------
- War Dogs (2016) (Rating: 6.79)
- Adaptation. (2002) (Rating: 7.25)
- Gentlemen of Fortune (1971) (Rating: 6.90)
- The Ax (2005) (Rating: 6.67)
- The Big Short (2015) (Rating: 7.29)
- Filth (2013) (Rating: 6.78)
- Four Lions (2010) (Rating: 7.04)
- Spun (2002) (Rating: 6.54)
- The Sting (1973) (Rating: 7.82)
- Inside Job (2010) (Rating: 7.55)

🎥 Director's Spotlight: More from Martin Scorsese
------------------------------
- GoodFellas (1990) (Rating: 8.18)
- Taxi Driver (1976) (Rating: 8.08)
- The Departed (2006) (Rating: 7.89)
- Shutter Island (2010) (Rating: 7.79)
- Casino (1995) (Rating: 7.76)

============================================================

============================================================
Top 10 High Quality Recommendation for The Lord of the Rings: The Return of the King (2003)
------------------------------
- The Lord of the Rings: The Two Towers (2002) (Rating: 7.99)
- The Lord of the Rings: The Fellowship of the Ring (2001) (Rating: 7.99)
- The Hobbit: The Battle of the Five Armies (2014) (Rating: 7.09)
- The Hobbit: An Unexpected Journey (2012) (Rating: 7.00)
- The Hobbit: The Desolation of Smaug (2013) (Rating: 7.59)
- Thor (2011) (Rating: 6.60)
- Conan the Barbarian (1982) (Rating: 6.59)
- Thor: The Dark World (2013) (Rating: 6.80)
- Pirates of the Caribbean: Dead Man's Chest (2006) (Rating: 7.00)
- Wonder Woman (2017) (Rating: 7.19)

🎥 Director's Spotlight: More from Peter Jackson
------------------------------
- The Lord of the Rings: The Fellowship of the Ring (2001) (Rating: 7.99)
- The Lord of the Rings: The Two Towers (2002) (Rating: 7.99)
- The Hobbit: The Desolation of Smaug (2013) (Rating: 7.59)
- Braindead (1992) (Rating: 7.31)
- The Hobbit: The Battle of the Five Armies (2014) (Rating: 7.09)

============================================================

============================================================
Top 10 High Quality Recommendation for Harry Potter and the Deathly Hallows: Part 2 (2011)
------------------------------
- Fantastic Beasts and Where to Find Them (2016) (Rating: 7.19)
- Return to Oz (1985) (Rating: 6.54)
- Harry Potter and the Philosopher's Stone (2001) (Rating: 7.49)
- Harry Potter and the Goblet of Fire (2005) (Rating: 7.49)
- Harry Potter and the Chamber of Secrets (2002) (Rating: 7.39)
- Harry Potter and the Prisoner of Azkaban (2004) (Rating: 7.69)
- Harry Potter and the Order of the Phoenix (2007) (Rating: 7.39)
- Sapphire Blue (2014) (Rating: 6.84)
- Harry Potter and the Half-Blood Prince (2009) (Rating: 7.39)
- Jason and the Argonauts (1963) (Rating: 6.95)

🎥 Director's Spotlight: More from David Yates
------------------------------
- Harry Potter and the Deathly Hallows: Part 1 (2010) (Rating: 7.49)
- Harry Potter and the Order of the Phoenix (2007) (Rating: 7.39)
- Harry Potter and the Half-Blood Prince (2009) (Rating: 7.39)
- Fantastic Beasts and Where to Find Them (2016) (Rating: 7.19)
- The Legend of Tarzan (2016) (Rating: 5.51)

============================================================

============================================================
Top 10 High Quality Recommendation for 12 Angry Men (1957)
------------------------------
- The Verdict (1982) (Rating: 7.18)
- 12 Angry Men (1997) (Rating: 7.07)
- Philadelphia (1993) (Rating: 7.56)
- Runaway Jury (2003) (Rating: 6.85)
- The Judge (2014) (Rating: 7.18)
- Anatomy of a Murder (1959) (Rating: 7.51)
- A Time to Kill (1996) (Rating: 6.96)
- The Rainmaker (1997) (Rating: 6.65)
- To Kill a Mockingbird (1962) (Rating: 7.82)
- Spotlight (2015) (Rating: 7.78)

🎥 Director's Spotlight: More from Sidney Lumet
------------------------------
- Network (1976) (Rating: 7.68)
- Dog Day Afternoon (1975) (Rating: 7.54)
- Serpico (1973) (Rating: 7.41)
- Fail-Safe (1964) (Rating: 7.23)
- The Verdict (1982) (Rating: 7.18)

============================================================

============================================================
Top 10 High Quality Recommendation for Pather Panchali (1955)
------------------------------
- The World of Apu (1959) (Rating: 7.34)
- Calvary (2014) (Rating: 7.03)
- 8½ (1963) (Rating: 7.78)
- Diary of a Country Priest (1951) (Rating: 7.07)
- Aparajito (1956) (Rating: 7.21)
- The Life of Oharu (1952) (Rating: 7.42)
- Departures (2008) (Rating: 7.50)
- Taare Zameen Par (2007) (Rating: 7.49)
- Bicycle Thieves (1948) (Rating: 7.87)
- Not One Less (1999) (Rating: 6.93)

🎥 Director's Spotlight: More from Satyajit Ray
------------------------------
- The World of Apu (1959) (Rating: 7.34)
- Aparajito (1956) (Rating: 7.21)

============================================================

============================================================
Top 10 High Quality Recommendation for The Silence of the Lambs (1991)
------------------------------
- Red Dragon (2002) (Rating: 6.69)
- Animal Kingdom (2010) (Rating: 6.65)
- I Saw the Devil (2010) (Rating: 7.52)
- Manhunter (1986) (Rating: 6.76)
- Antibodies (2005) (Rating: 6.52)
- End of Watch (2012) (Rating: 7.18)
- Dog Day Afternoon (1975) (Rating: 7.54)
- Road to Perdition (2002) (Rating: 7.27)
- Inside Man (2006) (Rating: 7.28)
- Zulu (2013) (Rating: 6.64)

🎥 Director's Spotlight: More from Jonathan Demme
------------------------------
- Stop Making Sense (1984) (Rating: 7.70)
- Philadelphia (1993) (Rating: 7.56)
- Something Wild (1986) (Rating: 6.44)
- The Manchurian Candidate (2004) (Rating: 6.21)
- Rachel Getting Married (2008) (Rating: 6.14)

============================================================

============================================================
Top 10 High Quality Recommendation for Schindler's List (1993)
------------------------------
- Come and See (1985) (Rating: 7.81)
- The Boy in the Striped Pyjamas (2008) (Rating: 7.67)
- Stalingrad (1993) (Rating: 7.15)
- Land of Mine (2015) (Rating: 7.64)
- Saving Private Ryan (1998) (Rating: 7.89)
- Winter in Wartime (2008) (Rating: 6.64)
- Hacksaw Ridge (2016) (Rating: 7.78)
- Katyn (2007) (Rating: 6.55)
- The Round Up (2010) (Rating: 7.39)
- Max Manus: Man of War (2008) (Rating: 6.73)

🎥 Director's Spotlight: More from Steven Spielberg
------------------------------
- Saving Private Ryan (1998) (Rating: 7.89)
- Raiders of the Lost Ark (1981) (Rating: 7.69)
- Catch Me If You Can (2002) (Rating: 7.69)
- Jurassic Park (1993) (Rating: 7.59)
- Indiana Jones and the Last Crusade (1989) (Rating: 7.59)

============================================================

============================================================
Top 10 High Quality Recommendation for The Godfather (1972)
------------------------------
- The Godfather: Part II (1974) (Rating: 8.28)
- The Shawshank Redemption (1994) (Rating: 8.49)
- The Consequences of Love (2004) (Rating: 7.33)
- GoodFellas (1990) (Rating: 8.18)
- The Godfather: Part III (1990) (Rating: 7.08)
- One Hundred Steps (2000) (Rating: 7.46)
- Election (2005) (Rating: 6.55)
- Il Divo (2008) (Rating: 7.30)
- Election 2 (2006) (Rating: 6.73)
- Serial Killer 1 (2015) (Rating: 6.81)

🎥 Director's Spotlight: More from Francis Ford Coppola
------------------------------
- The Godfather: Part II (1974) (Rating: 8.28)
- Apocalypse Now (1979) (Rating: 7.97)
- The Conversation (1974) (Rating: 7.40)
- The Godfather: Part III (1990) (Rating: 7.08)
- Dracula (1992) (Rating: 7.08)

============================================================

============================================================
Top 10 High Quality Recommendation for The Prestige (2006)
------------------------------
- Gone Girl (2014) (Rating: 7.89)
- The Return (2003) (Rating: 7.13)
- The Sixth Sense (1999) (Rating: 7.69)
- Page Eight (2011) (Rating: 6.63)
- The Constant Gardener (2005) (Rating: 6.86)
- The Firm (1993) (Rating: 6.58)
- Disturbia (2007) (Rating: 6.59)
- Blow Out (1981) (Rating: 7.18)
- Rebecca (1940) (Rating: 7.58)
- Spellbound (1945) (Rating: 7.13)

🎥 Director's Spotlight: More from Christopher Nolan
------------------------------
- The Dark Knight (2008) (Rating: 8.29)
- Inception (2010) (Rating: 8.10)
- Interstellar (2014) (Rating: 8.09)
- Memento (2000) (Rating: 8.09)
- The Dark Knight Rises (2012) (Rating: 7.60)

============================================================

============================================================
Top 10 High Quality Recommendation for Incendies (2010)
------------------------------
- Feed (2017) (Rating: 6.90)
- Waltz with Bashir (2008) (Rating: 7.65)
- Black Narcissus (1947) (Rating: 7.36)
- Taste of Cherry (1997) (Rating: 6.86)
- The Message (1977) (Rating: 7.08)
- Escape Plan (2013) (Rating: 6.69)
- Before the Rain (1994) (Rating: 7.11)
- The Battle of Algiers (1966) (Rating: 7.55)
- Testament of Youth (2014) (Rating: 7.10)
- Don't Worry, I'm Fine (2006) (Rating: 7.13)


In [134]:
import pickle

In [135]:
with open("movie_embeddings.pkl", "wb") as f:
    pickle.dump(sbert_vectors, f)

with open("movie_tfidf.pkl", "wb") as f:
    pickle.dump(tfidf_vectors, f)

movies.to_csv("movies_final_level7.csv", index = False)